import { promises as fs } from "fs";
import { join } from "path";

import * as Context from "effect/Context";
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import * as Schema from "effect/Schema";

import { DesktopEnvironment } from "../app/DesktopEnvironment";
import { resolveScriptWorkspacePaths } from "./ScriptWorkspacePaths";

const scriptWorkspaceOperationSchema = Schema.Literals([
  "copy-types",
  "create-config",
  "create-directory",
]);

export class ScriptWorkspaceError extends Schema.TaggedErrorClass<ScriptWorkspaceError>()(
  "ScriptWorkspaceError",
  {
    operation: scriptWorkspaceOperationSchema,
    path: Schema.String,
    cause: Schema.Defect(),
  },
) {
  override get message(): string {
    return `Script workspace ${this.operation} failed at ${this.path}.`;
  }
}

export interface ScriptWorkspaceShape {
  readonly initialize: Effect.Effect<void, ScriptWorkspaceError>;
}

export class ScriptWorkspace extends Context.Service<
  ScriptWorkspace,
  ScriptWorkspaceShape
>()("lucent/desktop/scripting/ScriptWorkspace") {}

export const SCRIPT_WORKSPACE_CONFIG = `${JSON.stringify(
  {
    compilerOptions: {
      target: "ES2020",
      module: "CommonJS",
      moduleResolution: "Node",
      lib: ["ES2020", "DOM"],
      checkJs: false,
      skipLibCheck: true,
      baseUrl: "./packages",
    },
    include: [
      "script-api.d.ts",
      "scripts/**/*.js",
      "scripts/**/*.cjs",
      "scripts/**/*.d.ts",
      "packages/**/*.js",
      "packages/**/*.cjs",
      "packages/**/*.d.ts",
    ],
  },
  null,
  2,
)}\n`;

const GENERATED_TYPES_PREFIX =
  "// Generated by pnpm run types:scripting. Do not edit directly.";

const hasErrorCode = (cause: unknown, code: string): boolean =>
  cause instanceof Error && "code" in cause && cause.code === code;

const isAlreadyPresent = (cause: unknown): boolean =>
  hasErrorCode(cause, "EEXIST");

const isMissing = (cause: unknown): boolean => hasErrorCode(cause, "ENOENT");

const makeError = (
  operation: typeof scriptWorkspaceOperationSchema.Type,
  path: string,
  cause: unknown,
) => new ScriptWorkspaceError({ operation, path, cause });

export const layer = Layer.effect(
  ScriptWorkspace,
  Effect.gen(function* () {
    const env = yield* DesktopEnvironment;
    const { dataDir, packagesDir, scriptsDir } = resolveScriptWorkspacePaths(
      env.workspaceDir,
    );
    const configPath = join(env.workspaceDir, "jsconfig.json");
    const typesPath = join(env.workspaceDir, "script-api.d.ts");
    const templatePath = env.isDev
      ? join(env.assetsDir, "..", "docs", "public", "script-api.d.ts")
      : join(env.assetsDir, "..", "script-api.d.ts");

    const createDirectory = (path: string) =>
      Effect.tryPromise({
        try: () => fs.mkdir(path, { recursive: true }),
        catch: (cause) => makeError("create-directory", path, cause),
      }).pipe(Effect.asVoid);

    const createPrivateDirectory = (path: string) =>
      Effect.tryPromise({
        try: async () => {
          await fs.mkdir(path, { mode: 0o700, recursive: true });
          const info = await fs.lstat(path);
          if (!info.isDirectory()) {
            throw new Error(`Expected a directory at ${path}.`);
          }
          if (env.platform !== "win32") await fs.chmod(path, 0o700);
        },
        catch: (cause) => makeError("create-directory", path, cause),
      });

    const createConfig = Effect.tryPromise({
      try: () =>
        fs.writeFile(configPath, SCRIPT_WORKSPACE_CONFIG, {
          encoding: "utf8",
          flag: "wx",
        }),
      catch: (cause) => makeError("create-config", configPath, cause),
    }).pipe(
      Effect.catch((error) =>
        isAlreadyPresent(error.cause) ? Effect.void : Effect.fail(error),
      ),
    );

    const copyTypes = Effect.tryPromise({
      try: async () => {
        let current: string | undefined;
        try {
          current = await fs.readFile(typesPath, "utf8");
        } catch (cause) {
          if (!isMissing(cause)) throw cause;
        }
        if (
          current !== undefined &&
          !current.startsWith(GENERATED_TYPES_PREFIX)
        ) {
          return;
        }
        await fs.copyFile(templatePath, typesPath);
      },
      catch: (cause) => makeError("copy-types", typesPath, cause),
    });

    return ScriptWorkspace.of({
      initialize: Effect.gen(function* () {
        yield* createDirectory(env.workspaceDir);
        yield* Effect.all(
          [
            createDirectory(scriptsDir),
            createDirectory(packagesDir),
            createPrivateDirectory(dataDir),
          ],
          { concurrency: 3, discard: true },
        );
        yield* Effect.all([createConfig, copyTypes], {
          concurrency: 2,
          discard: true,
        });
      }),
    });
  }),
);
