// Generated by pnpm run types:scripting. Do not edit directly.

/* eslint-disable */

type ScriptPipe = {
  <A>(value: A): A;
  <A, B>(value: A, ab: (a: A) => B): B;
  <A, B, C>(value: A, ab: (a: A) => B, bc: (b: B) => C): C;
  <A, B, C, D>(
    value: A,
    ab: (a: A) => B,
    bc: (b: B) => C,
    cd: (c: C) => D,
  ): D;
};

interface ScriptEffectModule {
  readonly [key: string]: any;
}

interface ScriptOptionModule {
  some<Value>(value: Value): Option<Value>;
  none<Value = never>(): Option<Value>;
  isSome<Value>(
    option: Option<Value>,
  ): option is { readonly _tag: "Some"; readonly value: Value };
  isNone<Value>(option: Option<Value>): option is { readonly _tag: "None" };
  readonly [key: string]: any;
}

interface ScriptOpaqueModule {
  readonly [key: string]: any;
}

interface ScriptEffectStd {
  readonly Effect: ScriptEffectModule;
  readonly Option: ScriptOptionModule;
  readonly Duration: ScriptOpaqueModule;
  readonly pipe: ScriptPipe;
}

declare module "effect" {
  const effect: ScriptEffectStd;
  export = effect;
}

declare module "lucent" {
  const lucent: ScriptLucentStd;
  namespace lucent {
    export type ScriptInputValue = LucentScriptInputValue;
    export type ScriptInputType = LucentScriptInputType;
    export type ScriptInputField = LucentScriptInputField;
    export type ScriptInputsDefinition = LucentScriptInputsDefinition;
    export type ScriptInputValues = LucentScriptInputValues;
    export type ScriptModuleExports = LucentScriptModuleExports;
  }
  export = lucent;
}

type DurationInput = number | string | bigint | DurationLike;

interface DurationLike {
  readonly _tag?: string;
}

type Option<Value> =
  | { readonly _tag: "Some"; readonly value: Value }
  | { readonly _tag: "None" };

type EffectYieldable<
  Value = unknown,
  Error = unknown,
  Requirements = never,
  Next = never,
> = unknown;

interface Effect<
  Value = unknown,
  Error = unknown,
  Requirements = never,
> {
  [Symbol.iterator](): Generator<EffectYieldable<Value, Error>, Value, any>;
}

interface ScriptExecutionError extends Error {
  readonly _tag: "ScriptExecutionError";
}

interface ScriptNotReadyError extends Error {
  readonly _tag: "ScriptNotReadyError";
}

interface ScriptStopSignal extends Error {
  readonly _tag: "ScriptStopSignal";
}

type Skill = number | string;

type LucentScriptInputValue = string | number | boolean;
type LucentScriptInputType = "string" | "number" | "boolean" | "select";

interface LucentScriptInputFieldBase<
  Type extends LucentScriptInputType,
  Value extends LucentScriptInputValue,
> {
  /** Stable key used by script.inputs.get(key). */
  readonly key: string;
  readonly type: Type;
  readonly label: string;
  readonly description?: string;
  readonly required?: boolean;
  readonly default?: Value;
}

interface LucentScriptStringInputField
  extends LucentScriptInputFieldBase<"string", string> {}

interface LucentScriptNumberInputField
  extends LucentScriptInputFieldBase<"number", number> {}

interface LucentScriptBooleanInputField
  extends LucentScriptInputFieldBase<"boolean", boolean> {}

interface LucentScriptSelectInputField
  extends LucentScriptInputFieldBase<"select", string> {
  readonly options: readonly string[];
}

type LucentScriptInputField =
  | LucentScriptStringInputField
  | LucentScriptNumberInputField
  | LucentScriptBooleanInputField
  | LucentScriptSelectInputField;

interface LucentScriptInputsDefinition {
  /** Stable id used to persist values for this script. */
  readonly id: string;
  readonly fields: readonly LucentScriptInputField[];
}

type LucentScriptInputValues = Readonly<Record<string, LucentScriptInputValue>>;

interface LucentScriptModuleExports extends ScriptMain {
  inputs?: LucentScriptInputsDefinition;
}

type ScriptInputValue = LucentScriptInputValue;
type ScriptInputType = LucentScriptInputType;
type ScriptInputField = LucentScriptInputField;
interface ScriptInputsDefinition extends LucentScriptInputsDefinition {}
type ScriptInputValues = LucentScriptInputValues;
type ScriptModuleExports = LucentScriptModuleExports;

type ScriptMain = () => Generator<Effect<any, any, never>, unknown, any>;

interface ScriptContext {
    readonly api: ScriptApi;
    readonly features: ScriptFeaturesApi;
    readonly script: ScriptRuntimeApi;
}
interface ScriptLucentStd {
    readonly api: ScriptApi;
    readonly features: ScriptFeaturesApi;
    readonly script: ScriptRuntimeApi;
}
interface ScriptApi {
    readonly army: ScriptArmyApi;
    readonly auth: ScriptAuthApi;
    readonly bank: ScriptBankApi;
    readonly combat: ScriptCombatApi;
    readonly drops: ScriptDropsApi;
    readonly events: ScriptEventsApi;
    readonly house: ScriptHouseApi;
    readonly inventory: ScriptInventoryApi;
    readonly map: ScriptMapApi;
    readonly monsters: ScriptMonstersApi;
    readonly packet: ScriptPacketApi;
    readonly player: ScriptPlayerApi;
    readonly players: ScriptPlayersApi;
    readonly quests: ScriptQuestsApi;
    readonly settings: ScriptSettingsApi;
    readonly shops: ScriptShopsApi;
    readonly tempInventory: ScriptTempInventoryApi;
    readonly wait: ScriptWaitApi;
}
interface ScriptRuntimeApi {
    readonly signal: AbortSignal;
    readonly inputs: ScriptRuntimeInputsApi;
    readonly options: ScriptRuntimeOptionsApi;
    exit(options?: { readonly closeWindow?: boolean; readonly logout?: boolean; }): Effect<never, ScriptStopSignal>;
    log(message: unknown): Effect<void, never>;
    sleep(ms: number): Effect<void, ScriptExecutionError>;
    stop(reason?: string): Effect<never, ScriptStopSignal>;
}
interface ScriptArmyApi {
    equipSet(setName: string, options?: ArmyEquipSetOptions): Effect<void, ArmyError>;
    executeWithArmy<A, E>(action: Effect<A, E, never>): Effect<A, E | ArmyError>;
    getConfigString(key: string, defaultValue?: string): Effect<string, never>;
    getConfigValue(key: string, defaultValue?: unknown): Effect<unknown, never>;
    getPlayerNumber(): Effect<number, never>;
    getSession(): Effect<ArmySession | null, never>;
    isLeader(): Effect<boolean, never>;
    isMember(): Effect<boolean, never>;
    isStarted(): Effect<boolean, never>;
    joinMap(map: string, cell?: string, pad?: string): Effect<void, ArmyError>;
    kill(target: MonsterQuery, options?: CombatKillOptions): Effect<void, ArmyError>;
    killForItem(target: MonsterQuery, item: ItemQuery, quantity?: number, options?: CombatKillOptions): Effect<void, ArmyError>;
    killForTempItem(target: MonsterQuery, item: ItemQuery, quantity?: number, options?: CombatKillOptions): Effect<void, ArmyError>;
    leave(): Effect<void, never>;
    runStep<A, E>(label: string, action: Effect<A, E, never>, options?: ArmyRunStepOptions): Effect<A, E | ArmyError>;
    start(configName: string): Effect<ArmySession, ArmyError>;
    sync(label?: string, options?: ArmyRunStepOptions): Effect<void, ArmyError>;
}
interface ScriptAuthApi {
    connectTo(server: string): Effect<AuthConnectOutcome, never>;
    getPassword(): Effect<string, never>;
    getServers(): Effect<readonly Server[], never>;
    getUsername(): Effect<string, never>;
    isLoggedIn(): Effect<boolean, never>;
    isServerSelectReady(): Effect<boolean, never>;
    isTemporarilyKicked(): Effect<boolean, never>;
    login(username: string, password: string): Effect<boolean, never>;
    logout(): Effect<void, never>;
}
interface ScriptBankApi {
    contains(selector: ItemQuery, quantity?: number): Effect<boolean, never>;
    deposit(selector: ItemQuery): Effect<boolean, never>;
    depositBatch(selectors: readonly ItemQuery[]): Effect<readonly boolean[], never>;
    get(selector: ItemQuery): Effect<Item | null, never>;
    getAll(): Effect<readonly Item[], never>;
    getAvailableSlots(): Effect<number, never>;
    getSlots(): Effect<number, never>;
    getUsedSlots(): Effect<number, never>;
    isOpen(): Effect<boolean, never>;
    open(force?: boolean): Effect<boolean, never>;
    swap(inventorySelector: ItemQuery, bankSelector: ItemQuery): Effect<boolean, never>;
    withdraw(selector: ItemQuery): Effect<boolean, never>;
    withdrawBatch(selectors: readonly ItemQuery[]): Effect<readonly boolean[], never>;
}
interface ScriptCombatApi {
    attackMonster(selector: MonsterQuery): Effect<boolean, never>;
    cancelAutoAttack(): Effect<void, never>;
    cancelTarget(): Effect<void, never>;
    canUseSkill(index: Skill): Effect<boolean, never>;
    exit(): Effect<boolean, never>;
    getConsumableSkillItem(): Effect<{ readonly itemId: number; } | null, never>;
    hunt(selector: MonsterQuery, options?: HuntOptions): Effect<Monster | null, never>;
    kill(selector: MonsterQuery, options?: CombatKillOptions): Effect<boolean, never>;
    killForItem(monster: MonsterQuery, item: ItemQuery, quantity?: number, options?: CombatKillOptions): Effect<boolean, never>;
    killForTempItem(monster: MonsterQuery, item: ItemQuery, quantity?: number, options?: CombatKillOptions): Effect<boolean, never>;
    readonly target: ScriptCombatTargetApi;
    useSkill(index: Skill, options?: SkillUseOptions): Effect<boolean, never>;
}
interface ScriptCombatTargetApi {
    readonly auras: ScriptCombatTargetAurasApi;
    get(): Effect<TargetInfo | null, never>;
}
interface ScriptCombatTargetAurasApi {
    get(auraName: string, options?: AuraQueryOptions): Effect<Aura | null, never>;
    getAll(options?: AuraQueryOptions): Effect<readonly Aura[], never>;
    has(auraName: string, options?: AuraQueryOptions): Effect<boolean, never>;
}
interface ScriptDropsApi {
    accept(selector: ItemQuery): Effect<boolean, never>;
    contains(selector: ItemQuery): Effect<boolean, never>;
    getAll(): Effect<readonly Item[], never>;
    isCustomUiEnabled(): Effect<boolean, never>;
    reject(selector: ItemQuery): Effect<boolean, never>;
    toggleUi(): Effect<void, never>;
}
interface ScriptEventsApi {
    on(selector: EventSelector | undefined, handler: FlashEventHandler): Effect<() => void, never>;
    once(selector?: EventSelector, options?: WaitOptions): Effect<FlashEvent | null, never>;
}
interface ScriptFeaturesAntiCounterApi {
    isEnabled(): Effect<boolean, never>;
    setEnabled(enabled: boolean): Effect<void, never>;
}
interface ScriptFeaturesApi {
    readonly antiCounter: ScriptFeaturesAntiCounterApi;
    readonly autoRelogin: ScriptFeaturesAutoReloginApi;
    readonly autoZone: ScriptFeaturesAutoZoneApi;
}
interface ScriptFeaturesAutoReloginApi {
    disable(): Effect<AutoReloginState, never>;
    enable(): Effect<AutoReloginState, never>;
    getDelay(): Effect<number, never>;
    getServer(): Effect<string | undefined, never>;
    getState(): Effect<AutoReloginState, never>;
    isEnabled(): Effect<boolean, never>;
    onState(listener: (state: AutoReloginState) => void, options?: StateSubscriptionOptions): Effect<StateDisposer, never>;
    runLogin(request: AutoReloginLoginRequest): Effect<AutoReloginLoginResult, AutoReloginLoginError>;
    setDelay(delayMs: number): Effect<AutoReloginState, never>;
    setEnabled(enabled: boolean): Effect<AutoReloginState, never>;
    setServer(serverName: string): Effect<AutoReloginState, never>;
}
interface ScriptFeaturesAutoZoneApi {
    getMap(): Effect<AutoZoneSupportedMap | undefined, never>;
    getState(): Effect<AutoZoneState, never>;
    isEnabled(): Effect<boolean, never>;
    onState(listener: (state: AutoZoneState) => void, options?: StateSubscriptionOptions): Effect<StateDisposer, never>;
    setEnabled(enabled: boolean): Effect<AutoZoneState, never>;
    setMap(map: 'ledgermayne' | 'moreskulls' | 'ultradage' | 'darkcarnax' | 'astralshrine' | 'queeniona' | 'magnumopus' | undefined): Effect<AutoZoneState, never>;
}
interface ScriptHouseApi {
    get(selector: ItemQuery): Effect<Item | null, never>;
    getAll(): Effect<readonly Item[], never>;
    getAvailableSlots(): Effect<number, never>;
    getSlots(): Effect<number, never>;
    getUsedSlots(): Effect<number, never>;
}
interface ScriptInventoryApi {
    contains(selector: ItemQuery, quantity?: number): Effect<boolean, never>;
    equip(selector: ItemQuery): Effect<boolean, never>;
    get(selector: ItemQuery): Effect<Item | null, never>;
    getAll(): Effect<readonly Item[], never>;
    getAvailableSlots(): Effect<number, never>;
    getSlots(): Effect<number, never>;
    getUsedSlots(): Effect<number, never>;
    unequipConsumable(selector: ItemQuery): Effect<boolean, never>;
}
interface ScriptMapApi {
    getCellPads(): Effect<readonly string[], never>;
    getCells(): Effect<readonly string[], never>;
    getId(): Effect<number, never>;
    getMapItem(itemId: number): Effect<void, never>;
    getName(): Effect<string, never>;
    getRoomNumber(): Effect<number, never>;
    isLoaded(): Effect<boolean, never>;
    loadSwf(swf: string): Effect<void, never>;
    reload(): Effect<void, never>;
    setSpawnPoint(cell?: string, pad?: string): Effect<void, never>;
}
interface ScriptMonstersApi {
    readonly auras: ScriptMonstersAurasApi;
    get(selector: MonsterQuery): Effect<Monster | null, never>;
    getAll(): Effect<readonly Monster[], never>;
    getAvailable(): Effect<readonly Monster[], never>;
    isAvailable(selector: MonsterQuery): Effect<boolean, never>;
}
interface ScriptMonstersAurasApi {
    get(monster: MonsterQuery, auraName: string, options?: AuraQueryOptions): Effect<Aura | null, never>;
    getAll(monster: MonsterQuery, options?: AuraQueryOptions): Effect<readonly Aura[], never>;
    has(monster: MonsterQuery, auraName: string, options?: AuraQueryOptions): Effect<boolean, never>;
}
interface ScriptPacketApi {
    on(selector: PacketSelector | undefined, handler: PacketHandler): Effect<() => void, never>;
    once(selector?: PacketSelector, options?: WaitOptions): Effect<FlashPacket | null, never>;
    sendClient(packet: string, type?: ClientPacketSendType): Effect<void, never>;
    sendServer(packet: string, type?: ServerPacketSendType): Effect<void, never>;
}
interface ScriptPlayerApi {
    readonly auras: ScriptPlayerAurasApi;
    readonly factions: ScriptPlayerFactionsApi;
    get(): Effect<Player | null, never>;
    getCell(): Effect<string, never>;
    getClassName(): Effect<string, never>;
    getGender(): Effect<string, never>;
    getGold(): Effect<number, never>;
    getHp(): Effect<number, never>;
    getLevel(): Effect<number, never>;
    getMaxHp(): Effect<number, never>;
    getMaxMp(): Effect<number, never>;
    getMp(): Effect<number, never>;
    getPad(): Effect<string, never>;
    getPosition(): Effect<Position, never>;
    getState(): Effect<EntityStateValue, never>;
    goToPlayer(name: string): Effect<void, never>;
    hasActiveBoost(boostType: string): Effect<boolean, never>;
    isAfk(): Effect<boolean, never>;
    isAlive(): Effect<boolean, never>;
    isMember(): Effect<boolean, never>;
    isReady(): Effect<boolean, never>;
    joinMap(map: string, cell?: string, pad?: string): Effect<boolean, never>;
    jumpToCell(cell: string, pad?: string, correction?: boolean): Effect<boolean, never>;
    readonly outfits: ScriptPlayerOutfitsApi;
    rest(full?: boolean): Effect<void, never>;
    useBoost(selector: ItemQuery): Effect<boolean, never>;
    walkTo(x: number, y: number, walkSpeed?: number): Effect<boolean, never>;
}
interface ScriptPlayerAurasApi {
    get(auraName: string, options?: AuraQueryOptions): Effect<Aura | null, never>;
    getAll(options?: AuraQueryOptions): Effect<readonly Aura[], never>;
    has(auraName: string, options?: AuraQueryOptions): Effect<boolean, never>;
}
interface ScriptPlayerFactionsApi {
    get(selector: string | number): Effect<Faction | null, never>;
    getAll(): Effect<readonly Faction[], never>;
}
interface ScriptPlayerOutfitsApi {
    equip(name: string, options?: OutfitOptions): Effect<boolean, never>;
    get(name: string): Effect<Outfit | null, never>;
    getAll(): Effect<readonly Outfit[], never>;
    wear(name: string, options?: OutfitOptions): Effect<boolean, never>;
}
interface ScriptPlayersApi {
    readonly auras: ScriptPlayersAurasApi;
    get(selector: string | number): Effect<Player | null, never>;
    getAll(): Effect<readonly Player[], never>;
    getMe(): Effect<Player | null, never>;
}
interface ScriptPlayersAurasApi {
    get(player: string | number, auraName: string, options?: AuraQueryOptions): Effect<Aura | null, never>;
    getAll(player: string | number, options?: AuraQueryOptions): Effect<readonly Aura[], never>;
    has(player: string | number, auraName: string, options?: AuraQueryOptions): Effect<boolean, never>;
}
interface ScriptQuestsApi {
    abandon(questId: number): Effect<boolean, never>;
    accept(questId: number): Effect<boolean, never>;
    acceptBatch(questIds: readonly number[]): Effect<readonly boolean[], never>;
    complete(questId: number, turnIns?: number, itemId?: number, special?: boolean): Effect<boolean, never>;
    get(questId: number): Effect<Quest | null, never>;
    getAccepted(): Effect<readonly Quest[], never>;
    getAll(): Effect<readonly Quest[], never>;
    getMaxTurnIns(questId: number): Effect<number, never>;
    isAvailable(questId: number): Effect<boolean, never>;
    isInProgress(questId: number): Effect<boolean, never>;
    load(questId: number): Effect<boolean, never>;
    loadBatch(questIds: readonly number[]): Effect<readonly boolean[], never>;
}
interface ScriptRuntimeInputsApi {
    get(key: string): Effect<ScriptInputValue | undefined, never>;
    getAll(): Effect<ScriptInputValues, never>;
}
interface ScriptRuntimeOptionsApi {
    getAll(): Effect<ScriptRuntimeOptions, never>;
    getSafeStartStop(): Effect<boolean, never>;
    getUsePrivateRooms(): Effect<boolean, never>;
    reset(): Effect<ScriptRuntimeOptions, never>;
    setSafeStartStop(enabled: boolean): Effect<ScriptRuntimeOptions, never>;
    setUsePrivateRooms(enabled: boolean): Effect<ScriptRuntimeOptions, never>;
}
interface ScriptSettingsApi {
    isAntiCounterEnabled(): Effect<boolean, never>;
    setAnimationsEnabled(enabled: boolean): Effect<void, never>;
    setAntiCounterEnabled(enabled: boolean): Effect<void, never>;
    setCollisionsEnabled(enabled: boolean): Effect<void, never>;
    setCustomGuild(name: string): Effect<void, never>;
    setCustomName(name: string): Effect<void, never>;
    setDeathAdsVisible(visible: boolean): Effect<void, never>;
    setEnemyMagnetEnabled(enabled: boolean): Effect<void, never>;
    setFrameRate(fps: number): Effect<void, never>;
    setInfiniteRangeEnabled(enabled: boolean): Effect<void, never>;
    setLagKillerEnabled(enabled: boolean): Effect<void, never>;
    setOtherPlayersVisible(visible: boolean): Effect<void, never>;
    setProvokeCellEnabled(enabled: boolean): Effect<void, never>;
    setSkipCutscenesEnabled(enabled: boolean): Effect<void, never>;
    setWalkSpeed(speed: number): Effect<void, never>;
}
interface ScriptShopsApi {
    buy(selector: ShopItemQuery, options?: QuantityOptions): Effect<boolean, never>;
    canBuy(selector: ShopItemQuery, options?: QuantityOptions): Effect<boolean, never>;
    close(shopId?: number): Effect<boolean, never>;
    get(selector: ShopItemQuery): Effect<Item | null, never>;
    getAll(): Effect<readonly Item[], never>;
    getInfo(): Effect<Shop | null, never>;
    getMaxBuyQuantity(selector: ShopItemQuery): Effect<number, never>;
    isMergeShop(): Effect<boolean, never>;
    isOpen(shopId?: number): Effect<boolean, never>;
    load(shopId: number): Effect<boolean, never>;
    loadArmorCustomize(): Effect<void, never>;
    loadHairShop(shopId: number): Effect<void, never>;
    sell(selector: ItemQuery, options?: QuantityOptions): Effect<boolean, never>;
}
interface ScriptTempInventoryApi {
    contains(selector: ItemQuery, quantity?: number): Effect<boolean, never>;
    get(selector: ItemQuery): Effect<Item | null, never>;
    getAll(): Effect<readonly Item[], never>;
}
interface ScriptWaitApi {
    forEvent(selector?: EventSelector, options?: WaitOptions): Effect<FlashEvent | null, never>;
    forGameAction(action: string, options?: WaitOptions | DurationInput): Effect<boolean, never>;
    forPacket(selector?: PacketSelector, options?: WaitOptions): Effect<FlashPacket | null, never>;
    isGameActionAvailable(action: string): Effect<boolean, never>;
    until(condition: Effect<boolean, never, never>, options?: WaitOptions): Effect<boolean, never>;
    untilSome<A>(condition: Effect<Option<A>, never, never>, options?: WaitOptions): Effect<A | null, never>;
}

interface ArmyEquipSetOptions {
  readonly resolveItems?: boolean;
}
interface ArmyError extends Error {
  _tag: unknown;
}
interface ArmyRunStepOptions {
  readonly timeoutMs?: number;
}
type ArmySession = ArmySessionPayload;
interface Aura {
  readonly category: string | undefined;
  readonly duration: number;
  readonly icon: string | undefined;
  readonly kind: AuraKind;
  readonly name: string;
  readonly stack: number;
  readonly value: number | undefined;
  toJSON(): AuraSnapshot;
}
interface AuraQueryOptions {
  readonly kind?: AuraKind;
}
interface AuthConnectOutcome {
  readonly message: string;
  readonly retryable: boolean;
  readonly serverName?: string;
  readonly status:
    | "blocked"
    | "connected"
    | "connection-error"
    | "connection-failed"
    | "full"
    | "not-found"
    | "not-ready"
    | "timeout";
}
interface AutoReloginLoginError {
  readonly message: string;
}
interface AutoReloginLoginRequest {
  readonly onLifecycle?: (
    event: AutoReloginLifecycleEvent,
  ) => Effect<void, unknown>;
  readonly password: string;
  readonly server?: string;
  readonly username: string;
}
type AutoReloginLoginResult =
  | { readonly status: "ready" }
  | { readonly status: "server-select" };
interface AutoReloginState {
  readonly attemptsRemaining?: number;
  readonly attempting: boolean;
  readonly captured: boolean;
  readonly delayMs: number;
  readonly enabled: boolean;
  readonly lastError?: string;
  readonly server?: string;
  readonly username?: string;
  readonly waitingDelay: boolean;
}
interface AutoZoneState {
  readonly enabled: boolean;
  readonly map: AutoZoneSupportedMap | undefined;
}
type AutoZoneSupportedMap = 'ledgermayne' | 'moreskulls' | 'ultradage' | 'darkcarnax' | 'astralshrine' | 'queeniona' | 'magnumopus';
type ClientPacketSendType = "str" | "json" | "xml";
interface CombatKillOptions {
  readonly findMost?: boolean;
  readonly killPriority?: readonly MonsterSelector[] | string;
  readonly maxKills?: number;
  readonly profile?: ScriptCombatProfileInput;
  readonly skillDelay?: number;
  readonly skillSet?: readonly Skill[] | string;
  readonly skillWait?: boolean;
  readonly timeout?: DurationInput;
}
interface EntityStateValue { readonly [key: string]: unknown; }
interface EventSelector {
  readonly kind?: FlashEventKind;
  readonly type?: FlashEventType;
}
interface Faction {
  readonly id: number;
  readonly name: string;
  readonly rank: number;
  readonly reputation: number;
  toJSON(): FactionSnapshot;
}
type FlashEvent =
  | FlashPacketEvent
  | FlashProjectionEvent
  | FlashRuntimeEvent;
type FlashEventHandler = (event: FlashEvent) => Effect<void>;
type FlashPacket = { readonly command: string; readonly direction: 'client'; readonly params: readonly string[]; readonly raw: string; readonly wireType: 'str' | 'json' | 'xml' | 'unknown'; } | { readonly command: string; readonly data: unknown; readonly direction: 'server'; readonly raw: string; readonly wireType: 'str' | 'json' | 'xml' | 'unknown'; } | { readonly command: string; readonly data: unknown; readonly direction: 'extension'; readonly raw: string; readonly wireType: 'str' | 'json' | 'xml' | 'unknown'; };
interface HuntOptions {
  readonly findMost?: boolean;
}
interface Item {
  readonly armor: boolean;
  readonly banked: boolean;
  readonly cape: boolean;
  readonly category: string;
  readonly charItemId: number | undefined;
  readonly classItem: boolean;
  readonly coins: boolean;
  readonly context: ItemContext;
  readonly cost: number;
  readonly description: string;
  readonly enhancement: Enhancement | undefined;
  readonly equipped: boolean;
  readonly equipmentSlot: string;
  readonly file: string;
  readonly helm: boolean;
  readonly houseItem: boolean;
  readonly itemId: number;
  readonly link: string;
  readonly meta: string;
  readonly name: string;
  readonly pet: boolean;
  readonly quantity: number;
  readonly shopItemId: number | undefined;
  readonly temporaryItem: boolean;
  readonly weapon: boolean;
  matches(selector: ItemQuery | ShopItemQuery): boolean;
  toJSON(): ItemSnapshot;
}
type ItemQuery = ItemSelector | number | string;
interface Monster extends Entity {
  readonly level: number;
  readonly monsterId: number;
  readonly monsterMapId: number;
  readonly name: string;
  readonly race: string;
  matches(selector: MonsterQuery): boolean;
}
type MonsterQuery = MonsterSelector | number | string;
interface Outfit {
  readonly colors: OutfitColors;
  readonly equipment: OutfitEquipment;
  readonly name: string;
  toJSON(): OutfitSnapshot;
}
interface OutfitOptions {
  readonly keepColors?: boolean;
}
type PacketHandler = (packet: FlashPacket) => Effect<void>;
interface PacketSelector {
  readonly command?: string;
  readonly direction?: FlashPacketDirection;
  readonly wireType?: FlashPacketWireType;
}
interface Player extends Entity {
  readonly afk: boolean;
  readonly entityId: number;
  readonly entityType: string;
  readonly level: number;
  readonly name: string;
  readonly pad: string;
  readonly position: Position;
  readonly username: string;
}
interface Position {
  readonly x: number;
  readonly y: number;
}
interface QuantityOptions {
  readonly quantity?: number;
}
interface Quest {
  readonly cadence: QuestCadence;
  readonly id: number;
  readonly name: string;
  readonly once: boolean;
  readonly requirements: readonly QuestItem[];
  readonly rewards: readonly QuestReward[];
  toJSON(): QuestSnapshot;
}
interface ScriptRuntimeOptions {
  readonly safeStartStop: boolean;
  readonly usePrivateRooms: boolean;
}
interface Server {
  readonly chat: number;
  readonly count: number;
  readonly full: boolean;
  readonly language: string;
  readonly max: number;
  readonly memberOnly: boolean;
  readonly name: string;
  readonly online: boolean;
  toJSON(): ServerSnapshot;
}
type ServerPacketSendType = "String" | "Json";
interface Shop {
  readonly house: boolean;
  readonly id: number;
  readonly items: readonly Item[];
  readonly limited: boolean;
  readonly merge: boolean;
  readonly name: string;
  toJSON(): ShopSnapshot;
}
type ShopItemQuery = ShopItemSelector | number | string;
interface SkillUseOptions {
  readonly force?: boolean;
  readonly wait?: boolean;
}
type StateDisposer = () => void;
interface StateSubscriptionOptions {
  readonly emitCurrent?: boolean;
}
type TargetInfo = MonsterTargetInfo | PlayerTargetInfo;
interface WaitOptions {
  readonly interval?: DurationInput;
  readonly timeout?: DurationInput;
}
interface _tag { readonly [key: string]: unknown; }
interface ArmySessionPayload extends ArmyConfigPayload {
  readonly playerName: string;
  readonly playerNumber: number;
  readonly role: "leader" | "member";
  readonly sessionId: string;
}
type AuraKind = "active" | "passive";
type AuraSnapshot = Readonly<AuraData>;
interface AutoReloginLifecycleEvent {
  readonly attemptsRemaining: number;
  readonly message?: string;
  readonly step: AutoReloginLifecycleStep;
}
type MonsterSelector = MonsterQuery;
type ScriptCombatProfileInput =
  | CombatProfile
  | CombatProfileDefinition
  | string;
type FlashEventKind = "packet" | "projection" | "runtime";
type FlashEventType = FlashEvent["type"];
type FactionSnapshot = Readonly<FactionData>;
type FlashPacketEvent =
  | {
      readonly kind: "packet";
      readonly payload: FlashPacket;
      readonly type: "packetReceived";
    }
  | {
      readonly kind: "packet";
      readonly payload: {
        readonly direction: FlashPacketDirection;
        readonly raw: string;
      };
      readonly type: "packetParseFailed";
    };
type FlashProjectionEvent =
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: UnknownRecord;
      readonly type: "questComplete";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: MapInfo;
      readonly type: "joinMap";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: {
        readonly map: string;
        readonly zone: string;
      };
      readonly type: "zone";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: {
        readonly afk: boolean;
        readonly entityId?: number;
        readonly isSelf: boolean;
        readonly username: string;
      };
      readonly type: "playerAfk";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: {
        readonly cell?: string;
        readonly entityId?: number;
        readonly isSelf: boolean;
        readonly pad?: string;
        readonly position?: Position;
        readonly username: string;
      };
      readonly type: "playerLocation";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: { readonly monsterMapId: number };
      readonly type: "monsterDeath";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: {
        readonly aura: Aura;
        readonly auraKind: AuraKind;
        readonly targetId: number;
        readonly targetType: "monster" | "player";
      };
      readonly type: "auraAdded";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: {
        readonly auraName: string;
        readonly auraKind: AuraKind;
        readonly remainingStack: number;
        readonly targetId: number;
        readonly targetType: "monster" | "player";
      };
      readonly type: "auraRemoved";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: {
        readonly cell: string;
        readonly entityId: number;
        readonly hp: number;
        readonly isSelf: boolean;
        readonly pad: string;
        readonly state: EntityState;
        readonly username: string;
      };
      readonly type: "playerDeath";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: {
        readonly auraName?: string;
        readonly auraPhase?: "off" | "on";
        readonly message: string;
        readonly monMapId?: number;
        readonly source: "animation" | "aura";
        readonly sourceMonMapId?: number;
        readonly targetId?: number;
        readonly targetMonMapId?: number;
        readonly targetName?: string;
        readonly targetType?: "monster" | "player";
      };
      readonly type: "updateMessage";
    };
type FlashRuntimeEvent =
  | {
      readonly kind: "runtime";
      readonly payload: { readonly status: string };
      readonly type: "connection";
    }
  | {
      readonly kind: "runtime";
      readonly payload: { readonly message: string };
      readonly type: "debug";
    }
  | {
      readonly kind: "runtime";
      readonly type: "loaded";
    }
  | {
      readonly kind: "runtime";
      readonly payload: { readonly percent: number };
      readonly type: "progress";
    };
type ItemContext =
  | "bank"
  | "drop"
  | "house"
  | "inventory"
  | "shop"
  | "temporary";
interface Enhancement {
  readonly dps?: number;
  readonly id?: number;
  readonly level?: number;
  readonly patternId?: number;
  readonly range?: number;
  readonly rarity?: number;
}
type ItemSnapshot = Readonly<ItemData> & {
  readonly armor: boolean;
  readonly banked: boolean;
  readonly cape: boolean;
  readonly classItem: boolean;
  readonly helm: boolean;
  readonly pet: boolean;
  readonly weapon: boolean;
};
type ItemSelector = ItemQuery;
interface Entity {
  readonly alive: boolean;
  readonly cell: string;
  readonly dead: boolean;
  readonly hp: number;
  readonly hpPercent: number;
  readonly idle: boolean;
  readonly inCombat: boolean;
  readonly maxHp: number;
  readonly maxMp: number;
  readonly mp: number;
  readonly mpPercent: number;
  readonly state: EntityState;
  isInCell(cell: string): boolean;
  toJSON(): EntitySnapshot;
}
interface OutfitColors {
  readonly accessory: number | undefined;
  readonly base: number | undefined;
  readonly eye: number | undefined;
  readonly hair: number | undefined;
  readonly skin: number | undefined;
  readonly trim: number | undefined;
}
interface OutfitEquipment {
  readonly armorItemId: number | undefined;
  readonly capeItemId: number | undefined;
  readonly classItemId: number | undefined;
  readonly helmItemId: number | undefined;
  readonly itemId: number | undefined;
  readonly miscItemId: number | undefined;
  readonly petItemId: number | undefined;
  readonly weaponItemId: number | undefined;
}
type OutfitSnapshot = Readonly<OutfitData>;
type FlashPacketDirection = 'client' | 'server' | 'extension';
type FlashPacketWireType = 'str' | 'json' | 'xml' | 'unknown';
type QuestCadence = "daily" | "monthly" | "none" | "weekly";
interface QuestItem {
  readonly itemId: number;
  readonly name: string;
  readonly quantity: number;
}
interface QuestReward extends QuestItem {
  readonly dropChance?: number;
}
type QuestSnapshot = Readonly<QuestData>;
type ServerSnapshot = Readonly<ServerData> & {
  readonly full: boolean;
};
interface Json { readonly [key: string]: unknown; }
type ShopSnapshot = Readonly<Omit<ShopData, "items">> & {
  readonly items: readonly ItemSnapshot[];
};
type ShopItemSelector = ShopItemQuery;
type MonsterTargetInfo = TargetBaseInfo & {
  type: "monster";
  monsterId: number;
  monsterMapId: number;
  level: number;
  race: string;
  name: string;
};
type PlayerTargetInfo = TargetBaseInfo & {
  type: "player";
  afk: boolean;
  entityId: number;
  entityType: string;
  level: number;
  mp: number;
  maxMp: number;
  sp: number;
  pad: string;
  username: string;
  name: string;
};
interface ArmyConfigPayload extends ArmyConfigCore {
  readonly configName: string;
  readonly raw: ArmyConfigRaw;
}
interface AuraData {
  category?: string;
  duration: number;
  icon?: string;
  kind: AuraKind;
  name: string;
  stack: number;
  value?: number;
}
type AutoReloginLifecycleStep = "connect" | "login" | "ready";
type CombatProfile = { readonly id: string; readonly label: string; readonly role: string; readonly delayMs: number; readonly cooldownMode: 'use-if-ready' | 'wait-for-cooldown'; readonly steps: readonly { readonly id: string; readonly skill: number; readonly conditions: readonly ({ readonly type: 'self-hp' | 'self-mp' | 'ally-hp'; readonly op: '<=' | '>='; readonly value: number; readonly unit: 'value' | 'percent'; } | { readonly type: 'self-aura' | 'target-aura'; readonly auraName: string; readonly op: '<=' | '>='; readonly value: number; })[]; readonly cooldownMode?: 'use-if-ready' | 'wait-for-cooldown'; readonly waitMs?: number; }[]; readonly className?: string; readonly resetSkillIndexOnMonsterDeath?: boolean; readonly messageTriggers?: readonly { readonly id: string; readonly messageIncludes: string; readonly skill: number; readonly source: 'any' | 'animation' | 'aura'; readonly cooldownMs?: number; }[]; };
interface CombatProfileDefinition extends Partial<Omit<CombatProfile, "steps" | "messageTriggers">> {
  readonly steps: readonly CombatProfileStepDefinition[];
  readonly messageTriggers?: readonly CombatProfileMessageTriggerDefinition[];
}
interface FactionData {
  id: number;
  name: string;
  rank: number;
  reputation: number;
}
type UnknownRecord = Record<string, unknown>;
interface MapInfo {
  readonly id: number;
  readonly name: string;
  readonly roomNumber: number;
}
type EntityState = EntityState;
interface ItemData {
  category: string;
  charItemId?: number;
  coins: boolean;
  context: ItemContext;
  cost: number;
  description: string;
  enhancement?: Enhancement;
  equipped: boolean;
  equipmentSlot: string;
  file: string;
  houseItem: boolean;
  itemId: number;
  link: string;
  meta: string;
  name: string;
  quantity: number;
  shopItemId?: number;
  temporaryItem: boolean;
}
type EntitySnapshot = Readonly<EntityData> & {
  readonly alive: boolean;
  readonly dead: boolean;
  readonly hpPercent: number;
  readonly idle: boolean;
  readonly inCombat: boolean;
  readonly mpPercent: number;
};
interface OutfitData {
  colors: OutfitColors;
  equipment: OutfitEquipment;
  name: string;
}
interface QuestData {
  cadence: QuestCadence;
  id: number;
  name: string;
  once: boolean;
  requirements: readonly QuestItem[];
  rewards: readonly QuestReward[];
}
interface ServerData {
  chat: number;
  count: number;
  language: string;
  max: number;
  memberOnly: boolean;
  name: string;
  online: boolean;
}
interface ShopData {
  house: boolean;
  id: number;
  items: readonly Item[];
  limited: boolean;
  merge: boolean;
  name: string;
}
type TargetBaseInfo = {
  type: "monster" | "player";
  hp: number;
  maxHp: number;
  state: EntityState;
  cell: string;
};
interface ArmyConfigCore {
  readonly items: Readonly<Record<string, string>>;
  readonly players: readonly string[];
  readonly room: string;
  readonly sets: Readonly<Record<string, ArmySetConfig>>;
}
type ArmyConfigRaw = Record<string, unknown>;
type CombatProfileStepDefinition = Partial<CombatProfileStep> & {
  readonly skill: number;
};
type CombatProfileMessageTriggerDefinition = Partial<CombatProfileMessageTrigger> & {
  readonly messageIncludes: string;
  readonly skill: number;
};
interface EntityData {
  cell: string;
  hp: number;
  maxHp: number;
  maxMp: number;
  mp: number;
  state: EntityState;
}
interface ArmySetConfig {
  readonly default?: ArmyEquipSet;
  readonly players: Readonly<Record<string, ArmyEquipSet>>;
}
type CombatProfileStep = { readonly id: string; readonly skill: number; readonly conditions: readonly ({ readonly type: 'self-hp' | 'self-mp' | 'ally-hp'; readonly op: '<=' | '>='; readonly value: number; readonly unit: 'value' | 'percent'; } | { readonly type: 'self-aura' | 'target-aura'; readonly auraName: string; readonly op: '<=' | '>='; readonly value: number; })[]; readonly cooldownMode?: 'use-if-ready' | 'wait-for-cooldown'; readonly waitMs?: number; };
type CombatProfileMessageTrigger = { readonly id: string; readonly messageIncludes: string; readonly skill: number; readonly source: 'any' | 'animation' | 'aura'; readonly cooldownMs?: number; };
interface ArmyEquipSet {
  readonly armor?: string;
  readonly cape?: string;
  readonly class?: string;
  readonly helm?: string;
  readonly pet?: string;
  readonly pots?: readonly string[];
  readonly safeClass?: string;
  readonly safePot?: string;
  readonly scroll?: string;
  readonly weapon?: string;
}
