// Generated by pnpm run types:scripting. Do not edit directly.

/* eslint-disable */

type ScriptPipe = {
  <A>(value: A): A;
  <A, B>(value: A, ab: (a: A) => B): B;
  <A, B, C>(value: A, ab: (a: A) => B, bc: (b: B) => C): C;
  <A, B, C, D>(
    value: A,
    ab: (a: A) => B,
    bc: (b: B) => C,
    cd: (c: C) => D,
  ): D;
};

interface ScriptEffectModule {
  readonly [key: string]: any;
}

interface ScriptOptionModule {
  some<Value>(value: Value): Option<Value>;
  none<Value = never>(): Option<Value>;
  isSome<Value>(
    option: Option<Value>,
  ): option is { readonly _tag: "Some"; readonly value: Value };
  isNone<Value>(option: Option<Value>): option is { readonly _tag: "None" };
  readonly [key: string]: any;
}

interface ScriptOpaqueModule {
  readonly [key: string]: any;
}

interface ScriptEffectStd {
  readonly Effect: ScriptEffectModule;
  readonly Option: ScriptOptionModule;
  readonly Duration: ScriptOpaqueModule;
  readonly pipe: ScriptPipe;
}

declare module "effect" {
  const effect: ScriptEffectStd;
  export = effect;
}

declare module "lucent" {
  const lucent: ScriptLucentStd;
  namespace lucent {
    export type ScriptInputValue = LucentScriptInputValue;
    export type ScriptInputType = LucentScriptInputType;
    export type ScriptInputField = LucentScriptInputField;
    export type ScriptInputsDefinition = LucentScriptInputsDefinition;
    export type ScriptInputValues = LucentScriptInputValues;
    export type ScriptModuleExports = LucentScriptModuleExports;
  }
  export = lucent;
}

type DurationInput = number | string | bigint | DurationLike;

interface DurationLike {
  readonly _tag?: string;
}

type Option<Value> =
  | { readonly _tag: "Some"; readonly value: Value }
  | { readonly _tag: "None" };

type EffectYieldable<
  Value = unknown,
  Error = unknown,
  Requirements = never,
  Next = never,
> = unknown;

interface Effect<
  Value = unknown,
  Error = unknown,
  Requirements = never,
> {
  [Symbol.iterator](): Generator<EffectYieldable<Value, Error>, Value, any>;
}

interface ScriptExecutionError extends Error {
  readonly _tag: "ScriptExecutionError";
}

interface ScriptNotReadyError extends Error {
  readonly _tag: "ScriptNotReadyError";
}

interface ScriptStopSignal extends Error {
  readonly _tag: "ScriptStopSignal";
}

type Skill = number | string;

type LucentScriptInputValue = string | number | boolean;
type LucentScriptInputType = "string" | "number" | "boolean" | "select";

interface LucentScriptInputFieldBase<
  Type extends LucentScriptInputType,
  Value extends LucentScriptInputValue,
> {
  /** Stable key used by script.inputs.get(key). */
  readonly key: string;
  readonly type: Type;
  readonly label: string;
  readonly description?: string;
  readonly required?: boolean;
  readonly default?: Value;
}

interface LucentScriptStringInputField
  extends LucentScriptInputFieldBase<"string", string> {}

interface LucentScriptNumberInputField
  extends LucentScriptInputFieldBase<"number", number> {}

interface LucentScriptBooleanInputField
  extends LucentScriptInputFieldBase<"boolean", boolean> {}

interface LucentScriptSelectInputField
  extends LucentScriptInputFieldBase<"select", string> {
  readonly options: readonly string[];
}

type LucentScriptInputField =
  | LucentScriptStringInputField
  | LucentScriptNumberInputField
  | LucentScriptBooleanInputField
  | LucentScriptSelectInputField;

interface LucentScriptInputsDefinition {
  /** Stable id used to persist values for this script. */
  readonly id: string;
  readonly fields: readonly LucentScriptInputField[];
}

type LucentScriptInputValues = Readonly<Record<string, LucentScriptInputValue>>;

interface LucentScriptModuleExports extends ScriptMain {
  inputs?: LucentScriptInputsDefinition;
}

type ScriptInputValue = LucentScriptInputValue;
type ScriptInputType = LucentScriptInputType;
type ScriptInputField = LucentScriptInputField;
interface ScriptInputsDefinition extends LucentScriptInputsDefinition {}
type ScriptInputValues = LucentScriptInputValues;
type ScriptModuleExports = LucentScriptModuleExports;

type ScriptMain = () => Generator<Effect<any, any, never>, unknown, any>;

interface ScriptContext {
    readonly api: ScriptApi;
    readonly features: ScriptFeaturesApi;
    readonly script: ScriptRuntimeApi;
}
interface ScriptLucentStd {
    readonly api: ScriptApi;
    readonly features: ScriptFeaturesApi;
    readonly script: ScriptRuntimeApi;
}
interface ScriptApi {
    readonly auth: ScriptAuthApi;
    readonly bank: ScriptBankApi;
    readonly combat: ScriptCombatApi;
    readonly drops: ScriptDropsApi;
    readonly events: ScriptEventsApi;
    readonly house: ScriptHouseApi;
    readonly inventory: ScriptInventoryApi;
    readonly map: ScriptMapApi;
    readonly monsters: ScriptMonstersApi;
    readonly packet: ScriptPacketApi;
    readonly player: ScriptPlayerApi;
    readonly players: ScriptPlayersApi;
    readonly quests: ScriptQuestsApi;
    readonly settings: ScriptSettingsApi;
    readonly shops: ScriptShopsApi;
    readonly tempInventory: ScriptTempInventoryApi;
    readonly wait: ScriptWaitApi;
}
interface ScriptRuntimeApi {
    readonly signal: AbortSignal;
    readonly inputs: ScriptRuntimeInputsApi;
    readonly options: ScriptRuntimeOptionsApi;
    exit(options?: { readonly closeWindow?: boolean; readonly logout?: boolean; }): Effect<never, ScriptStopSignal>;
    log(message: unknown): Effect<void, never>;
    sleep(ms: number): Effect<void, ScriptExecutionError>;
    stop(reason?: string): Effect<never, ScriptStopSignal>;
}
interface ScriptAuthApi {
    connectTo(server: string): Effect<AuthConnectOutcome, never>;
    getPassword(): Effect<string, never>;
    getServers(): Effect<readonly ServerRecord[], never>;
    getUsername(): Effect<string, never>;
    isLoggedIn(): Effect<boolean, never>;
    isServerSelectReady(): Effect<boolean, never>;
    isTemporarilyKicked(): Effect<boolean, never>;
    login(username: string, password: string): Effect<boolean, never>;
    logout(): Effect<void, never>;
}
interface ScriptBankApi {
    contains(selector: ItemSelector, quantity?: number): Effect<boolean, never>;
    deposit(selector: ItemSelector): Effect<boolean, never>;
    depositBatch(selectors: readonly ItemSelector[]): Effect<readonly boolean[], never>;
    get(selector: ItemSelector): Effect<ItemRecord | null, never>;
    getAll(): Effect<readonly ItemRecord[], never>;
    getAvailableSlots(): Effect<number, never>;
    getSlots(): Effect<number, never>;
    getUsedSlots(): Effect<number, never>;
    isOpen(): Effect<boolean, never>;
    open(force?: boolean): Effect<void, never>;
    swap(inventorySelector: ItemSelector, bankSelector: ItemSelector): Effect<boolean, never>;
    withdraw(selector: ItemSelector): Effect<boolean, never>;
    withdrawBatch(selectors: readonly ItemSelector[]): Effect<readonly boolean[], never>;
}
interface ScriptCombatApi {
    attackMonster(selector: MonsterSelector): Effect<boolean, never>;
    cancelAutoAttack(): Effect<void, never>;
    cancelTarget(): Effect<void, never>;
    canUseSkill(index: number): Effect<boolean, never>;
    exit(): Effect<boolean, never>;
    getConsumableSkillItem(): Effect<{ readonly itemId: number; } | null, never>;
    hunt(selector: MonsterSelector, options?: HuntOptions): Effect<MonsterRecord | null, never>;
    kill(selector: MonsterSelector, options?: CombatKillOptions): Effect<boolean, never>;
    killForItem(monster: MonsterSelector, item: ItemSelector, quantity?: number, options?: CombatKillOptions): Effect<boolean, never>;
    killForTempItem(monster: MonsterSelector, item: ItemSelector, quantity?: number, options?: CombatKillOptions): Effect<boolean, never>;
    readonly target: ScriptCombatTargetApi;
    useSkill(index: number, options?: SkillUseOptions): Effect<boolean, never>;
}
interface ScriptCombatTargetApi {
    readonly auras: ScriptCombatTargetAurasApi;
    get(): Effect<TargetInfo | null, never>;
}
interface ScriptCombatTargetAurasApi {
    get(auraName: string): Effect<AuraRecord | null, never>;
    getAll(): Effect<readonly AuraRecord[], never>;
    has(auraName: string): Effect<boolean, never>;
}
interface ScriptDropsApi {
    accept(selector: ItemSelector): Effect<boolean, never>;
    contains(selector: ItemSelector): Effect<boolean, never>;
    getAll(): Effect<readonly DropRecord[], never>;
    isCustomUiEnabled(): Effect<boolean, never>;
    reject(selector: ItemSelector): Effect<boolean, never>;
    toggleUi(): Effect<void, never>;
}
interface ScriptEventsApi {
    on(selector: EventSelector | undefined, handler: FlashEventHandler): Effect<() => void, never>;
    once(selector?: EventSelector, options?: WaitOptions): Effect<FlashEvent | null, never>;
}
interface ScriptFeaturesAntiCounterApi {
    isEnabled(): Effect<boolean, never>;
    setEnabled(enabled: boolean): Effect<void, never>;
}
interface ScriptFeaturesApi {
    readonly antiCounter: ScriptFeaturesAntiCounterApi;
    readonly autoRelogin: ScriptFeaturesAutoReloginApi;
    readonly autoZone: ScriptFeaturesAutoZoneApi;
}
interface ScriptFeaturesAutoReloginApi {
    disable(): Effect<AutoReloginState, never>;
    enable(): Effect<AutoReloginState, never>;
    getDelay(): Effect<number, never>;
    getServer(): Effect<string | undefined, never>;
    getState(): Effect<AutoReloginState, never>;
    isEnabled(): Effect<boolean, never>;
    onState(listener: (state: AutoReloginState) => void, options?: StateSubscriptionOptions): Effect<StateDisposer, never>;
    setDelay(delayMs: number): Effect<AutoReloginState, never>;
    setEnabled(enabled: boolean): Effect<AutoReloginState, never>;
    setServer(serverName: string): Effect<AutoReloginState, never>;
}
interface ScriptFeaturesAutoZoneApi {
    getMap(): Effect<AutoZoneSupportedMap | undefined, never>;
    getState(): Effect<AutoZoneState, never>;
    isEnabled(): Effect<boolean, never>;
    onState(listener: (state: AutoZoneState) => void, options?: StateSubscriptionOptions): Effect<StateDisposer, never>;
    setEnabled(enabled: boolean): Effect<AutoZoneState, never>;
    setMap(map: 'ledgermayne' | 'moreskulls' | 'ultradage' | 'darkcarnax' | 'astralshrine' | 'queeniona' | 'magnumopus' | undefined): Effect<AutoZoneState, never>;
}
interface ScriptHouseApi {
    get(selector: ItemSelector): Effect<ItemRecord | null, never>;
    getAll(): Effect<readonly ItemRecord[], never>;
    getAvailableSlots(): Effect<number, never>;
    getSlots(): Effect<number, never>;
    getUsedSlots(): Effect<number, never>;
}
interface ScriptInventoryApi {
    contains(selector: ItemSelector, quantity?: number): Effect<boolean, never>;
    equip(selector: ItemSelector): Effect<boolean, never>;
    get(selector: ItemSelector): Effect<ItemRecord | null, never>;
    getAll(): Effect<readonly ItemRecord[], never>;
    getAvailableSlots(): Effect<number, never>;
    getSlots(): Effect<number, never>;
    getUsedSlots(): Effect<number, never>;
    unequipConsumable(selector: ItemSelector): Effect<boolean, never>;
}
interface ScriptMapApi {
    getCellPads(): Effect<readonly string[], never>;
    getCells(): Effect<readonly string[], never>;
    getId(): Effect<number, never>;
    getMapItem(itemId: number): Effect<void, never>;
    getName(): Effect<string, never>;
    getRoomNumber(): Effect<number, never>;
    isLoaded(): Effect<boolean, never>;
    loadSwf(swf: string): Effect<void, never>;
    reload(): Effect<void, never>;
    setSpawnPoint(cell?: string, pad?: string): Effect<void, never>;
}
interface ScriptMonstersApi {
    readonly auras: ScriptMonstersAurasApi;
    get(selector: MonsterSelector): Effect<MonsterRecord | null, never>;
    getAll(): Effect<readonly MonsterRecord[], never>;
    getAvailable(): Effect<readonly MonsterRecord[], never>;
    isAvailable(selector: MonsterSelector): Effect<boolean, never>;
}
interface ScriptMonstersAurasApi {
    get(monster: MonsterSelector, auraName: string): Effect<AuraRecord | null, never>;
    getAll(monster: MonsterSelector): Effect<readonly AuraRecord[], never>;
    has(monster: MonsterSelector, auraName: string): Effect<boolean, never>;
}
interface ScriptPacketApi {
    on(selector: PacketSelector | undefined, handler: PacketHandler): Effect<() => void, never>;
    once(selector?: PacketSelector, options?: WaitOptions): Effect<FlashPacket | null, never>;
    sendClient(packet: string, type?: ClientPacketSendType): Effect<void, never>;
    sendServer(packet: string, type?: ServerPacketSendType): Effect<void, never>;
}
interface ScriptPlayerApi {
    readonly auras: ScriptPlayerAurasApi;
    readonly factions: ScriptPlayerFactionsApi;
    getCell(): Effect<string, never>;
    getClassName(): Effect<string, never>;
    getGender(): Effect<string, never>;
    getGold(): Effect<number, never>;
    getHp(): Effect<number, never>;
    getLevel(): Effect<number, never>;
    getMaxHp(): Effect<number, never>;
    getMaxMp(): Effect<number, never>;
    getMp(): Effect<number, never>;
    getPad(): Effect<string, never>;
    getPosition(): Effect<Position, never>;
    getState(): Effect<number, never>;
    goToPlayer(name: string): Effect<void, never>;
    hasActiveBoost(boostType: string): Effect<boolean, never>;
    isAfk(): Effect<boolean, never>;
    isAlive(): Effect<boolean, never>;
    isMember(): Effect<boolean, never>;
    isReady(): Effect<boolean, never>;
    joinMap(map: string, cell?: string, pad?: string): Effect<boolean, never>;
    jumpToCell(cell: string, pad?: string, correction?: boolean): Effect<void, never>;
    readonly outfits: ScriptPlayerOutfitsApi;
    rest(full?: boolean): Effect<void, never>;
    useBoost(selector: ItemSelector): Effect<boolean, never>;
    walkTo(x: number, y: number, walkSpeed?: number): Effect<boolean, never>;
}
interface ScriptPlayerAurasApi {
    get(auraName: string): Effect<AuraRecord | null, never>;
    getAll(): Effect<readonly AuraRecord[], never>;
    has(auraName: string): Effect<boolean, never>;
}
interface ScriptPlayerFactionsApi {
    get(selector: string | number): Effect<FactionRecord | null, never>;
    getAll(): Effect<readonly FactionRecord[], never>;
}
interface ScriptPlayerOutfitsApi {
    equip(name: string, options?: OutfitOptions): Effect<boolean, never>;
    get(name: string): Effect<OutfitRecord | null, never>;
    getAll(): Effect<readonly OutfitRecord[], never>;
    wear(name: string, options?: OutfitOptions): Effect<boolean, never>;
}
interface ScriptPlayersApi {
    readonly auras: ScriptPlayersAurasApi;
    get(selector: string | number): Effect<PlayerRecord | null, never>;
    getAll(): Effect<readonly PlayerRecord[], never>;
    getMe(): Effect<PlayerRecord | null, never>;
}
interface ScriptPlayersAurasApi {
    get(player: string | number, auraName: string): Effect<AuraRecord | null, never>;
    has(player: string | number, auraName: string): Effect<boolean, never>;
}
interface ScriptQuestsApi {
    abandon(questId: number): Effect<void, never>;
    accept(questId: number): Effect<boolean, never>;
    acceptBatch(questIds: readonly number[]): Effect<readonly boolean[], never>;
    complete(questId: number, turnIns?: number, itemId?: number, special?: boolean): Effect<boolean, never>;
    get(questId: number): Effect<QuestRecord | null, never>;
    getAccepted(): Effect<readonly QuestRecord[], never>;
    getAll(): Effect<readonly QuestRecord[], never>;
    getMaxTurnIns(questId: number): Effect<number, never>;
    isAvailable(questId: number): Effect<boolean, never>;
    isInProgress(questId: number): Effect<boolean, never>;
    load(questId: number): Effect<boolean, never>;
    loadBatch(questIds: readonly number[]): Effect<readonly boolean[], never>;
}
interface ScriptRuntimeInputsApi {
    get(key: string): Effect<ScriptInputValue | undefined, never>;
    getAll(): Effect<ScriptInputValues, never>;
}
interface ScriptRuntimeOptionsApi {
    getAll(): Effect<ScriptRuntimeOptions, never>;
    getSafeStartStop(): Effect<boolean, never>;
    getUsePrivateRooms(): Effect<boolean, never>;
    reset(): Effect<ScriptRuntimeOptions, never>;
    setSafeStartStop(enabled: boolean): Effect<ScriptRuntimeOptions, never>;
    setUsePrivateRooms(enabled: boolean): Effect<ScriptRuntimeOptions, never>;
}
interface ScriptSettingsApi {
    isAntiCounterEnabled(): Effect<boolean, never>;
    setAnimationsEnabled(enabled: boolean): Effect<void, never>;
    setAntiCounterEnabled(enabled: boolean): Effect<void, never>;
    setCollisionsEnabled(enabled: boolean): Effect<void, never>;
    setCustomGuild(name: string): Effect<void, never>;
    setCustomName(name: string): Effect<void, never>;
    setDeathAdsVisible(visible: boolean): Effect<void, never>;
    setEnemyMagnetEnabled(enabled: boolean): Effect<void, never>;
    setFrameRate(fps: number): Effect<void, never>;
    setInfiniteRangeEnabled(enabled: boolean): Effect<void, never>;
    setLagKillerEnabled(enabled: boolean): Effect<void, never>;
    setOtherPlayersVisible(visible: boolean): Effect<void, never>;
    setProvokeCellEnabled(enabled: boolean): Effect<void, never>;
    setSkipCutscenesEnabled(enabled: boolean): Effect<void, never>;
    setWalkSpeed(speed: number): Effect<void, never>;
}
interface ScriptShopsApi {
    buy(selector: ShopItemSelector, options?: QuantityOptions): Effect<boolean, never>;
    canBuy(selector: ShopItemSelector, options?: QuantityOptions): Effect<boolean, never>;
    close(shopId?: number): Effect<boolean, never>;
    get(selector: ShopItemSelector): Effect<ShopItemRecord | null, never>;
    getAll(): Effect<readonly ShopItemRecord[], never>;
    getInfo(): Effect<ShopInfoRecord | null, never>;
    getMaxBuyQuantity(selector: ShopItemSelector): Effect<number, never>;
    isMergeShop(): Effect<boolean, never>;
    isOpen(shopId?: number): Effect<boolean, never>;
    load(shopId: number): Effect<boolean, never>;
    loadArmorCustomize(): Effect<void, never>;
    loadHairShop(shopId: number): Effect<void, never>;
    sell(selector: ItemSelector, options?: QuantityOptions): Effect<boolean, never>;
}
interface ScriptTempInventoryApi {
    contains(selector: ItemSelector, quantity?: number): Effect<boolean, never>;
    get(selector: ItemSelector): Effect<ItemRecord | null, never>;
    getAll(): Effect<readonly ItemRecord[], never>;
}
interface ScriptWaitApi {
    forEvent(selector?: EventSelector, options?: WaitOptions): Effect<FlashEvent | null, never>;
    forGameAction(action: string, options?: WaitOptions | DurationInput): Effect<boolean, never>;
    forPacket(selector?: PacketSelector, options?: WaitOptions): Effect<FlashPacket | null, never>;
    isGameActionAvailable(action: string): Effect<boolean, never>;
    until(condition: Effect<boolean, never, never>, options?: WaitOptions): Effect<boolean, never>;
    untilSome<A>(condition: Effect<Option<A>, never, never>, options?: WaitOptions): Effect<A | null, never>;
}

interface AuraRecord {
  readonly category?: string;
  readonly duration: number;
  readonly icon?: string;
  readonly name: string;
  readonly stack: number;
  readonly value?: number;
}
interface AuthConnectOutcome {
  readonly message: string;
  readonly retryable: boolean;
  readonly serverName?: string;
  readonly status:
    | "blocked"
    | "connected"
    | "connection-error"
    | "connection-failed"
    | "full"
    | "not-found"
    | "not-ready"
    | "timeout";
}
interface AutoReloginState {
  readonly attemptsRemaining?: number;
  readonly attempting: boolean;
  readonly captured: boolean;
  readonly delayMs: number;
  readonly enabled: boolean;
  readonly lastError?: string;
  readonly server?: string;
  readonly username?: string;
  readonly waitingDelay: boolean;
}
interface AutoZoneState {
  readonly enabled: boolean;
  readonly map: AutoZoneSupportedMap | undefined;
}
type AutoZoneSupportedMap = 'ledgermayne' | 'moreskulls' | 'ultradage' | 'darkcarnax' | 'astralshrine' | 'queeniona' | 'magnumopus';
type ClientPacketSendType = "str" | "json" | "xml";
interface CombatKillOptions {
  readonly findMost?: boolean;
  readonly killPriority?: readonly MonsterSelector[] | string;
  readonly maxKills?: number;
  readonly profile?: unknown;
  readonly skillDelay?: number;
  readonly skillSet?: readonly Skill[];
  readonly skillWait?: boolean;
  readonly timeout?: DurationInput;
}
interface DropRecord extends ItemRecord {
  readonly dropId: number;
  readonly dropQuantity: number;
}
interface EventSelector {
  readonly kind?: FlashEventKind;
  readonly type?: FlashEventType;
}
interface FactionRecord {
  readonly id: number;
  readonly name: string;
  readonly rank: number;
  readonly reputation: number;
}
type FlashEvent =
  | FlashPacketEvent
  | FlashProjectionEvent
  | FlashRuntimeEvent;
type FlashEventHandler = (event: FlashEvent) => Effect<void>;
type FlashPacket = { readonly command: string; readonly direction: 'client'; readonly params: readonly string[]; readonly raw: string; readonly wireType: 'str' | 'json' | 'xml' | 'unknown'; } | { readonly command: string; readonly data: unknown; readonly direction: 'server'; readonly raw: string; readonly wireType: 'str' | 'json' | 'xml' | 'unknown'; } | { readonly command: string; readonly data: unknown; readonly direction: 'extension'; readonly raw: string; readonly wireType: 'str' | 'json' | 'xml' | 'unknown'; };
interface HuntOptions {
  readonly findMost?: boolean;
}
interface ItemRecord {
  readonly banked: boolean;
  readonly category: string;
  readonly charItemId?: number;
  readonly coins: boolean;
  readonly cost: number;
  readonly description: string;
  readonly enhancement?: {
    readonly dps?: number;
    readonly id?: number;
    readonly level?: number;
    readonly patternId?: number;
    readonly range?: number;
    readonly rarity?: number;
  };
  readonly equipped: boolean;
  readonly equipmentSlot: string;
  readonly file: string;
  readonly house: boolean;
  readonly itemId: number;
  readonly link: string;
  readonly meta: string;
  readonly name: string;
  readonly quantity: number;
  readonly temp: boolean;
  readonly virtual: boolean;
}
type ItemSelector = ObjectSelector<InventoryItemSelectorShape> | number | string;
interface MonsterRecord {
  readonly cell: string;
  readonly hp: number;
  readonly level: number;
  readonly maxHp: number;
  readonly maxMp: number;
  readonly monsterId: number;
  readonly monsterMapId: number;
  readonly mp: number;
  readonly name: string;
  readonly race: string;
  readonly state: number;
}
type MonsterSelector = ObjectSelector<MonsterSelectorShape> | number | string;
interface OutfitOptions {
  readonly keepColors?: boolean;
}
interface OutfitRecord {
  readonly name: string;
  readonly raw: UnknownRecord;
}
type PacketHandler = (packet: FlashPacket) => Effect<void>;
interface PacketSelector {
  readonly command?: string;
  readonly direction?: FlashPacketDirection;
  readonly wireType?: FlashPacketWireType;
}
interface PlayerRecord {
  readonly afk: boolean;
  readonly cell: string;
  readonly entityId: number;
  readonly entityType: string;
  readonly hp: number;
  readonly level: number;
  readonly maxHp: number;
  readonly maxMp: number;
  readonly mp: number;
  readonly name: string;
  readonly pad: string;
  readonly position: readonly [number, number];
  readonly state: number;
  readonly username: string;
}
interface Position {
  readonly x: number;
  readonly y: number;
}
interface QuantityOptions {
  readonly quantity?: number;
}
interface QuestRecord {
  readonly id: number;
  readonly name: string;
  readonly raw: UnknownRecord;
}
interface ScriptRuntimeOptions {
  readonly safeStartStop: boolean;
  readonly usePrivateRooms: boolean;
}
type ServerPacketSendType = "String" | "Json";
interface ServerRecord {
  readonly chat: number;
  readonly count: number;
  readonly language: string;
  readonly max: number;
  readonly memberOnly: boolean;
  readonly name: string;
  readonly online: boolean;
  readonly raw: UnknownRecord;
}
interface ShopInfoRecord {
  readonly house: boolean;
  readonly id: number;
  readonly items: readonly ShopItemRecord[];
  readonly limited: boolean;
  readonly merge: boolean;
  readonly name: string;
}
interface ShopItemRecord extends ItemRecord {
  readonly shopItemId?: number | string;
}
type ShopItemSelector =
  | ObjectSelector<ShopItemSelectorShape>
  | ObjectSelector<InventoryItemSelectorShape>
  | number
  | string;
interface SkillUseOptions {
  readonly force?: boolean;
  readonly wait?: boolean;
}
type StateDisposer = () => void;
interface StateSubscriptionOptions {
  readonly emitCurrent?: boolean;
}
type TargetInfo = MonsterTargetInfo | PlayerTargetInfo;
interface WaitOptions {
  readonly interval?: DurationInput;
  readonly timeout?: DurationInput;
}
type FlashEventKind = "packet" | "projection" | "runtime";
type FlashEventType = FlashEvent["type"];
type FlashPacketEvent =
  | {
      readonly kind: "packet";
      readonly payload: FlashPacket;
      readonly type: "packetReceived";
    }
  | {
      readonly kind: "packet";
      readonly payload: {
        readonly direction: FlashPacketDirection;
        readonly raw: string;
      };
      readonly type: "packetParseFailed";
    };
type FlashProjectionEvent =
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: UnknownRecord;
      readonly type: "questComplete";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: MapRecord;
      readonly type: "joinMap";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: {
        readonly map: string;
        readonly zone: string;
      };
      readonly type: "zone";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: {
        readonly afk: boolean;
        readonly entityId?: number;
        readonly isSelf: boolean;
        readonly username: string;
      };
      readonly type: "playerAfk";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: {
        readonly cell?: string;
        readonly entityId?: number;
        readonly isSelf: boolean;
        readonly pad?: string;
        readonly position?: Position;
        readonly username: string;
      };
      readonly type: "playerLocation";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: { readonly monsterMapId: number };
      readonly type: "monsterDeath";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: {
        readonly aura: AuraRecord;
        readonly targetId: number;
        readonly targetType: "monster" | "player";
      };
      readonly type: "auraAdded";
    }
  | {
      readonly kind: "projection";
      readonly packet: FlashPacket;
      readonly payload: {
        readonly auraName: string;
        readonly targetId: number;
        readonly targetType: "monster" | "player";
      };
      readonly type: "auraRemoved";
    };
type FlashRuntimeEvent =
  | {
      readonly kind: "runtime";
      readonly payload: { readonly status: string };
      readonly type: "connection";
    }
  | {
      readonly kind: "runtime";
      readonly payload: { readonly message: string };
      readonly type: "debug";
    }
  | {
      readonly kind: "runtime";
      readonly type: "loaded";
    }
  | {
      readonly kind: "runtime";
      readonly payload: { readonly percent: number };
      readonly type: "progress";
    };
type ObjectSelector<Shape extends Record<string, unknown>> = {
  [Key in keyof Shape]: {
    [SelectedKey in Key]: Shape[SelectedKey];
  } & {
    [OtherKey in Exclude<keyof Shape, Key>]?: never;
  };
}[keyof Shape];
type InventoryItemSelectorShape = ItemSelectorShape;
type MonsterSelectorShape = {
  name: string;
  monMapId: number;
};
type UnknownRecord = Record<string, unknown>;
type FlashPacketDirection = 'client' | 'server' | 'extension';
type FlashPacketWireType = 'str' | 'json' | 'xml' | 'unknown';
interface Json { readonly [key: string]: unknown; }
type ShopItemSelectorShape = ItemSelectorShape & {
  shopItemId: number;
};
type MonsterTargetInfo = TargetBaseInfo & {
  type: "monster";
  monsterId: number;
  monsterMapId: number;
  level: number;
  race: string;
  name: string;
};
type PlayerTargetInfo = TargetBaseInfo & {
  type: "player";
  afk: boolean;
  entityId: number;
  entityType: string;
  level: number;
  mp: number;
  maxMp: number;
  sp: number;
  pad: string;
  username: string;
  name: string;
};
interface MapRecord {
  readonly id: number;
  readonly name: string;
  readonly roomNumber: number;
}
interface Shape { readonly [key: string]: unknown; }
interface SelectedKey { readonly [key: string]: unknown; }
interface OtherKey { readonly [key: string]: unknown; }
type ItemSelectorShape = {
  name: string;
  itemId: number;
};
type TargetBaseInfo = {
  type: "monster" | "player";
  hp: number;
  maxHp: number;
  state: number;
  cell: string;
};
