packages:
  - "packages/*"
  - app
  - docs
  - observability

onlyBuiltDependencies:
  - electron # https://github.com/electron/electron/issues/44008
  - esbuild
  - sharp

ignoredBuiltDependencies:
  - core-js
  - unrs-resolver

allowBuilds:
  core-js: true
  electron-winstaller: false
  esbuild: true
  msgpackr-extract: false
  msw: false
  sharp: true

overrides:
  "@tanstack/solid-virtual": "3.13.24"
  "effect": "4.0.0-beta.83"
  "@effect/platform": "4.0.0-beta.83"
  "@effect/platform-node": "4.0.0-beta.83"
  "@effect/platform-node-shared": "4.0.0-beta.83"
  "fast-uri": "^3.1.2"
  "tmp": "^0.2.6"
  "typescript": "npm:@typescript/typescript6@^6.0.2"
  "vitest": "^3.2.6"
