// @ts-check

const potionShops = {
  Gebo: { map: "alchemyacademy", shop: 2036 },
  Jera: { map: "alchemyacademy", shop: 2114 },
  Fehu: { map: "alchemyacademy", shop: 2116 },
};

/** @type {Record<string, import("./types").PotionRecipe>} */
const potions = {
  "Judgment Tonic": {
    reagents: ["Dragon Scale", "Moglin Tears"],
    trait: "Wis",
    rune: "Jera",
    purchase: potionShops.Jera,
    maxStack: 300,
  },
  "Fortitude Tonic": {
    reagents: ["Necrot", "Roc Tongue"],
    trait: "End",
    rune: "Fehu",
    purchase: potionShops.Fehu,
    maxStack: 300,
  },
  "Fate Tonic": {
    reagents: ["Arashtite Ore", "Dried Slime"],
    trait: "Luc",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Sage Tonic": {
    reagents: ["Arashtite Ore", "Dried Slime"],
    trait: "Int",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Potent Battle Elixir": {
    reagents: ["Doomatter", "Chaoroot"],
    trait: "APw",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Potent Malevolence Elixir": {
    reagents: ["Doomatter", "Chaoroot"],
    trait: "SPw",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Potent Honor Potion": {
    reagents: ["Chaoroot", "Chaos Entity"],
    trait: "Dam",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Unstable Divine Elixir": {
    reagents: ["Dragon Scale", "Lemurphant Tears"],
    trait: "hOu",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 99,
  },
  "Potent Revitalize Elixir": {
    reagents: ["Chaoroot", "Lemurphant Tears"],
    trait: "hRe",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Potent Destruction Elixir": {
    reagents: ["Dried Slime", "Arashtite Ore"],
    trait: "mRe",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Body Tonic": {
    reagents: ["Roc Tongue", "Chaoroot"],
    trait: "End",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Soul Potion": {
    reagents: ["Necrot", "Nimblestem"],
    trait: "Dam",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Unstable Battle Elixir": {
    reagents: ["Doomatter", "Nimblestem"],
    trait: "APw",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Unstable Body Tonic": {
    reagents: ["Nimblestem", "Roc Tongue"],
    trait: "End",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Unstable Fate Tonic": {
    reagents: ["Dried Slime", "Trollola Nectar"],
    trait: "Luc",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Unstable Keen Elixir": {
    reagents: ["Trollola Nectar", "Doomatter"],
    trait: "Cri",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Unstable Mastery Tonic": {
    reagents: ["Chaos Entity", "Dried Slime"],
    trait: "Dex",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Unstable Might Tonic": {
    reagents: ["Chaos Entity", "Fish Oil"],
    trait: "Str",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Unstable Wise Tonic": {
    reagents: ["Moglin Tears", "Rhison Blood"],
    trait: "Wis",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Might Tonic": {
    reagents: ["Chaos Entity", "Rhison Blood"],
    trait: "Dam",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Malice Potion": {
    reagents: ["Chaoroot", "Chaos Entity"],
    trait: "Dam",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Potent Life Potion": {
    reagents: ["Dragon Scale", "Searbush"],
    trait: "Hea",
    rune: "Gebo",
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Endurance Draught": {
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Felicitous Philtre": {
    purchase: potionShops.Gebo,
    maxStack: 300,
  },
  "Scroll of Life Steal": {
    purchase: { map: "arcangrove", shop: 211 },
    maxStack: 99,
  },
};

/** @type {Record<string, number>} */
const scrolls = {
  "Scroll of Fireball": 2295,
  "Scroll of Shadowburn": 2296,
  "Scroll of Plasma Bolt": 2297,
  "Scroll of Dark Energy": 2298,
  "Scroll of Ssikari's Breath": 2299,
  "Scroll of Shadow Bolt": 2300,
  "Scroll of Diamond Cage": 2301,
  "Scroll of Exorcise": 2302,
  "Scroll of Acid Rain": 2303,
  "Scroll of Heartbeat": 2304,
  "Scroll of Corrosion": 2305,
  "Scroll of Crushing Wave": 2306,
  "Scroll of Wind Strike": 2307,
  "Scroll of Arc Lightning": 2308,
  "Scroll of Spirit Rend": 2309,
  "Scroll of Dark Arc": 2310,
  "Scroll of Chains": 2311,
  "Scroll of Eclipse": 2312,
  "Scroll of Purge": 2313,
  "Scroll of Scorched Steel": 2314,
  "Scroll of Firebolt": 2315,
  "Scroll of Holy Bolt": 2316,
  "Scroll of Blessed Shard": 2317,
  "Scroll of Frostbite": 2318,
  "Scroll of Geyser": 2319,
  "Scroll of Fire Flare": 2320,
  "Scroll of Frost Flare": 2321,
  "Scroll of Plague Flare": 2322,
  "Scroll of Charged Flare": 2323,
  "Scroll of Doom Flare": 2324,
  "Scroll of Holy Flare": 2325,
  "Scroll of Blinding Light": 2326,
  "Scroll of Guardian Blast": 2327,
  "Scroll of Shadowblade": 2328,
  "Scroll of Furious Gale": 2329,
  "Scroll of Enrage": 2330,
  "Scroll of Decay": 2331,
  "Scroll of Death Pact": 2332,
  "Scroll of Cantor's Lament": 2333,
  "Scroll of Pulse Compression": 2334,
  "Scroll of Dissonance": 2335,
  "Scroll of Soul Crush": 2336,
  "Scroll of Void Strike": 2337,
  "Scroll of Psychic Wave": 2338,
  "Scroll of Chaos Fog": 2339,
  "Scroll of Torment": 2340,
  "Scroll of Shiftburn": 2341,
  "Scroll of Freezing Flame": 2342,
  "Scroll of Fire Storm": 2343,
  "Scroll of Mystify": 2344,
  "Scroll of Wither": 2345,
  "Scroll of Underworld": 2346,
  "Scroll of Ethereal Slumber": 2347,
  "Scroll of Ethereal Curse": 2348,
  "Scroll of Dark Grip": 2349,
  "Scroll of Weaken": 2350,
  "Scroll of Bane": 2351,
  "Scroll of Petrify": 2352,
  "Scroll of Cripple": 2353,
};

/** @type {Record<string, import("./types").Material>} */
const materials = {
  "Fish Oil": {
    item: 11467,
    name: "Fish Oil",
    map: "alchemyacademy",
    shop: 397,
    batchQuantity: 3,
  },
  Searbush: {
    item: 11468,
    name: "Searbush",
    map: "alchemyacademy",
    shop: 397,
    batchQuantity: 2,
    farm: {
      map: "mafic",
      monster: "Living Fire",
    },
  },
  Nimblestem: {
    item: 11469,
    name: "Nimblestem",
    map: "alchemyacademy",
    shop: 397,
    batchQuantity: 2,
    farm: {
      map: "mudluk",
      monster: "Swamp Frogdrake",
    },
  },
  "Rhison Blood": {
    item: 11470,
    name: "Rhison Blood",
    map: "alchemyacademy",
    shop: 397,
    batchQuantity: 2,
    farm: {
      map: "bloodtusk",
      monster: "Rhison",
    },
  },
  "Roc Tongue": {
    item: 11471,
    name: "Roc Tongue",
    map: "alchemyacademy",
    shop: 397,
    batchQuantity: 2,
    farm: {
      map: "roc",
      monster: "Rock Roc",
    },
  },
  "Moglin Tears": {
    item: 11472,
    name: "Moglin Tears",
    map: "alchemyacademy",
    shop: 397,
    batchQuantity: 2,
    farm: {
      map: "twig",
      monster: "Sweetish Fish",
      memberOnly: true,
    },
  },
  "Arashtite Ore": {
    item: 11473,
    name: "Arashtite Ore",
    map: "alchemyacademy",
    shop: 397,
    batchQuantity: 2,
    farm: {
      map: "orecavern",
      monster: "Deathmole",
    },
  },
  "Dried Slime": {
    item: 11474,
    name: "Dried Slime",
    map: "alchemyacademy",
    shop: 397,
    batchQuantity: 2,
    farm: {
      map: "orecavern",
      monster: "Crashroom",
    },
  },
  "Dragon Scale": {
    item: 11475,
    name: "Dragon Scale",
    map: "alchemyacademy",
    shop: 397,
    batchQuantity: 2,
    farm: {
      map: "lair",
      monster: "*",
      cell: "Hole",
      pad: "Center",
    },
  },
  "Trollola Nectar": {
    item: 11476,
    name: "Trollola Nectar",
    map: "alchemyacademy",
    shop: 397,
    batchQuantity: 2,
    farm: {
      map: "bloodtusk",
      monster: "Trollola Plant",
    },
  },
  Doomatter: {
    item: 11477,
    name: "Doomatter",
    map: "alchemyacademy",
    shop: 397,
    batchQuantity: 2,
    farm: {
      map: "maul",
      monster: "Creature Creation",
    },
  },
  "Ice Vapor": {
    item: 11478,
    name: "Ice Vapor",
    map: "alchemyacademy",
    shop: 397,
    batchQuantity: 2,
    farm: {
      map: "lair",
      monster: "*",
    },
  },
  "Lemurphant Tears": {
    item: 11479,
    name: "Lemurphant Tears",
    map: "alchemyacademy",
    shop: 397,
    batchQuantity: 2,
    farm: {
      map: "ravinetemple",
      monster: "Lemurphant",
    },
  },
  Necrot: {
    item: 11480,
    name: "Necrot",
    map: "alchemyacademy",
    shop: 397,
    batchQuantity: 2,
    farm: {
      map: "deathsrealm",
      monster: "Skeleton Fighter",
    },
  },
  Chaoroot: {
    item: 11481,
    name: "Chaoroot",
    map: "tercessuinotlim",
    shop: 1951,
    batchQuantity: 10,
    farm: {
      map: "orecavern",
      monster: "Naga Baas",
    },
  },
  "Chaos Entity": {
    item: 11482,
    name: "Chaos Entity",
    map: "alchemyacademy",
    shop: 2114,
    batchQuantity: 1,
  },
  "Gold Voucher 100k": {
    item: 62749,
    name: "Gold Voucher 100k",
    map: "alchemyacademy",
    shop: 2036,
  },
  "Gold Voucher 500k": {
    item: 61043,
    name: "Gold Voucher 500k",
    map: "alchemyacademy",
    shop: 2036,
  },
  "Dragon Runestone": {
    item: "Dragon Runestone",
    name: "Dragon Runestone",
    map: "alchemyacademy",
    shop: 395,
    batchQuantity: 1,
  },
  "Arcane Quill": {
    item: 17391,
    name: "Arcane Quill",
    map: "spellcraft",
    shop: 693,
    batchQuantity: 1,
  },
  "Mystic Parchment": {
    item: "Mystic Parchment",
    name: "Mystic Parchment",
    map: "spellcraft",
    shop: 549,
    farm: {
      map: "underworld",
      monster: "Skull Warrior",
    },
  },
  "Mystic Quills": {
    item: "Mystic Quills",
    name: "Mystic Quills",
    map: "spellcraft",
    shop: 549,
    farm: {
      map: "mobius",
      monster: "Slugfit",
    },
  },
};

module.exports = { potions, scrolls, materials };
