import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { promisify } from "node:util";
import { fileURLToPath, pathToFileURL } from "node:url";

import * as NodeRuntime from "@effect/platform-node/NodeRuntime";
import * as Console from "effect/Console";
import * as Effect from "effect/Effect";
import ts from "typescript";
import {
  Application,
  type DeclarationReflection,
  type ProjectReflection,
  type Reflection,
  ReflectionKind,
  type SignatureReflection,
  type SomeType,
} from "typedoc";
import {
  getPropertyName,
  parseTypeReference,
  resolveOmitInterfaceAlias,
  type TypeReferenceInfo,
} from "./ts-ast-utils";

const execFileAsync = promisify(execFile);

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const DEFAULT_REPO_ROOT = join(SCRIPT_DIR, "..");
const DEFAULT_SOURCE_FILE = "app/src/renderer/apps/game/scripting/ScriptApi.ts";
const DEFAULT_OUTPUT_DIR = "docs/src/content/docs/scripting";
const LEGACY_OUTPUT_DIR = "docs/src/content/docs/script-commands";
const SOURCE_LINKS_OUTPUT = "docs/src/generated/script-source-links.ts";
const TYPE_PREVIEWS_OUTPUT = "docs/public/script-type-previews.json";
const APP_TSCONFIG = "app/tsconfig.json";
const SOURCE_REF_ENV = "DOCGEN_SOURCE_REF";
const DEFAULT_SOURCE_REF = "main";
const GENERATED_HEADER =
  "<!-- Generated by pnpm run docgen. Do not edit directly. -->";
const DOCGEN_COMPILER_PATHS: Record<string, string[]> = {
  "@lucent/game": ["packages/game/src/index.ts"],
  "@lucent/core": ["packages/core/src/index.ts"],
  "@lucent/core/accounts": ["packages/core/src/accounts.ts"],
  "@lucent/core/appearance": ["packages/core/src/appearance.ts"],
  "@lucent/core/army": ["packages/core/src/army.ts"],
  "@lucent/core/combatProfiles": ["packages/core/src/combatProfiles.ts"],
  "@lucent/core/environment": ["packages/core/src/environment.ts"],
  "@lucent/core/hotkeys": ["packages/core/src/hotkeys.ts"],
  "@lucent/core/scriptInputs": ["packages/core/src/scriptInputs.ts"],
  "@lucent/core/settings": ["packages/core/src/settings.ts"],
  "*": ["app/*"],
};

const TYPE_REFERENCE_WRAPPERS = new Set([
  "Array",
  "Effect",
  "Generator",
  "Omit",
  "Partial",
  "Pick",
  "Readonly",
  "ReadonlyArray",
  "Record",
  "Required",
]);

const BUILTIN_TYPE_NAMES = new Set([
  "AbortSignal",
  "Boolean",
  "Date",
  "Duration",
  "Error",
  "Function",
  "Number",
  "Object",
  "Option",
  "Promise",
  "String",
  "any",
  "boolean",
  "false",
  "never",
  "null",
  "number",
  "readonly",
  "string",
  "true",
  "undefined",
  "unknown",
  "void",
]);

type CliOptions = {
  readonly repoRoot: string;
  readonly sourceFile: string;
  readonly outputDir: string;
  readonly includeSourceLinks: boolean;
};

type GitSourceInfo = {
  readonly repoUrl: string;
  readonly ref: string;
};

type SourceInfo = {
  readonly sourcePath: string;
  readonly sourceLine: number;
  readonly sourceUrl: string | null;
};

type ParameterDoc = {
  readonly name: string;
  readonly type: string;
  readonly required: boolean;
  readonly rest: boolean;
  readonly description: string;
};

type ReturnDoc = {
  readonly raw: string;
  readonly result: string | null;
  readonly error: string | null;
};

type MemberDoc = SourceInfo & {
  readonly path: string;
  readonly name: string;
  readonly kind: "method" | "effect" | "value";
  readonly summary: string;
  readonly signature: string;
  readonly parameters: readonly ParameterDoc[];
  readonly returnDoc: ReturnDoc;
};

type TypeMemberDoc = SourceInfo & {
  readonly name: string;
  readonly type: string;
  readonly summary: string;
  readonly readonly: boolean;
  readonly optional: boolean;
  readonly inheritedFrom: string | null;
};

type TypeMethodDoc = SourceInfo & {
  readonly name: string;
  readonly signature: string;
  readonly summary: string;
  readonly inheritedFrom: string | null;
};

type ReferencedTypeDoc = SourceInfo & {
  readonly name: string;
  readonly slug: string;
  readonly kind: string;
  readonly summary: string;
  readonly aliasOf: string | null;
  readonly definition: string;
  readonly properties: readonly TypeMemberDoc[];
  readonly methods: readonly TypeMethodDoc[];
};

type ApiGroup = {
  readonly id: string;
  readonly title: string;
  readonly label: string;
  readonly description: string;
  readonly summary: string;
  readonly members: readonly MemberDoc[];
  readonly typeReferences: readonly string[];
};

type ApiNamespace = {
  readonly name: string;
  readonly slug: string;
  readonly href: string;
  readonly sourceType: string;
};

type TypeLink = {
  readonly href: string;
  readonly slug: string;
};

type RenderedFile = {
  readonly path: string;
  readonly content: string;
};

class DocgenError extends Error {
  override readonly name = "DocgenError";

  constructor(message: string, options?: { readonly cause?: unknown }) {
    super(message);
    this.cause = options?.cause;
  }
}

const fail = (message: string): never => {
  throw new DocgenError(message);
};

const parseCliOptions = (
  args: ReadonlyArray<string>,
  repoRoot: string,
): CliOptions => {
  let source = DEFAULT_SOURCE_FILE;
  let out = DEFAULT_OUTPUT_DIR;
  let includeSourceLinks = true;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index] ?? fail(`Unable to read argument at ${index}`);
    if (arg === "--") {
      continue;
    }
    if (arg === "--include-source-links") {
      includeSourceLinks = true;
      continue;
    }
    if (arg === "--no-source-links") {
      includeSourceLinks = false;
      continue;
    }
    if (arg === "--source") {
      source = args[index + 1] ?? fail("--source requires a path");
      index += 1;
      continue;
    }
    if (arg.startsWith("--source=")) {
      source = arg.slice("--source=".length);
      continue;
    }
    if (arg === "--out") {
      out = args[index + 1] ?? fail("--out requires a path");
      index += 1;
      continue;
    }
    if (arg.startsWith("--out=")) {
      out = arg.slice("--out=".length);
      continue;
    }
    fail(`Unknown argument: ${arg}`);
  }

  return {
    repoRoot,
    sourceFile: isAbsolute(source) ? source : resolve(repoRoot, source),
    outputDir: isAbsolute(out) ? out : resolve(repoRoot, out),
    includeSourceLinks,
  };
};

const normalizeGitRemoteUrl = (rawUrl: string): string | null => {
  const url = rawUrl.trim().replace(/\.git$/, "");
  if (url.startsWith("https://")) {
    return url;
  }
  if (url.startsWith("http://")) {
    return `https://${url.slice("http://".length)}`;
  }

  const sshMatch = url.match(/^git@([^:]+):(.+)$/);
  if (sshMatch) {
    return `https://${sshMatch[1]}/${sshMatch[2]}`;
  }

  return null;
};

const getGitSourceInfo = (
  repoRoot: string,
): Effect.Effect<GitSourceInfo | null> =>
  Effect.gen(function* () {
    const remoteUrl = yield* Effect.tryPromise(async () => {
      const result = await execFileAsync(
        "git",
        ["remote", "get-url", "origin"],
        { cwd: repoRoot },
      );
      return result.stdout;
    }).pipe(Effect.catch(() => Effect.succeed(null)));

    if (remoteUrl === null) {
      return null;
    }

    const repoUrl = normalizeGitRemoteUrl(remoteUrl);
    if (repoUrl === null) {
      return null;
    }

    const sourceRef = process.env[SOURCE_REF_ENV]?.trim();
    if (sourceRef) {
      return { repoUrl, ref: sourceRef };
    }

    return { repoUrl, ref: DEFAULT_SOURCE_REF };
  });

const buildSourceUrl = (
  git: GitSourceInfo | null,
  repoRoot: string,
  sourcePath: string,
  sourceLine: number,
): string | null => {
  if (git === null) {
    return null;
  }

  const repoRelativePath = relative(repoRoot, sourcePath).replaceAll("\\", "/");
  return `${git.repoUrl}/blob/${git.ref}/${repoRelativePath}#L${sourceLine}`;
};

const getSourceInfo = (
  options: CliOptions,
  git: GitSourceInfo | null,
  node: ts.Node,
): SourceInfo => {
  const sourceFile = node.getSourceFile();
  const sourceLine =
    sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile)).line +
    1;

  return {
    sourcePath: relative(options.repoRoot, sourceFile.fileName).replaceAll(
      "\\",
      "/",
    ),
    sourceLine,
    sourceUrl: buildSourceUrl(
      git,
      options.repoRoot,
      sourceFile.fileName,
      sourceLine,
    ),
  };
};

const titleCase = (value: string): string =>
  value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");

const kebabCase = (value: string): string =>
  value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^A-Za-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();

const anchorSlug = (value: string): string =>
  value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "");

const memberAnchor = (path: string): string => `member-${anchorSlug(path)}`;

const escapeTableCell = (value: string): string =>
  value
    .replaceAll("\\", "\\\\")
    .replaceAll("|", "\\|")
    .replace(/\r?\n/g, "<br>");

const escapeHtml = (value: string): string =>
  value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");

const renderCode = (value: string): string => `\`${escapeTableCell(value)}\``;
const renderHtmlCode = (value: string): string =>
  `<code>${escapeHtml(value)}</code>`;
const lucideCheckIcon =
  '<span class="required-mark" role="img" aria-label="Required"></span>';

const renderBooleanMark = (value: boolean): string =>
  value ? lucideCheckIcon : "";

const getText = (
  value:
    | string
    | ts.NodeArray<ts.JSDocComment>
    | readonly ts.JSDocComment[]
    | undefined,
): string => {
  if (value === undefined) {
    return "";
  }
  if (typeof value === "string") {
    return value.trim();
  }

  return value
    .map((part) => {
      const text = (part as { text?: unknown }).text;
      return text === undefined ? (part as ts.Node).getText() : String(text);
    })
    .join("")
    .trim();
};

const getNodeJsDoc = (node: ts.Node): ts.JSDoc | null => {
  const docs = (node as ts.Node & { jsDoc?: ts.JSDoc[] }).jsDoc;
  return docs?.[docs.length - 1] ?? null;
};

const getSummary = (node: ts.Node): string =>
  getText(getNodeJsDoc(node)?.comment);

const getParamDescriptions = (
  node: ts.SignatureDeclaration,
): ReadonlyMap<string, string> => {
  const descriptions = new Map<string, string>();
  const doc = getNodeJsDoc(node);
  if (!doc?.tags) {
    return descriptions;
  }

  for (const tag of doc.tags) {
    if (!ts.isJSDocParameterTag(tag)) {
      continue;
    }
    descriptions.set(
      tag.name.getText(),
      getText(tag.comment).replace(/^\s*-\s+/, ""),
    );
  }

  return descriptions;
};

const createProgram = (repoRoot: string): ts.Program => {
  const configPath = resolve(repoRoot, APP_TSCONFIG);
  const readResult = ts.readConfigFile(configPath, ts.sys.readFile);
  if (readResult.error) {
    fail(ts.flattenDiagnosticMessageText(readResult.error.messageText, "\n"));
  }

  const parsed = ts.parseJsonConfigFileContent(
    readResult.config,
    ts.sys,
    dirname(configPath),
  );

  if (parsed.errors.length > 0) {
    fail(
      parsed.errors
        .map((error) =>
          ts.flattenDiagnosticMessageText(error.messageText, "\n"),
        )
        .join("\n"),
    );
  }

  return ts.createProgram({
    rootNames: parsed.fileNames,
    options: {
      ...parsed.options,
      baseUrl: repoRoot,
      paths: DOCGEN_COMPILER_PATHS,
    },
  });
};

const isInsideRepo = (repoRoot: string, fileName: string): boolean => {
  const rel = relative(repoRoot, fileName);
  return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
};

const buildDeclarationMap = (
  program: ts.Program,
): ReadonlyMap<string, ts.InterfaceDeclaration | ts.TypeAliasDeclaration> => {
  const declarations = new Map<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >();

  const declarationRank = (
    declaration: ts.InterfaceDeclaration | ts.TypeAliasDeclaration,
  ): number => {
    const fileName = declaration.getSourceFile().fileName.replaceAll("\\", "/");
    return (
      (fileName.includes("/dist/") ? 10 : 0) +
      (/\.d\.[cm]?ts$/.test(fileName) ? 5 : 0)
    );
  };

  const visit = (node: ts.Node): void => {
    if (ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) {
      const current = declarations.get(node.name.text);
      if (current === undefined || declarationRank(node) < declarationRank(current)) {
        declarations.set(node.name.text, node);
      }
    }
    ts.forEachChild(node, visit);
  };

  for (const sourceFile of program.getSourceFiles()) {
    if (sourceFile.fileName.includes("/node_modules/")) {
      continue;
    }
    visit(sourceFile);
  }

  return declarations;
};

const getInterface = (
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  name: string,
  seen = new Set<string>(),
): ts.InterfaceDeclaration => {
  if (seen.has(name)) {
    fail(`Unable to resolve circular interface alias ${name}`);
  }

  const declaration =
    declarations.get(name) ?? fail(`Unable to find interface ${name}`);

  if (ts.isInterfaceDeclaration(declaration)) {
    return declaration;
  }

  const reference = parseTypeReference(declaration.type);
  if (reference) {
    const nextSeen = new Set(seen);
    nextSeen.add(name);
    const omitted = resolveOmitInterfaceAlias(
      reference,
      (targetName) => getInterface(declarations, targetName, nextSeen),
      { referenceName: "unqualifiedName" },
    );
    if (omitted) {
      return omitted;
    }
    return getInterface(declarations, reference.unqualifiedName, nextSeen);
  }

  return fail(`Unable to find interface ${name}`);
};

const typeText = (
  node: ts.TypeNode | undefined,
  sourceFile: ts.SourceFile,
): string => (node === undefined ? "unknown" : node.getText(sourceFile));

const splitTopLevel = (value: string, delimiter = ","): string[] => {
  const parts: string[] = [];
  let depth = 0;
  let start = 0;

  for (let index = 0; index < value.length; index += 1) {
    const char = value[index];
    if (char === "<" || char === "(" || char === "[" || char === "{") {
      depth += 1;
    } else if (char === ">" || char === ")" || char === "]" || char === "}") {
      depth = Math.max(0, depth - 1);
    } else if (char === delimiter && depth === 0) {
      parts.push(value.slice(start, index).trim());
      start = index + 1;
    }
  }

  parts.push(value.slice(start).trim());
  return parts;
};

const isEffectTypeNode = (node: ts.TypeNode | undefined): boolean => {
  const reference = parseTypeReference(node);
  if (!reference) {
    return false;
  }
  return reference.unqualifiedName === "Effect" && reference.args.length >= 1;
};

const expressionNameText = (node: ts.Expression): string | null => {
  if (ts.isIdentifier(node)) {
    return node.text;
  }

  if (ts.isPropertyAccessExpression(node)) {
    const left = expressionNameText(node.expression);
    return left === null ? node.name.text : `${left}.${node.name.text}`;
  }

  return null;
};

const unqualifiedExpressionName = (node: ts.Expression): string | null => {
  if (ts.isIdentifier(node)) {
    return node.text;
  }

  if (ts.isPropertyAccessExpression(node)) {
    return node.name.text;
  }

  return null;
};

const parseHeritageReference = (
  node: ts.ExpressionWithTypeArguments,
): TypeReferenceInfo | null => {
  const name = expressionNameText(node.expression);
  const unqualifiedName = unqualifiedExpressionName(node.expression);
  if (name === null || unqualifiedName === null) {
    return null;
  }

  return {
    name,
    unqualifiedName,
    args: Array.from(node.typeArguments ?? []),
  };
};

const formatResolvedType = (
  checker: ts.TypeChecker,
  type: ts.Type,
  node: ts.Node,
): string =>
  checker
    .typeToString(
      type,
      node,
      ts.TypeFormatFlags.NoTruncation |
        ts.TypeFormatFlags.UseSingleQuotesForStringLiteralType,
    )
    .replace(/import\(["'][^"']+["']\)\./g, "");

const formatType = (
  checker: ts.TypeChecker,
  node: ts.TypeNode | undefined,
): string => {
  if (node === undefined) {
    return "unknown";
  }

  return formatResolvedType(checker, checker.getTypeAtLocation(node), node);
};

const parseEffectReturn = (
  raw: string,
  node: ts.TypeNode | undefined,
  sourceFile: ts.SourceFile,
): ReturnDoc => {
  const reference = parseTypeReference(node);
  if (reference?.unqualifiedName === "Effect" && reference.args.length >= 1) {
    return {
      raw,
      result: typeText(reference.args[0], sourceFile),
      error:
        reference.args.length >= 2
          ? typeText(reference.args[1], sourceFile)
          : "never",
    };
  }

  if (
    reference?.unqualifiedName === "BridgeEffect" &&
    reference.args.length >= 1
  ) {
    return {
      raw,
      result: typeText(reference.args[0], sourceFile),
      error: "BridgeError",
    };
  }

  if (
    reference?.unqualifiedName === "ArmyEffect" &&
    reference.args.length >= 1
  ) {
    const extraError =
      reference.args.length >= 2
        ? `${typeText(reference.args[1], sourceFile)} | `
        : "";
    return {
      raw,
      result: typeText(reference.args[0], sourceFile),
      error: `${extraError}ArmyError | BridgeError`,
    };
  }

  const effectMatch = /^(?:Effect\.)?Effect<(.+)>$/.exec(raw);
  if (effectMatch?.[1]) {
    const args = splitTopLevel(effectMatch[1]);
    return {
      raw,
      result: args[0] ?? "unknown",
      error: args[1] ?? "never",
    };
  }

  return { raw, result: null, error: null };
};

const getReturnDoc = (
  checker: ts.TypeChecker,
  node: ts.SignatureDeclaration,
): ReturnDoc => {
  const sourceFile = node.getSourceFile();
  const raw =
    node.type === undefined
      ? checker.typeToString(
          checker.getSignatureFromDeclaration(node)?.getReturnType() ??
            checker.getAnyType(),
          node,
          ts.TypeFormatFlags.NoTruncation,
        )
      : formatType(checker, node.type);

  return parseEffectReturn(raw, node.type, sourceFile);
};

const getParameterDocs = (
  checker: ts.TypeChecker,
  node: ts.SignatureDeclaration,
): ParameterDoc[] => {
  const descriptions = getParamDescriptions(node);
  const sourceFile = node.getSourceFile();

  return node.parameters.map((parameter) => {
    const name = parameter.name.getText(sourceFile);
    return {
      name,
      type: formatType(checker, parameter.type),
      required:
        parameter.questionToken === undefined &&
        parameter.initializer === undefined &&
        parameter.dotDotDotToken === undefined,
      rest: parameter.dotDotDotToken !== undefined,
      description: descriptions.get(name) ?? "",
    };
  });
};

const methodSignature = (
  path: string,
  parameters: readonly ParameterDoc[],
  returnDoc: ReturnDoc,
): string =>
  `${path}(${parameters
    .map(
      (parameter) =>
        `${parameter.rest ? "..." : ""}${parameter.name}${
          parameter.required ? "" : "?"
        }: ${parameter.type}`,
    )
    .join(", ")}): ${returnDoc.raw}`;

const collectTypeReferences = (
  node: ts.Node | undefined,
  output: Set<string>,
): void => {
  if (node === undefined) {
    return;
  }

  if (ts.isTypeReferenceNode(node)) {
    const name = parseTypeReference(node)?.unqualifiedName;
    if (
      name &&
      !TYPE_REFERENCE_WRAPPERS.has(name) &&
      !BUILTIN_TYPE_NAMES.has(name)
    ) {
      output.add(name);
    }
  }

  ts.forEachChild(node, (child) => collectTypeReferences(child, output));
};

const expandTypeReferences = (
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  roots: ReadonlySet<string>,
): ReadonlySet<string> => {
  const expanded = new Set(roots);
  const pending = Array.from(roots);

  for (let index = 0; index < pending.length; index += 1) {
    const name = pending[index];
    if (name === undefined) {
      continue;
    }

    const declaration = declarations.get(name);
    if (declaration === undefined) {
      continue;
    }

    const nested = new Set<string>();
    collectTypeReferences(declaration, nested);
    if (ts.isInterfaceDeclaration(declaration)) {
      for (const clause of declaration.heritageClauses ?? []) {
        for (const heritage of clause.types) {
          const reference = parseHeritageReference(heritage);
          if (reference !== null) {
            nested.add(reference.unqualifiedName);
          }
        }
      }
    }

    for (const reference of nested) {
      if (
        expanded.has(reference) ||
        BUILTIN_TYPE_NAMES.has(reference) ||
        TYPE_REFERENCE_WRAPPERS.has(reference)
      ) {
        continue;
      }
      expanded.add(reference);
      pending.push(reference);
    }
  }

  return expanded;
};

const resolveNestedInterface = (
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  node: ts.TypeNode | undefined,
): ts.InterfaceDeclaration | null => {
  const reference = parseTypeReference(node);
  if (!reference) {
    return null;
  }

  const declaration = declarations.get(reference.unqualifiedName);
  return declaration && ts.isInterfaceDeclaration(declaration)
    ? declaration
    : null;
};

const resolveInheritedInterface = (
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  heritage: ts.ExpressionWithTypeArguments,
): ts.InterfaceDeclaration | null => {
  const reference = parseHeritageReference(heritage);
  if (reference === null) {
    return null;
  }

  const omitted = resolveOmitInterfaceAlias(
    reference,
    (targetName) => getInterface(declarations, targetName),
    { referenceName: "unqualifiedName" },
  );
  if (omitted !== null) {
    return omitted;
  }

  if (reference.unqualifiedName === "Pick") {
    return null;
  }

  const declaration = declarations.get(reference.unqualifiedName);
  if (declaration === undefined) {
    return null;
  }

  return ts.isInterfaceDeclaration(declaration)
    ? declaration
    : getInterface(declarations, reference.unqualifiedName);
};

const collectInterfaceMemberNames = (
  declaration: ts.InterfaceDeclaration,
): ReadonlySet<string> => {
  const names = new Set<string>();
  for (const member of declaration.members) {
    if (!ts.isMethodSignature(member) && !ts.isPropertySignature(member)) {
      continue;
    }

    const name = getPropertyName(member.name);
    if (name !== null) {
      names.add(name);
    }
  }
  return names;
};

const topLevelPathMember = (basePath: string, path: string): string => {
  const prefix = `${basePath}.`;
  return path.startsWith(prefix)
    ? (path.slice(prefix.length).split(".")[0] ?? path)
    : path;
};

const collectMembersFromInterface = (
  checker: ts.TypeChecker,
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  options: CliOptions,
  git: GitSourceInfo | null,
  declaration: ts.InterfaceDeclaration,
  basePath: string,
  typeReferences: Set<string>,
  seenInterfaces = new Set<string>(),
): MemberDoc[] => {
  if (seenInterfaces.has(declaration.name.text)) {
    return [];
  }

  const nextSeen = new Set(seenInterfaces);
  nextSeen.add(declaration.name.text);
  const docs: MemberDoc[] = [];
  const ownMemberNames = collectInterfaceMemberNames(declaration);

  for (const heritageClause of declaration.heritageClauses ?? []) {
    if (heritageClause.token !== ts.SyntaxKind.ExtendsKeyword) {
      continue;
    }

    for (const heritage of heritageClause.types) {
      const inheritedInterface = resolveInheritedInterface(
        declarations,
        heritage,
      );
      if (inheritedInterface === null) {
        continue;
      }

      docs.push(
        ...collectMembersFromInterface(
          checker,
          declarations,
          options,
          git,
          inheritedInterface,
          basePath,
          typeReferences,
          nextSeen,
        ).filter(
          (doc) =>
            !ownMemberNames.has(topLevelPathMember(basePath, doc.path)),
        ),
      );
    }
  }

  for (const member of declaration.members) {
    if (ts.isMethodSignature(member)) {
      const name = getPropertyName(member.name);
      if (name === null) {
        continue;
      }

      const parameters = getParameterDocs(checker, member);
      const returnDoc = getReturnDoc(checker, member);
      for (const parameter of member.parameters) {
        collectTypeReferences(parameter.type, typeReferences);
      }
      collectTypeReferences(member.type, typeReferences);

      const path = `${basePath}.${name}`;
      docs.push({
        path,
        name,
        kind: "method",
        summary: getSummary(member),
        signature: methodSignature(path, parameters, returnDoc),
        parameters,
        returnDoc,
        ...getSourceInfo(options, git, member),
      });
      continue;
    }

    if (!ts.isPropertySignature(member)) {
      continue;
    }

    const name = getPropertyName(member.name);
    if (name === null) {
      continue;
    }

    const nestedInterface = resolveNestedInterface(declarations, member.type);
    if (nestedInterface !== null && !isEffectTypeNode(member.type)) {
      docs.push(
        ...collectMembersFromInterface(
          checker,
          declarations,
          options,
          git,
          nestedInterface,
          `${basePath}.${name}`,
          typeReferences,
          nextSeen,
        ),
      );
      continue;
    }

    if (member.type && ts.isFunctionTypeNode(member.type)) {
      const parameters = getParameterDocs(checker, member.type);
      const returnDoc = getReturnDoc(checker, member.type);
      for (const parameter of member.type.parameters) {
        collectTypeReferences(parameter.type, typeReferences);
      }
      collectTypeReferences(member.type.type, typeReferences);

      const path = `${basePath}.${name}`;
      docs.push({
        path,
        name,
        kind: "method",
        summary: getSummary(member),
        signature: methodSignature(path, parameters, returnDoc),
        parameters,
        returnDoc,
        ...getSourceInfo(options, git, member),
      });
      continue;
    }

    collectTypeReferences(member.type, typeReferences);

    const returnDoc = parseEffectReturn(
      formatType(checker, member.type),
      member.type,
      member.getSourceFile(),
    );
    docs.push({
      path: `${basePath}.${name}`,
      name,
      kind: returnDoc.result === null ? "value" : "effect",
      summary: getSummary(member),
      signature: `${basePath}.${name}: ${returnDoc.raw}`,
      parameters: [],
      returnDoc,
      ...getSourceInfo(options, git, member),
    });
  }

  return docs.sort((a, b) => a.path.localeCompare(b.path));
};

const getSymbolDeclaration = (symbol: ts.Symbol): ts.Declaration | null =>
  symbol.valueDeclaration ?? symbol.declarations?.[0] ?? null;

const getSymbolSummary = (
  checker: ts.TypeChecker,
  symbol: ts.Symbol,
  declaration: ts.Declaration | null,
  signatureDeclaration?: ts.SignatureDeclaration,
): string =>
  (declaration === null ? "" : getSummary(declaration)) ||
  ts.displayPartsToString(symbol.getDocumentationComment(checker)).trim() ||
  (signatureDeclaration === undefined
    ? ""
    : getSummary(signatureDeclaration));

const isDocumentableSymbol = (
  options: CliOptions,
  symbol: ts.Symbol,
): boolean =>
  (symbol.declarations ?? []).some((declaration) => {
    const fileName = declaration.getSourceFile().fileName;
    return (
      isInsideRepo(options.repoRoot, fileName) &&
      !fileName.includes("/node_modules/") &&
      !fileName.endsWith(".test.ts")
    );
  });

const getSignatureParameterDocs = (
  checker: ts.TypeChecker,
  signature: ts.Signature,
  fallbackNode: ts.Node,
): ParameterDoc[] =>
  signature.getParameters().map((parameter) => {
    const declaration = getSymbolDeclaration(parameter);
    const typeNode = declaration ?? fallbackNode;
    const parameterDeclaration =
      declaration !== null && ts.isParameter(declaration)
        ? declaration
        : null;
    const description = ts
      .displayPartsToString(parameter.getDocumentationComment(checker))
      .trim();

    return {
      name: parameter.name,
      type: formatResolvedType(
        checker,
        checker.getTypeOfSymbolAtLocation(parameter, typeNode),
        typeNode,
      ),
      required:
        (parameter.flags & ts.SymbolFlags.Optional) === 0 &&
        parameterDeclaration?.questionToken === undefined &&
        parameterDeclaration?.initializer === undefined &&
        parameterDeclaration?.dotDotDotToken === undefined,
      rest: parameterDeclaration?.dotDotDotToken !== undefined,
      description,
    };
  });

const collectTaggedTypeReferences = (
  checker: ts.TypeChecker,
  node: ts.Node,
  references: Set<string>,
): void => {
  if (ts.isTypeReferenceNode(node)) {
    const referenced = checker.getSymbolAtLocation(node.typeName);
    const symbol =
      referenced !== undefined &&
      (referenced.flags & ts.SymbolFlags.Alias) !== 0
        ? checker.getAliasedSymbol(referenced)
        : referenced;
    if (
      symbol !== undefined &&
      (symbol.declarations ?? []).some((declaration) =>
        ts
          .getJSDocTags(declaration)
          .some((tag) => tag.tagName.text === "scriptingExpandSchema"),
      )
    ) {
      references.add(symbol.name);
    }
  }

  ts.forEachChild(node, (child) =>
    collectTaggedTypeReferences(checker, child, references),
  );
};

const collectMembersFromType = (
  checker: ts.TypeChecker,
  options: CliOptions,
  git: GitSourceInfo | null,
  type: ts.Type,
  fallbackNode: ts.Node,
  basePath: string,
  typeReferences: Set<string>,
  seenTypes = new Set<ts.Type>(),
): MemberDoc[] => {
  if (seenTypes.has(type)) {
    return [];
  }

  const nextSeen = new Set(seenTypes);
  nextSeen.add(type);
  const docs: MemberDoc[] = [];

  for (const symbol of checker.getPropertiesOfType(type)) {
    const name = symbol.getName();
    const declaration = getSymbolDeclaration(symbol);
    const sourceNode = declaration ?? fallbackNode;
    const memberType = checker.getTypeOfSymbolAtLocation(symbol, sourceNode);
    const signatures = memberType.getCallSignatures();
    const path = `${basePath}.${name}`;

    if (signatures.length > 0) {
      const signature = signatures[0]!;
      const signatureDeclaration = signature.getDeclaration();
      const signatureNode = signatureDeclaration ?? sourceNode;
      const parameters = getSignatureParameterDocs(
        checker,
        signature,
        signatureNode,
      );
      const rawReturn = formatResolvedType(
        checker,
        signature.getReturnType(),
        signatureNode,
      );
      const returnDoc = parseEffectReturn(
        rawReturn,
        signatureDeclaration?.type,
        signatureNode.getSourceFile(),
      );

      for (const parameter of parameters) {
        collectTypeNameTokens(parameter.type, typeReferences);
      }
      for (const parameter of signatureDeclaration?.parameters ?? []) {
        if (parameter.type !== undefined) {
          collectTaggedTypeReferences(
            checker,
            parameter.type,
            typeReferences,
          );
        }
      }
      collectTypeNameTokens(rawReturn, typeReferences);

      docs.push({
        path,
        name,
        kind: "method",
        summary: getSymbolSummary(
          checker,
          symbol,
          declaration,
          signatureDeclaration,
        ),
        signature: methodSignature(path, parameters, returnDoc),
        parameters,
        returnDoc,
        ...getSourceInfo(options, git, sourceNode),
      });
      continue;
    }

    const rawType = formatResolvedType(checker, memberType, sourceNode);
    const returnDoc = parseEffectReturn(
      rawType,
      declaration !== null && ts.isPropertySignature(declaration)
        ? declaration.type
        : undefined,
      sourceNode.getSourceFile(),
    );
    const nestedSymbols = checker
      .getPropertiesOfType(memberType)
      .filter((nested) => isDocumentableSymbol(options, nested));
    if (returnDoc.result === null && nestedSymbols.length > 0) {
      docs.push(
        ...collectMembersFromType(
          checker,
          options,
          git,
          memberType,
          sourceNode,
          path,
          typeReferences,
          nextSeen,
        ),
      );
      continue;
    }

    collectTypeNameTokens(rawType, typeReferences);
    docs.push({
      path,
      name,
      kind: returnDoc.result === null ? "value" : "effect",
      summary: getSymbolSummary(checker, symbol, declaration),
      signature: `${path}: ${rawType}`,
      parameters: [],
      returnDoc,
      ...getSourceInfo(options, git, sourceNode),
    });
  }

  return docs.sort((left, right) => left.path.localeCompare(right.path));
};

const collectApiGroups = (
  checker: ts.TypeChecker,
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  options: CliOptions,
  git: GitSourceInfo | null,
): {
  readonly runtimeHelpers: readonly MemberDoc[];
  readonly namespaces: readonly ApiNamespace[];
  readonly groups: readonly ApiGroup[];
  readonly typeReferences: readonly string[];
} => {
  const scriptApi = getInterface(declarations, "ScriptApi");
  const scriptRuntimeApi = getInterface(declarations, "ScriptRuntimeApi");
  const helperTypeReferences = new Set<string>();
  const groups: ApiGroup[] = [];

  const runtimeHelpers = collectMembersFromInterface(
    checker,
    declarations,
    options,
    git,
    scriptRuntimeApi,
    "script",
    helperTypeReferences,
  );

  const namespaces: ApiNamespace[] = [];
  for (const member of scriptApi.members) {
    if (!ts.isPropertySignature(member)) {
      continue;
    }

    const name = getPropertyName(member.name);
    if (name === null) {
      continue;
    }

    const typeReferences = new Set<string>();
    const shapeType = checker.getTypeAtLocation(member.type ?? member);
    const members = collectMembersFromType(
      checker,
      options,
      git,
      shapeType,
      member,
      `api.${name}`,
      typeReferences,
    );
    if (members.length === 0) {
      continue;
    }

    const id = `api/${kebabCase(name)}`;
    namespaces.push({
      name,
      slug: kebabCase(name),
      href: `/scripting/api/${kebabCase(name)}/`,
      sourceType: formatType(checker, member.type),
    });
    const summary = getSummary(member);
    groups.push({
      id,
      title: `api.${name}`,
      label: titleCase(name),
      description: summary || "",
      summary,
      members,
      typeReferences: Array.from(typeReferences),
    });
  }

  const scriptFeaturesApi = getInterface(declarations, "ScriptFeaturesApi");
  for (const member of scriptFeaturesApi.members) {
    if (!ts.isPropertySignature(member)) {
      continue;
    }

    const name = getPropertyName(member.name);
    if (name === null) {
      continue;
    }

    const typeReferences = new Set<string>();
    const members = collectMembersFromType(
      checker,
      options,
      git,
      checker.getTypeAtLocation(member.type ?? member),
      member,
      `features.${name}`,
      typeReferences,
    );
    if (members.length === 0) {
      continue;
    }

    const summary = getSummary(member) || "";
    groups.push({
      id: `features/${kebabCase(name)}`,
      title: `features.${name}`,
      label: titleCase(name),
      description: summary,
      summary,
      members,
      typeReferences: Array.from(typeReferences),
    });
  }

  const documentedTypeReferences = new Set([
    ...helperTypeReferences,
    ...groups.flatMap((group) => group.typeReferences),
  ]);
  for (const member of [
    ...runtimeHelpers,
    ...groups.flatMap((group) => group.members),
  ]) {
    for (const parameter of member.parameters) {
      collectTypeNameTokens(parameter.type, documentedTypeReferences);
    }
    collectTypeNameTokens(member.returnDoc.raw, documentedTypeReferences);
    if (member.returnDoc.result !== null) {
      collectTypeNameTokens(member.returnDoc.result, documentedTypeReferences);
    }
    if (member.returnDoc.error !== null) {
      collectTypeNameTokens(member.returnDoc.error, documentedTypeReferences);
    }
  }

  return {
    runtimeHelpers,
    namespaces: namespaces.sort((a, b) => a.name.localeCompare(b.name)),
    groups: groups.sort((a, b) => a.id.localeCompare(b.id)),
    typeReferences: Array.from(documentedTypeReferences),
  };
};

const walkReflection = (
  reflection: Reflection,
  visit: (reflection: Reflection) => void,
): void => {
  visit(reflection);
  if (!reflection.isContainer()) {
    return;
  }
  for (const child of reflection.children ?? []) {
    walkReflection(child, visit);
  }
};

const reflectionSource = (
  options: CliOptions,
  git: GitSourceInfo | null,
  reflection: DeclarationReflection | SignatureReflection,
): SourceInfo => {
  const source = reflection.sources?.[0];
  if (source === undefined) {
    return {
      sourcePath: "unknown",
      sourceLine: 1,
      sourceUrl: null,
    };
  }

  const sourceFileName = source.fullFileName || source.fileName;
  const fullPath = isAbsolute(sourceFileName)
    ? sourceFileName
    : resolve(options.repoRoot, sourceFileName);
  const sourcePath = relative(options.repoRoot, fullPath).replaceAll("\\", "/");
  return {
    sourcePath,
    sourceLine: source.line,
    sourceUrl: buildSourceUrl(git, options.repoRoot, fullPath, source.line),
  };
};

const commentText = (reflection: Reflection | undefined): string => {
  const parts = reflection?.comment?.summary ?? [];
  return parts
    .map((part) => ("text" in part ? part.text : ""))
    .join("")
    .trim();
};

const typeToString = (type: SomeType | undefined): string =>
  type?.toString() ?? "unknown";

const typeParametersText = (
  typeParameters: DeclarationReflection["typeParameters"],
): string =>
  typeParameters === undefined || typeParameters.length === 0
    ? ""
    : `<${typeParameters.map((parameter) => parameter.name).join(", ")}>`;

const typedocKindName = (kind: ReflectionKind): string =>
  ReflectionKind.singularString(kind).toString().toLowerCase();

const isDocumentableTypeReflection = (
  reflection: Reflection,
): reflection is DeclarationReflection =>
  reflection.isDeclaration() &&
  (reflection.kind === ReflectionKind.Class ||
    reflection.kind === ReflectionKind.Interface ||
    reflection.kind === ReflectionKind.TypeAlias ||
    reflection.kind === ReflectionKind.Enum);

const reflectionRank = (reflection: DeclarationReflection): number => {
  const sourcePenalty = reflection.sources?.some((source) =>
    source.fullFileName.includes("/dist/"),
  )
    ? 10
    : 0;

  switch (reflection.kind) {
    case ReflectionKind.Class:
      return sourcePenalty;
    case ReflectionKind.Interface:
      return sourcePenalty + 1;
    case ReflectionKind.TypeAlias:
      return sourcePenalty + 2;
    case ReflectionKind.Enum:
      return sourcePenalty + 3;
    default:
      return sourcePenalty + 4;
  }
};

const isDocSourceReflection = (
  options: CliOptions,
  reflection: DeclarationReflection,
): boolean => {
  const source = reflection.sources?.[0];
  if (source === undefined) {
    return false;
  }

  const sourceFileName = source.fullFileName || source.fileName;
  const fullPath = isAbsolute(sourceFileName)
    ? sourceFileName
    : resolve(options.repoRoot, sourceFileName);
  if (!isInsideRepo(options.repoRoot, fullPath)) {
    return false;
  }

  const relativePath = relative(options.repoRoot, fullPath).replaceAll(
    "\\",
    "/",
  );
  return (
    relativePath.startsWith("app/src/shared/") ||
    relativePath.startsWith("app/src/renderer/apps/game/") ||
    relativePath.startsWith("packages/core/src/") ||
    relativePath.startsWith("packages/game/src/")
  );
};

const buildTypeReflectionMap = (
  options: CliOptions,
  project: ProjectReflection,
): ReadonlyMap<string, DeclarationReflection> => {
  const reflections = new Map<string, DeclarationReflection>();
  walkReflection(project, (reflection) => {
    if (
      !isDocumentableTypeReflection(reflection) ||
      !isDocSourceReflection(options, reflection)
    ) {
      return;
    }

    const current = reflections.get(reflection.name);
    if (
      current === undefined ||
      reflectionRank(reflection) < reflectionRank(current)
    ) {
      reflections.set(reflection.name, reflection);
    }
  });
  return reflections;
};

const collectTypeNameTokens = (text: string, output: Set<string>): void => {
  for (const match of text.matchAll(/\b[A-Za-z_$][A-Za-z0-9_$]*\b/g)) {
    const token = match[0];
    if (!BUILTIN_TYPE_NAMES.has(token) && !TYPE_REFERENCE_WRAPPERS.has(token)) {
      output.add(token);
    }
  }
};

const getInheritedFrom = (reflection: DeclarationReflection): string | null => {
  const inherited = reflection.inheritedFrom;
  if (inherited === undefined) {
    return null;
  }

  const parent = inherited.reflection?.parent;
  if (parent !== undefined && parent.name !== reflection.parent?.name) {
    return parent.name;
  }

  const qualified = inherited.qualifiedName;
  const parts = qualified.split(".");
  return parts.length > 1 ? (parts[parts.length - 2] ?? null) : inherited.name;
};

const methodSignatureText = (
  method: DeclarationReflection,
  signature: SignatureReflection,
): string => {
  const typeParameters =
    signature.typeParameters === undefined ||
    signature.typeParameters.length === 0
      ? ""
      : `<${signature.typeParameters.map((parameter) => parameter.name).join(", ")}>`;
  const parameters = (signature.parameters ?? [])
    .map((parameter) => {
      const rest = parameter.flags.isRest ? "..." : "";
      const optional = parameter.flags.isOptional ? "?" : "";
      return `${rest}${parameter.name}${optional}: ${typeToString(parameter.type)}`;
    })
    .join(", ");
  return `${method.name}${typeParameters}(${parameters}): ${typeToString(
    signature.type,
  )}`;
};

const declarationDefinition = (reflection: DeclarationReflection): string => {
  const typeParameters = typeParametersText(reflection.typeParameters);
  switch (reflection.kind) {
    case ReflectionKind.Class: {
      const extended = reflection.extendedTypes?.[0];
      return `class ${reflection.name}${typeParameters}${
        extended === undefined ? "" : ` extends ${extended.toString()}`
      }`;
    }
    case ReflectionKind.Interface:
      return `interface ${reflection.name}${typeParameters}`;
    case ReflectionKind.TypeAlias:
      return `type ${reflection.name}${typeParameters} = ${typeToString(
        reflection.type,
      )}`;
    case ReflectionKind.Enum:
      return `enum ${reflection.name}`;
    default:
      return `${typedocKindName(reflection.kind)} ${reflection.name}`;
  }
};

const isVisibleInstanceMember = (reflection: DeclarationReflection): boolean =>
  !reflection.flags.isPrivate &&
  !reflection.flags.isProtected &&
  !reflection.flags.isStatic;

const getDirectAliasTarget = (
  reflection: DeclarationReflection,
  reflections: ReadonlyMap<string, DeclarationReflection>,
): DeclarationReflection | null => {
  if (reflection.kind !== ReflectionKind.TypeAlias) {
    return null;
  }

  const rendered = typeToString(reflection.type);
  const match = /^([A-Za-z_$][A-Za-z0-9_$]*)(?:<.*>)?$/.exec(rendered);
  return match?.[1] === undefined
    ? null
    : (reflections.get(match[1]) ?? null);
};

const buildReferencedTypeDoc = (
  options: CliOptions,
  git: GitSourceInfo | null,
  reflection: DeclarationReflection,
  reflections: ReadonlyMap<string, DeclarationReflection>,
  seen = new Set<string>(),
): ReferencedTypeDoc => {
  const properties: TypeMemberDoc[] = [];
  const methods: TypeMethodDoc[] = [];

  for (const child of reflection.children ?? []) {
    if (!isVisibleInstanceMember(child)) {
      continue;
    }

    if (
      child.kind === ReflectionKind.Property ||
      child.kind === ReflectionKind.Accessor ||
      child.kind === ReflectionKind.EnumMember
    ) {
      const getSignature = child.getSignature;
      properties.push({
        name: child.name,
        type: typeToString(getSignature?.type ?? child.type),
        summary: commentText(getSignature ?? child),
        readonly:
          child.flags.isReadonly || child.kind === ReflectionKind.Accessor,
        optional: child.flags.isOptional,
        inheritedFrom: getInheritedFrom(child),
        ...reflectionSource(options, git, getSignature ?? child),
      });
      continue;
    }

    if (child.kind === ReflectionKind.Method) {
      for (const signature of child.signatures ?? []) {
        methods.push({
          name: child.name,
          signature: methodSignatureText(child, signature),
          summary: commentText(signature) || commentText(child),
          inheritedFrom: getInheritedFrom(child),
          ...reflectionSource(options, git, signature),
        });
      }
    }
  }

  const aliasTarget = getDirectAliasTarget(reflection, reflections);
  if (
    aliasTarget !== null &&
    !seen.has(aliasTarget.name) &&
    properties.length === 0 &&
    methods.length === 0
  ) {
    const nextSeen = new Set(seen);
    nextSeen.add(reflection.name);
    const target = buildReferencedTypeDoc(
      options,
      git,
      aliasTarget,
      reflections,
      nextSeen,
    );
    properties.push(
      ...target.properties.map((property) => ({
        ...property,
        inheritedFrom: property.inheritedFrom ?? aliasTarget.name,
      })),
    );
    methods.push(
      ...target.methods.map((method) => ({
        ...method,
        inheritedFrom: method.inheritedFrom ?? aliasTarget.name,
      })),
    );
  }

  const summary = commentText(reflection);

  return {
    name: reflection.name,
    slug: kebabCase(reflection.name),
    kind: typedocKindName(reflection.kind),
    summary:
      summary ||
      (aliasTarget === null ? "" : `Alias of ${aliasTarget.name}.`),
    aliasOf: aliasTarget?.name ?? null,
    definition: declarationDefinition(reflection),
    properties: properties.sort((a, b) => a.name.localeCompare(b.name)),
    methods: methods.sort((a, b) => a.name.localeCompare(b.name)),
    ...reflectionSource(options, git, reflection),
  };
};

const buildAstReferencedTypeDoc = (
  checker: ts.TypeChecker,
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  options: CliOptions,
  git: GitSourceInfo | null,
  declaration: ts.InterfaceDeclaration | ts.TypeAliasDeclaration,
  seen = new Set<string>(),
): ReferencedTypeDoc => {
  const name = declaration.name.text;
  const properties: TypeMemberDoc[] = [];
  const methods: TypeMethodDoc[] = [];
  const nextSeen = new Set(seen);
  nextSeen.add(name);

  const inheritMembers = (
    target: ts.InterfaceDeclaration | ts.TypeAliasDeclaration,
    inheritedFrom: string,
  ): void => {
    if (nextSeen.has(target.name.text)) {
      return;
    }
    const inherited = buildAstReferencedTypeDoc(
      checker,
      declarations,
      options,
      git,
      target,
      nextSeen,
    );
    properties.push(
      ...inherited.properties.map((property) => ({
        ...property,
        inheritedFrom: property.inheritedFrom ?? inheritedFrom,
      })),
    );
    methods.push(
      ...inherited.methods.map((method) => ({
        ...method,
        inheritedFrom: method.inheritedFrom ?? inheritedFrom,
      })),
    );
  };

  let aliasOf: string | null = null;
  if (ts.isTypeAliasDeclaration(declaration)) {
    const target = parseTypeReference(declaration.type);
    const targetDeclaration =
      target === null ? undefined : declarations.get(target.unqualifiedName);
    if (targetDeclaration !== undefined) {
      aliasOf = targetDeclaration.name.text;
      inheritMembers(targetDeclaration, targetDeclaration.name.text);
    } else if (
      ts.isTypeQueryNode(declaration.type) &&
      ts.isQualifiedName(declaration.type.exprName) &&
      declaration.type.exprName.right.text === "Type" &&
      ts
        .getJSDocTags(declaration)
        .some((tag) => tag.tagName.text === "scriptingExpandSchema")
    ) {
      const resolved = checker.getTypeAtLocation(declaration);
      for (const symbol of checker.getPropertiesOfType(resolved)) {
        const symbolDeclaration = getSymbolDeclaration(symbol);
        if (
          symbolDeclaration === null ||
          !isInsideRepo(
            options.repoRoot,
            symbolDeclaration.getSourceFile().fileName,
          ) ||
          symbolDeclaration.getSourceFile().fileName.includes(
            "/node_modules/",
          )
        ) {
          continue;
        }
        const sourceNode = symbolDeclaration;
        properties.push({
          name: symbol.name,
          type: formatResolvedType(
            checker,
            checker.getTypeOfSymbolAtLocation(symbol, sourceNode),
            sourceNode,
          ),
          summary: getSymbolSummary(
            checker,
            symbol,
            symbolDeclaration,
          ),
          readonly: true,
          optional: (symbol.flags & ts.SymbolFlags.Optional) !== 0,
          inheritedFrom: null,
          ...getSourceInfo(options, git, sourceNode),
        });
      }
    }
  } else {
    for (const clause of declaration.heritageClauses ?? []) {
      if (clause.token !== ts.SyntaxKind.ExtendsKeyword) {
        continue;
      }
      for (const heritage of clause.types) {
        const reference = parseHeritageReference(heritage);
        const inherited =
          reference === null
            ? undefined
            : declarations.get(reference.unqualifiedName);
        if (inherited !== undefined) {
          inheritMembers(inherited, inherited.name.text);
        }
      }
    }

    for (const member of declaration.members) {
      const memberName =
        (ts.isPropertySignature(member) || ts.isMethodSignature(member)) &&
        member.name !== undefined
          ? getPropertyName(member.name)
          : null;
      if (memberName === null) {
        continue;
      }

      if (ts.isPropertySignature(member)) {
        properties.push({
          name: memberName,
          type: formatType(checker, member.type),
          summary: getSummary(member),
          readonly:
            member.modifiers?.some(
              (modifier) => modifier.kind === ts.SyntaxKind.ReadonlyKeyword,
            ) ?? false,
          optional: member.questionToken !== undefined,
          inheritedFrom: null,
          ...getSourceInfo(options, git, member),
        });
        continue;
      }

      if (!ts.isMethodSignature(member)) {
        continue;
      }

      const parameters = getParameterDocs(checker, member);
      const returnDoc = getReturnDoc(checker, member);
      methods.push({
        name: memberName,
        signature: methodSignature(memberName, parameters, returnDoc),
        summary: getSummary(member),
        inheritedFrom: null,
        ...getSourceInfo(options, git, member),
      });
    }
  }

  const typeParameters =
    declaration.typeParameters === undefined ||
    declaration.typeParameters.length === 0
      ? ""
      : `<${declaration.typeParameters
          .map((parameter) => parameter.name.text)
          .join(", ")}>`;
  const summary = getSummary(declaration);
  return {
    name,
    slug: kebabCase(name),
    kind: ts.isInterfaceDeclaration(declaration) ? "interface" : "type alias",
    summary: summary || (aliasOf === null ? "" : `Alias of ${aliasOf}.`),
    aliasOf,
    definition: ts.isInterfaceDeclaration(declaration)
      ? `interface ${name}${typeParameters}`
      : `type ${name}${typeParameters} = ${typeText(
          declaration.type,
          declaration.getSourceFile(),
        )}`,
    properties: properties.sort((left, right) =>
      left.name.localeCompare(right.name),
    ),
    methods: methods.sort((left, right) => left.name.localeCompare(right.name)),
    ...getSourceInfo(options, git, declaration),
  };
};

const collectReferencedTypeDocs = (
  checker: ts.TypeChecker,
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  options: CliOptions,
  git: GitSourceInfo | null,
  project: ProjectReflection,
  rootReferences: ReadonlySet<string>,
): ReferencedTypeDoc[] => {
  const reflections = buildTypeReflectionMap(options, project);
  const pending = Array.from(rootReferences);
  const seen = new Set<string>();
  const docs: ReferencedTypeDoc[] = [];

  for (let index = 0; index < pending.length; index += 1) {
    const name = pending[index];
    if (
      name === undefined ||
      seen.has(name) ||
      BUILTIN_TYPE_NAMES.has(name) ||
      TYPE_REFERENCE_WRAPPERS.has(name)
    ) {
      continue;
    }
    seen.add(name);

    const reflection = reflections.get(name);
    const declaration = declarations.get(name);
    if (reflection === undefined && declaration === undefined) {
      continue;
    }
    if (
      declaration !== undefined &&
      ts
        .getJSDocTags(declaration)
        .some((tag) => tag.tagName.text === "internal")
    ) {
      continue;
    }

    const doc =
      declaration !== undefined && ts.isTypeAliasDeclaration(declaration)
        ? buildAstReferencedTypeDoc(
            checker,
            declarations,
            options,
            git,
            declaration,
          )
        : reflection !== undefined
          ? buildReferencedTypeDoc(options, git, reflection, reflections)
          : buildAstReferencedTypeDoc(
              checker,
              declarations,
              options,
              git,
              declaration!,
            );
    docs.push(doc);

    const nestedReferences = new Set<string>();
    collectTypeNameTokens(doc.definition, nestedReferences);
    for (const property of doc.properties) {
      collectTypeNameTokens(property.type, nestedReferences);
    }
    for (const method of doc.methods) {
      collectTypeNameTokens(method.signature, nestedReferences);
    }
    for (const nested of nestedReferences) {
      if (!seen.has(nested) && !pending.includes(nested)) {
        pending.push(nested);
      }
    }
  }

  return docs.sort((a, b) => a.name.localeCompare(b.name));
};

const typedocEntryPoints = (
  program: ts.Program,
  options: CliOptions,
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  typeReferences: ReadonlySet<string>,
): readonly string[] => {
  const entryPoints = new Set<string>();
  const addSourceFile = (fileName: string): void => {
    if (
      fileName.includes("/node_modules/") ||
      fileName.endsWith(".test.ts") ||
      !isInsideRepo(options.repoRoot, fileName)
    ) {
      return;
    }
    entryPoints.add(relative(options.repoRoot, fileName).replaceAll("\\", "/"));
  };

  addSourceFile(options.sourceFile);
  for (const sourceFile of program.getSourceFiles()) {
    const relativePath = relative(options.repoRoot, sourceFile.fileName).replaceAll(
      "\\",
      "/",
    );
    if (
      relativePath.startsWith("app/src/shared/") ||
      relativePath.startsWith("app/src/renderer/apps/game/") ||
      relativePath.startsWith("packages/core/src/") ||
      relativePath.startsWith("packages/game/src/")
    ) {
      addSourceFile(sourceFile.fileName);
    }
  }
  for (const reference of typeReferences) {
    const declaration = declarations.get(reference);
    if (declaration !== undefined) {
      addSourceFile(declaration.getSourceFile().fileName);
    }
  }
  return Array.from(entryPoints).sort();
};

const createTypeDocProject = (
  program: ts.Program,
  options: CliOptions,
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  typeReferences: ReadonlySet<string>,
): Effect.Effect<ProjectReflection, DocgenError> =>
  Effect.tryPromise({
    try: async () => {
      const app = await Application.bootstrap(
        {
          entryPoints: [
            ...typedocEntryPoints(
              program,
              options,
              declarations,
              typeReferences,
            ),
          ],
          excludeExternals: false,
          excludePrivate: true,
          excludeProtected: true,
          skipErrorChecking: true,
          logLevel: "Error",
          compilerOptions: {
            target: "esnext",
            module: "esnext",
            moduleResolution: "bundler",
            lib: ["esnext", "dom", "dom.iterable"],
            strict: true,
            skipLibCheck: true,
            jsx: "react-jsx",
            jsxImportSource: "solid-js",
            resolveJsonModule: true,
            esModuleInterop: true,
            allowSyntheticDefaultImports: true,
            noEmit: true,
            baseUrl: ".",
            paths: DOCGEN_COMPILER_PATHS,
          },
        },
        [],
      );
      const project = await app.convert();
      if (project === undefined) {
        return fail("TypeDoc was unable to convert scripting API entry points");
      }
      return project;
    },
    catch: (cause) =>
      cause instanceof DocgenError
        ? cause
        : new DocgenError("Failed to create TypeDoc project", { cause }),
  });

const renderTypeExpression = (
  type: string,
  typeLinks: ReadonlyMap<string, TypeLink>,
): string => {
  let rendered = "";
  for (let index = 0; index < type.length; ) {
    const rest = type.slice(index);
    const match = /^[A-Za-z_$][A-Za-z0-9_$]*/.exec(rest);
    if (match?.[0]) {
      const token = match[0];
      const link = typeLinks.get(token);
      rendered +=
        link === undefined ? renderCode(token) : renderTypeLink(token, link);
      index += token.length;
      continue;
    }

    const char = type[index] ?? "";
    if (char === "|") {
      rendered += "\\|";
    } else if (char === "<") {
      rendered += "&lt;";
    } else if (char === ">") {
      rendered += "&gt;";
    } else {
      rendered += escapeTableCell(char);
    }
    index += 1;
  }
  return rendered;
};

const buildTypeLinks = (
  types: readonly ReferencedTypeDoc[],
  prefix: string,
): ReadonlyMap<string, TypeLink> =>
  new Map(
    types.map((type) => [
      type.name,
      {
        href: `${prefix}${type.slug}/`,
        slug: type.slug,
      },
    ]),
  );

const renderTypeLink = (name: string, link: TypeLink): string =>
  `<a href="${escapeHtml(link.href)}" data-script-type="${escapeHtml(link.slug)}">${renderHtmlCode(name)}</a>`;

const renderSourceLink = (
  source: SourceInfo,
  className = "source-reference__link",
): string => {
  const sourceReference = `${source.sourcePath}:${source.sourceLine}`;
  const isHeadingLink = className === "source-reference__heading-link";
  const headingStyle = isHeadingLink
    ? ` style="float: right; display: inline-flex; align-items: center; justify-content: center; margin-block: -0.125rem; margin-inline-start: 0.5rem; border-radius: var(--radius-sm); text-decoration: none;"`
    : "";
  const headingAttributes = isHeadingLink
    ? ` tabindex="-1" aria-hidden="true"`
    : ` aria-label="Open source: ${escapeHtml(sourceReference)}"`;
  const icon = `<svg class="source-reference__icon" width="16" height="16" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m18 16 4-4-4-4"></path><path d="m6 8-4 4 4 4"></path><path d="m14.5 4-5 16"></path></svg>`;
  return source.sourceUrl
    ? `<a class="${className}"${headingStyle} href="${escapeHtml(source.sourceUrl)}"${headingAttributes} title="Open source: ${escapeHtml(sourceReference)}" target="_blank" rel="noreferrer">${icon}</a>`
    : "";
};

const renderHeadingSourceLink = (source: SourceInfo): string => {
  const sourceLink = renderSourceLink(source, "source-reference__heading-link");
  return sourceLink === "" ? "" : ` ${sourceLink}`;
};

const renderSource = (source: SourceInfo): string => {
  const sourceReference = `${source.sourcePath}:${source.sourceLine}`;
  const sourcePath = `<code class="source-reference__path">${escapeHtml(sourceReference)}</code>`;

  return `<p class="source-reference"><span class="source-reference__label">Source</span>${sourcePath}${renderSourceLink(source)}</p>`;
};

const GENERATED_MEMBER_SUMMARIES: Readonly<Record<string, string>> = {
  "api.events.on":
    "Runs a handler for every matching event until the script stops or the yielded disposer is called.",
  "api.events.once": "Waits for the next matching event.",
  "api.events.stream":
    "Creates a lazy Effect Stream of matching events for advanced stream composition.",
};

const renderMember = (
  lines: string[],
  member: MemberDoc,
  typeLinks: ReadonlyMap<string, TypeLink>,
) => {
  lines.push(`<a id="${memberAnchor(member.path)}"></a>`, "");
  lines.push(
    `### \`${member.path}${member.kind === "method" ? "()" : ""}\`${renderHeadingSourceLink(member)}`,
    "",
  );

  const summary = member.summary || GENERATED_MEMBER_SUMMARIES[member.path] || "";
  if (summary !== "") {
    lines.push(summary, "");
  }

  if (member.sourceUrl === null) {
    lines.push(renderSource(member), "");
  }

  lines.push("```ts", member.signature, "```", "");

  if (member.parameters.length > 0) {
    lines.push(
      "| Name | Type | Required | Description |",
      "| --- | --- | --- | --- |",
    );
    for (const parameter of member.parameters) {
      lines.push(
        `| ${renderCode(`${parameter.rest ? "..." : ""}${parameter.name}`)} | ${renderTypeExpression(parameter.type, typeLinks)} | ${renderBooleanMark(parameter.required)} | ${escapeTableCell(parameter.description)} |`,
      );
    }
    lines.push("");
  }

  if (member.returnDoc.result !== null) {
    lines.push(
      `**Yields:** ${renderTypeExpression(member.returnDoc.result, typeLinks)}`,
      "",
      `**Errors:** ${renderTypeExpression(member.returnDoc.error ?? "never", typeLinks)}`,
      "",
    );
  } else {
    lines.push(
      `**Returns:** ${renderTypeExpression(member.returnDoc.raw, typeLinks)}`,
      "",
    );
  }
};

const typeMemberAnchor = (kind: "property" | "method", name: string): string =>
  `${kind}-${anchorSlug(name)}`;

const renderTypeProperty = (lines: string[], property: TypeMemberDoc) => {
  lines.push(
    `<a id="${typeMemberAnchor("property", property.name)}"></a>`,
    "",
    `### \`${property.name}\`${renderHeadingSourceLink(property)}`,
    "",
  );

  if (property.summary !== "") {
    lines.push(property.summary, "");
  }

  if (property.sourceUrl === null) {
    lines.push(renderSource(property), "");
  }

  lines.push("```ts");
  lines.push(
    `${property.readonly ? "readonly " : ""}${property.name}${
      property.optional ? "?" : ""
    }: ${property.type}`,
  );
  lines.push("```", "");
};

const renderTypeMethod = (lines: string[], method: TypeMethodDoc) => {
  lines.push(
    `<a id="${typeMemberAnchor("method", method.name)}"></a>`,
    "",
    `### \`${method.name}()\`${renderHeadingSourceLink(method)}`,
    "",
  );

  if (method.summary !== "") {
    lines.push(method.summary, "");
  }

  if (method.sourceUrl === null) {
    lines.push(renderSource(method), "");
  }

  lines.push("```ts", method.signature, "```", "");
};

const frontmatter = (
  title: string,
  description: string,
  label?: string,
  extraFields = "",
): string => {
  const yamlString = (value: string): string => JSON.stringify(value);
  const sidebar =
    label === undefined ? "" : `sidebar:\n  label: ${yamlString(label)}\n`;
  return `---\ntitle: ${yamlString(title)}\ndescription: ${yamlString(description)}\n${sidebar}${extraFields}tableOfContents:\n  minHeadingLevel: 2\n  maxHeadingLevel: 3\n---`;
};

const finalizeMarkdown = (lines: readonly string[]): string =>
  `${lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;

const renderIndex = (_namespaces: readonly ApiNamespace[]): string => {
  const lines = [
    frontmatter("Scripting API", "", "Overview"),
    "",
    GENERATED_HEADER,
    "",
    'Scripts export a CommonJS generator function and import script APIs from `require("lucent")`.',
    "",
    "```js",
    'const { features, script, api } = require("lucent")',
    "",
    "module.exports = function* run() {",
    '  yield* script.log("started")',
    '  yield* script.options.setRoomPolicy({ kind: "random-private" })',
    '  yield* api.player.joinMap("battleon")',
    "  const me = yield* api.players.getMe()",
    "  if (me !== null) yield* script.log(`Logged in as ${me.username}`)",
    "}",
    "```",
    "",
    "## Runtime Import",
    "",
    '`require("lucent")` returns the script API facade. The declaration file types this import directly, so `features`, `script`, and `api` get autocomplete without a JSDoc parameter annotation.',
    "",
    "| Member | Description |",
    "| --- | --- |",
    "| [`api`](/scripting/api/) | Interact with the game. |",
    "| [`script`](/scripting/script/) | Manage the running script. |",
    "| [`features`](/scripting/features/) | Use feature controls. |",
    "| [`imports`](/scripting/imports/) | Import supported script modules. |",
    "",
    "## Reference",
    "",
    "| Page | Description |",
    "| --- | --- |",
    "| [`types`](/scripting/types/) | Referenced scripting data types and public class surfaces. |",
    "",
    "## Editor Integration",
    "",
    "Download the generated declaration file [`script-api.d.ts`](/script-api.d.ts) and place it beside your scripts. You can rename it if your `jsconfig.json` includes the renamed declaration file. It declares the supported imports, so `require(\"lucent\")` and `require(\"effect\")` are typed automatically.",
    "",
    "```js",
    '/// <reference path="./script-api.d.ts" />',
    "",
    'const { features, script, api } = require("lucent")',
    "",
    "module.exports = function* run() {",
    '  yield* script.options.setRoomPolicy({ kind: "random-private" })',
    '  yield* api.player.joinMap("battleon")',
    "  const me = yield* api.players.getMe()",
    "  if (me !== null) yield* script.log(me.username)",
    "}",
    "```",
    "",
    "For a folder full of scripts, put the declaration file beside them and add `jsconfig.json` to the folder. Keep `checkJs` off to get autocomplete without diagnostics noise, and add `// @ts-check` only to files where you want type errors reported.",
    "",
    "```json",
    "{",
    '  "compilerOptions": {',
    '    "target": "ES2020",',
    '    "lib": ["ES2020", "DOM"],',
    '    "checkJs": false,',
    '    "skipLibCheck": true',
    "  },",
    '  "include": ["**/*.js", "*.d.ts"]',
    "}",
    "```",
  ];
  return finalizeMarkdown(lines);
};

const renderImportsOverview = (): string => {
  const lines = [
    frontmatter(
      "Script Imports",
      "Supported modules available to scripts.",
      "Imports",
    ),
    "",
    GENERATED_HEADER,
    "",
    "Scripts can import a small set of supported modules. For now, other imports are not available.",
    "",
    "### `require(\"lucent\")`",
    "",
    "`require(\"lucent\")` returns the active script API facade.",
    "",
    "```js",
    'const { features, script, api } = require("lucent")',
    "",
    "module.exports = function* run() {",
    '  yield* api.player.joinMap("battleon")',
    '  yield* api.wait.forMapLoaded("battleon", { timeout: "10 seconds" })',
    '  yield* script.log("ready")',
    "}",
    "```",
    "",
    "Feature controls remain grouped under `features`.",
    "",
    "```js",
    'const { features, script, api } = require("lucent")',
    "const { autoZone } = features",
    "",
    "module.exports = function* run() {",
    '  yield* autoZone.setMap("ultradage")',
    "  yield* autoZone.enable()",
    "}",
    "```",
    "",
    "### `require(\"effect\")`",
    "",
    "`require(\"effect\")` returns the exposed Effect modules available for use.",
    "",
    "```js",
    'const { features, script, api } = require("lucent")',
    'const { Effect, pipe } = require("effect")',
    "",
    "module.exports = function* run() {",
    "  const me = yield* api.players.getMe()",
    "  if (me !== null) {",
    "    yield* script.log(me.username)",
    "  }",
    "}",
    "```",
    "",
    "The curated import currently exposes [`Effect`](https://effect-ts.github.io/effect/effect/Effect.ts.html), [`Option`](https://effect-ts.github.io/effect/effect/Option.ts.html), [`Duration`](https://effect-ts.github.io/effect/effect/Duration.ts.html), and [`pipe`](https://effect-ts.github.io/effect/effect/Function.ts.html).",
    "",
    "When a script yields an Effect, the script runner owns its execution and cancellation. Background work that is started manually, such as detached fibers or timers, should still be cleaned up by the script.",
  ];

  return finalizeMarkdown(lines);
};

const renderApiOverview = (namespaces: readonly ApiNamespace[]): string => {
  const lines = [
    frontmatter(
      "Game API",
      "Gameplay and game-state APIs exposed to scripts.",
      "API",
    ),
    "",
    GENERATED_HEADER,
    "",
    "`api` gives scripts access to gameplay and game-state namespaces.",
    "",
    "## Namespaces",
    "",
    "| Namespace | Description |",
    "| --- | --- |",
    ...namespaces.map(
      (namespace) =>
        `| [\`api.${namespace.name}\`](${namespace.href}) | ${titleCase(
          namespace.name,
        )} APIs. |`,
    ),
  ];

  return finalizeMarkdown(lines);
};

const renderFeaturesOverview = (groups: readonly ApiGroup[]): string => {
  const featureGroups = groups.filter((group) =>
    group.id.startsWith("features/"),
  );
  const lines = [
    frontmatter(
      "Features",
      "Higher-level gameplay automation features exposed to scripts.",
      "Features",
    ),
    "",
    GENERATED_HEADER,
    "",
    "`features` gives scripts access to higher-level automation controls that sit above the lower-level game API namespaces.",
    "",
    "## Namespaces",
    "",
    "| Namespace | Description |",
    "| --- | --- |",
    ...featureGroups.map((group) => {
      const description =
        group.description || `${group.label} feature controls.`;
      return `| [\`${group.title}\`](/scripting/${group.id}/) | ${escapeTableCell(description)} |`;
    }),
  ];

  return finalizeMarkdown(lines);
};

const renderScriptOverview = (
  helpers: readonly MemberDoc[],
  typeLinks: ReadonlyMap<string, TypeLink>,
): string => {
  const lines = [
    frontmatter(
      "Script",
      "Current script lifecycle and diagnostics APIs.",
      "Script",
    ),
    "",
    GENERATED_HEADER,
    "",
    "`script` gives scripts access to the current script's lifecycle, diagnostics, and session-backed options.",
    "",
    "## Members",
    "",
  ];

  for (const helper of helpers) {
    renderMember(lines, helper, typeLinks);
  }

  return finalizeMarkdown(lines);
};

type ScriptEventReference = {
  readonly name: string;
  readonly payload: string;
};

const collectScriptEventReferences = (
  checker: ts.TypeChecker,
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
): readonly ScriptEventReference[] => {
  const declaration = declarations.get("Event");
  if (declaration === undefined) {
    return [];
  }

  const eventType = checker.getTypeAtLocation(declaration);
  const variants = eventType.isUnion() ? eventType.types : [eventType];
  const references: ScriptEventReference[] = [];
  for (const variant of variants) {
    const typeProperty = checker.getPropertyOfType(variant, "type");
    if (typeProperty === undefined) {
      continue;
    }
    const typeDeclaration = getSymbolDeclaration(typeProperty) ?? declaration;
    const discriminator = checker.getTypeOfSymbolAtLocation(
      typeProperty,
      typeDeclaration,
    );
    if (!discriminator.isStringLiteral()) {
      continue;
    }

    const fields = checker
      .getPropertiesOfType(variant)
      .filter((property) => property.name !== "type")
      .map((property) => {
        const propertyDeclaration =
          getSymbolDeclaration(property) ?? declaration;
        const optional =
          (property.flags & ts.SymbolFlags.Optional) === 0 ? "" : "?";
        const propertyType = (
          ts.isPropertySignature(propertyDeclaration) &&
          propertyDeclaration.type !== undefined
            ? typeText(
                propertyDeclaration.type,
                propertyDeclaration.getSourceFile(),
              )
            : formatResolvedType(
                checker,
                checker.getTypeOfSymbolAtLocation(
                  property,
                  propertyDeclaration,
                ),
                propertyDeclaration,
              )
        ).replace(/\s+/g, " ");
        return `${property.name}${optional}: ${propertyType}`;
      });

    references.push({
      name: discriminator.value,
      payload: fields.length === 0 ? "{}" : `{ ${fields.join("; ")} }`,
    });
  }

  return references.sort((left, right) => left.name.localeCompare(right.name));
};

const renderEventPayloadReference = (
  payload: string,
  _typeLinks: ReadonlyMap<string, TypeLink>,
): string =>
  `<code>${escapeHtml(payload).replaceAll("|", "&#124;")}</code>`;

const renderEventsReference = (
  lines: string[],
  typeLinks: ReadonlyMap<string, TypeLink>,
  events: readonly ScriptEventReference[],
): void => {
  lines.push(
    "## Choosing an Event API",
    "",
    "Use `on` to run a handler for every matching event, or `once` when the script only needs the next match. Both return Effects that fit normal generator scripts.",
    "",
    "`stream` exposes the same events as a lazy Effect `Stream` for advanced filtering, mapping, and composition. It does no work until the stream is consumed, so most scripts should start with `on` or `once`.",
    "",
    "## Supported Events",
    "",
    "`on`, `once`, and `stream` accept every event below. Payload shapes are generated from the current `Event` union.",
    "",
    "| Event | Payload |",
    "| --- | --- |",
  );

  for (const event of events) {
    lines.push(
      `| ${renderCode(event.name)} | ${renderEventPayloadReference(event.payload, typeLinks)} |`,
    );
  }

  lines.push("");
};

const renderGroup = (
  group: ApiGroup,
  typeLinks: ReadonlyMap<string, TypeLink>,
  events: readonly ScriptEventReference[],
): string => {
  const summary =
    group.summary ||
    (group.id === "api/events"
      ? "Listen for one event, subscribe to repeated events, or compose an event stream."
      : "");
  const lines = [
    frontmatter(group.title, summary, group.label),
    "",
    GENERATED_HEADER,
    "",
    summary,
    "",
  ];

  if (group.id === "api/events") {
    renderEventsReference(lines, typeLinks, events);
  }

  if (group.members.length > 0) {
    lines.push("## Members", "");
    for (const member of group.members) {
      renderMember(lines, member, typeLinks);
    }
  }

  return finalizeMarkdown(lines);
};

const renderTypesIndex = (types: readonly ReferencedTypeDoc[]): string => {
  const lines = [
    frontmatter("Referenced Types", "", "Types"),
    "",
    GENERATED_HEADER,
    "",
    "Referenced types are generated from the types directly linked by the documented API surface. This page is not a complete or authoritative representation of every type available.",
    "",
    "",
    "| Type | Kind | Summary |",
    "| --- | --- | --- |",
    ...types.map(
      (type) =>
        `| ${renderTypeLink(type.name, {
          href: `/scripting/types/${type.slug}/`,
          slug: type.slug,
        })} | ${escapeTableCell(type.kind)} | ${escapeTableCell(type.summary)} |`,
    ),
  ];
  return finalizeMarkdown(lines);
};

const renderTypePage = (
  type: ReferencedTypeDoc,
  typeLinks: ReadonlyMap<string, TypeLink>,
): string => {
  const lines = [
    frontmatter(type.name, type.summary || "", type.name),
    "",
    GENERATED_HEADER,
    "",
  ];

  const generatedAliasSummary =
    type.aliasOf === null ? "" : `Alias of ${type.aliasOf}.`;
  if (type.summary !== "" && type.summary !== generatedAliasSummary) {
    lines.push(type.summary, "");
  }

  if (type.aliasOf !== null) {
    const aliasLink = typeLinks.get(type.aliasOf);
    lines.push(
      aliasLink === undefined
        ? generatedAliasSummary
        : `Alias of ${renderTypeLink(type.aliasOf, aliasLink)}. The resolved members are listed below.`,
      "",
    );
  }

  lines.push("```ts", type.definition, "```", "", renderSource(type), "");

  if (type.properties.length > 0) {
    lines.push("## Properties", "");
    for (const property of type.properties) {
      renderTypeProperty(lines, property);
    }
  }

  if (type.methods.length > 0) {
    lines.push("## Methods", "");
    for (const method of type.methods) {
      renderTypeMethod(lines, method);
    }
  }

  return finalizeMarkdown(lines);
};

const renderSourceLinksModule = (
  types: readonly ReferencedTypeDoc[],
): string => {
  const entries = types
    .filter((type) => type.sourceUrl !== null)
    .map((type) => {
      const sourceReference = `${type.sourcePath}:${type.sourceLine}`;
      return `  ${JSON.stringify(`scripting/types/${type.slug}`)}: { path: ${JSON.stringify(sourceReference)}, url: ${JSON.stringify(type.sourceUrl)} },`;
    })
    .sort();

  return `${GENERATED_HEADER.replace("<!--", "//").replace("-->", "").trim()}

export const scriptSourceLinks: Record<string, { path: string; url: string }> = {
${entries.join("\n")}
};
`;
};

const renderTypePreviewsJson = (types: readonly ReferencedTypeDoc[]): string =>
  `${JSON.stringify(
    {
      types: Object.fromEntries(
        types
          .map((type): [string, object] => [
            type.slug,
            {
              name: type.name,
              slug: type.slug,
              kind: type.kind,
              summary: type.summary,
              aliasOf: type.aliasOf,
              definition: type.definition,
              keys: [
                ...type.properties.map((property) => ({
                  kind: "property",
                  name: property.name,
                  signature: `${property.readonly ? "readonly " : ""}${property.name}${
                    property.optional ? "?" : ""
                  }: ${property.type}`,
                  description: property.summary,
                })),
                ...type.methods.map((method) => ({
                  kind: "method",
                  name: `${method.name}()`,
                  signature: method.signature,
                  description: method.summary,
                })),
              ],
              source:
                type.sourceUrl === null
                  ? null
                  : {
                      path: `${type.sourcePath}:${type.sourceLine}`,
                      url: type.sourceUrl,
                    },
            },
          ])
          .sort(([left], [right]) => left.localeCompare(right)),
      ),
    },
    null,
    2,
  )}\n`;

const renderFiles = (
  options: CliOptions,
  helpers: readonly MemberDoc[],
  namespaces: readonly ApiNamespace[],
  groups: readonly ApiGroup[],
  types: readonly ReferencedTypeDoc[],
  events: readonly ScriptEventReference[],
): ReadonlyArray<RenderedFile> => {
  const typeLinks = buildTypeLinks(types, "/scripting/types/");
  return [
    {
      path: join(options.outputDir, "index.md"),
      content: renderIndex(namespaces),
    },
    {
      path: join(options.outputDir, "api.md"),
      content: renderApiOverview(namespaces),
    },
    {
      path: join(options.outputDir, "features.md"),
      content: renderFeaturesOverview(groups),
    },
    {
      path: join(options.outputDir, "script.md"),
      content: renderScriptOverview(helpers, typeLinks),
    },
    {
      path: join(options.outputDir, "imports.md"),
      content: renderImportsOverview(),
    },
    {
      path: join(options.outputDir, "types/index.md"),
      content: renderTypesIndex(types),
    },
    ...groups.map((group) => ({
      path: join(options.outputDir, `${group.id}.md`),
      content: renderGroup(group, typeLinks, events),
    })),
    ...types.map((type) => ({
      path: join(options.outputDir, `types/${type.slug}.md`),
      content: renderTypePage(type, typeLinks),
    })),
    {
      path: resolve(options.repoRoot, SOURCE_LINKS_OUTPUT),
      content: renderSourceLinksModule(types),
    },
    {
      path: resolve(options.repoRoot, TYPE_PREVIEWS_OUTPUT),
      content: renderTypePreviewsJson(types),
    },
  ];
};

const ensureParentDir = async (path: string): Promise<void> => {
  await fs.mkdir(dirname(path), { recursive: true });
};

const listMarkdownFiles = async (dir: string): Promise<readonly string[]> => {
  const entries = await fs
    .readdir(dir, { withFileTypes: true })
    .catch(() => []);
  const files: string[] = [];
  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listMarkdownFiles(path)));
    } else if (entry.isFile() && entry.name.endsWith(".md")) {
      files.push(path);
    }
  }
  return files;
};

const writeGeneratedDocs = (
  repoRoot: string,
  outputDir: string,
  files: ReadonlyArray<RenderedFile>,
): Effect.Effect<void, unknown> =>
  Effect.gen(function* () {
    const legacyDir = resolve(repoRoot, LEGACY_OUTPUT_DIR);
    if (legacyDir !== outputDir) {
      yield* Effect.tryPromise(() =>
        fs.rm(legacyDir, { recursive: true, force: true }),
      );
    }

    yield* Effect.tryPromise(() => fs.mkdir(outputDir, { recursive: true }));

    const expected = new Set(files.map((file) => resolve(file.path)));
    const existing = yield* Effect.tryPromise(() =>
      listMarkdownFiles(outputDir),
    );
    for (const file of existing) {
      if (!expected.has(resolve(file))) {
        yield* Effect.tryPromise(() => fs.unlink(file));
      }
    }

    for (const file of files) {
      yield* Effect.tryPromise(() => ensureParentDir(file.path));
      const current = yield* Effect.tryPromise(() =>
        fs.readFile(file.path, "utf8"),
      ).pipe(Effect.catch(() => Effect.succeed(null)));
      if (current === file.content) {
        continue;
      }

      yield* Effect.tryPromise(() =>
        fs.writeFile(file.path, file.content, "utf8"),
      );
    }
  });

const main = (options: CliOptions): Effect.Effect<void, unknown> =>
  Effect.gen(function* () {
    const program = createProgram(options.repoRoot);
    const sourceFile = program.getSourceFile(options.sourceFile);
    if (!sourceFile) {
      fail(`Unable to load ${relative(options.repoRoot, options.sourceFile)}`);
    }

    const checker = program.getTypeChecker();
    const declarations = buildDeclarationMap(program);
    const git = yield* getGitSourceInfo(options.repoRoot);
    const { runtimeHelpers, namespaces, groups, typeReferences } =
      collectApiGroups(
        checker,
        declarations,
        options,
        options.includeSourceLinks ? git : null,
      );
    const expandedTypeReferences = expandTypeReferences(
      declarations,
      new Set(typeReferences),
    );
    const typedocProject = yield* createTypeDocProject(
      program,
      options,
      declarations,
      expandedTypeReferences,
    );
    const referencedTypes = collectReferencedTypeDocs(
      checker,
      declarations,
      options,
      options.includeSourceLinks ? git : null,
      typedocProject,
      expandedTypeReferences,
    );
    const scriptEvents = collectScriptEventReferences(checker, declarations);
    const renderedFiles = renderFiles(
      options,
      runtimeHelpers,
      namespaces,
      groups,
      referencedTypes,
      scriptEvents,
    );

    yield* writeGeneratedDocs(
      options.repoRoot,
      options.outputDir,
      renderedFiles,
    );
    yield* Console.log(
      `Generated ${renderedFiles.length} scripting API doc files in ${relative(
        options.repoRoot,
        options.outputDir,
      )}`,
    );
  });

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  const options = parseCliOptions(process.argv.slice(2), DEFAULT_REPO_ROOT);

  main(options).pipe(
    Effect.catch((error) =>
      Effect.gen(function* () {
        yield* Console.error(
          error instanceof Error ? error.message : String(error),
        );
        yield* Effect.sync(() => {
          process.exitCode = 1;
        });
      }),
    ),
    NodeRuntime.runMain,
  );
}
