import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import compat from "core-js-compat";

type RuntimeTargets = {
  readonly chrome: string;
  readonly node: string;
};

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(SCRIPT_DIR, "..");
const APP_DIR = join(REPO_ROOT, "app");
const RUNTIME_TARGETS_PATH = join(APP_DIR, "runtime-targets.json");
const GENERATED_DIR = join(APP_DIR, "src", "shared", "generated");
const rootRequire = createRequire(import.meta.url);
const appRequire = createRequire(join(APP_DIR, "package.json"));
const coreJsVersion = (
  appRequire("core-js/package.json") as { readonly version: string }
).version;
const coreJsCompatVersion = (
  rootRequire("core-js-compat/package.json") as { readonly version: string }
).version;

if (coreJsVersion !== coreJsCompatVersion) {
  throw new Error(
    `core-js (${coreJsVersion}) and core-js-compat (${coreJsCompatVersion}) must use the same version`,
  );
}

const CORE_JS_VERSION = coreJsVersion.split(".").slice(0, 2).join(".");
const GENERATED_HEADER = [
  "// Generated by scripts/gen-core-js-polyfills.ts.",
  "// Do not edit by hand.",
  "",
];

const runtimeTargets = JSON.parse(
  readFileSync(RUNTIME_TARGETS_PATH, "utf8"),
) as RuntimeTargets;

const generatedSource = (
  target: Record<string, string>,
  additionalImports: ReadonlyArray<string> = [],
): string => {
  // Import only stable APIs missing from the target runtime, so esbuild does
  // not bundle and source-map every module pulled in by core-js/stable.
  const modules = compat({
    modules: "core-js/stable",
    targets: target,
    version: CORE_JS_VERSION,
  }).list;

  return [
    ...GENERATED_HEADER,
    ...modules.map(
      (moduleName) => `import "core-js/modules/${moduleName}.js";`,
    ),
    ...additionalImports.map((moduleName) => `import "${moduleName}";`),
    "",
  ].join("\n");
};

const generatedFiles = new Map([
  [
    join(GENERATED_DIR, "polyfills.node.ts"),
    generatedSource(
      { node: runtimeTargets.node },
      ["abort-controller/polyfill.js"],
    ),
  ],
  [
    join(GENERATED_DIR, "polyfills.renderer.ts"),
    generatedSource({ chrome: runtimeTargets.chrome }),
  ],
]);

const isCheck = process.argv.includes("--check");
const staleFiles: string[] = [];

if (!isCheck) {
  mkdirSync(GENERATED_DIR, { recursive: true });
}

for (const [path, source] of generatedFiles) {
  if (isCheck) {
    try {
      if (readFileSync(path, "utf8") !== source) {
        staleFiles.push(path);
      }
    } catch {
      staleFiles.push(path);
    }
    continue;
  }

  writeFileSync(path, source);
}

if (staleFiles.length > 0) {
  console.error(
    `Generated polyfill files are stale:\n${staleFiles
      .map((path) => `- ${path}`)
      .join("\n")}\nRun pnpm polyfills:generate.`,
  );
  process.exitCode = 1;
}
