import fs from "node:fs/promises";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import ts from "typescript";
import {
  getPropertyName,
  parseTypeReference,
  resolveOmitInterfaceAlias,
} from "./ts-ast-utils";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const DEFAULT_REPO_ROOT = join(SCRIPT_DIR, "..");
const DEFAULT_SOURCE_FILE = "app/src/renderer/apps/game/scripting/ScriptApi.ts";
const DEFAULT_OUTPUT_FILE = "docs/public/script-api.d.ts";
const APP_TSCONFIG = "app/tsconfig.json";
const GENERATED_HEADER =
  "// Generated by pnpm run types:scripting. Do not edit directly.";

const BUILTIN_TYPE_NAMES = new Set([
  "A",
  "AbortSignal",
  "Array",
  "Boolean",
  "Date",
  "E",
  "Error",
  "Exclude",
  "Extract",
  "Function",
  "Generator",
  "InitialValue",
  "Key",
  "Map",
  "Math",
  "NewKey",
  "NewValue",
  "Object",
  "Omit",
  "OtherValue",
  "Partial",
  "Pick",
  "Promise",
  "Readonly",
  "ReadonlyArray",
  "ReadonlyMap",
  "Record",
  "Required",
  "Requirements",
  "ResultValue",
  "Set",
  "String",
  "Symbol",
  "TemplateStringsArray",
  "This",
  "Value",
  "any",
  "bigint",
  "boolean",
  "false",
  "never",
  "null",
  "number",
  "object",
  "string",
  "symbol",
  "true",
  "undefined",
  "unknown",
  "void",
]);

const SUPPORT_TYPE_NAMES = new Set([
  "DurationInput",
  "DurationLike",
  "Effect",
  "EffectYieldable",
  "Option",
  "ScriptExecutionError",
  "ScriptEffectModule",
  "ScriptEffectStd",
  "ScriptInputField",
  "ScriptInputType",
  "ScriptInputValue",
  "ScriptInputValues",
  "ScriptInputsDefinition",
  "ScriptModuleExports",
  "ScriptOpaqueModule",
  "ScriptNotReadyError",
  "ScriptOptionModule",
  "ScriptPipe",
  "Scope",
  "Skill",
  "Stream",
]);

const SUPPORT_DECLARATIONS = `
type ScriptPipe = {
  <A>(value: A): A;
  <A, B>(value: A, ab: (a: A) => B): B;
  <A, B, C>(value: A, ab: (a: A) => B, bc: (b: B) => C): C;
  <A, B, C, D>(
    value: A,
    ab: (a: A) => B,
    bc: (b: B) => C,
    cd: (c: C) => D,
  ): D;
};

interface ScriptEffectModule {
  readonly [key: string]: any;
}

interface ScriptOptionModule {
  some<Value>(value: Value): Option<Value>;
  none<Value = never>(): Option<Value>;
  isSome<Value>(
    option: Option<Value>,
  ): option is { readonly _tag: "Some"; readonly value: Value };
  isNone<Value>(option: Option<Value>): option is { readonly _tag: "None" };
  readonly [key: string]: any;
}

interface ScriptOpaqueModule {
  readonly [key: string]: any;
}

interface ScriptEffectStd {
  readonly Effect: ScriptEffectModule;
  readonly Option: ScriptOptionModule;
  readonly Duration: ScriptOpaqueModule;
  readonly pipe: ScriptPipe;
}

declare module "effect" {
  const effect: ScriptEffectStd;
  export = effect;
}

declare module "lucent" {
  const lucent: ScriptLucentStd;
  namespace lucent {
    export type ScriptInputValue = LucentScriptInputValue;
    export type ScriptInputType = LucentScriptInputType;
    export type ScriptInputField = LucentScriptInputField;
    export type ScriptInputsDefinition = LucentScriptInputsDefinition;
    export type ScriptInputValues = LucentScriptInputValues;
    export type ScriptModuleExports = LucentScriptModuleExports;
  }
  export = lucent;
}

type DurationInput = number | string | bigint | DurationLike;

interface DurationLike {
  readonly _tag?: string;
}

type Option<Value> =
  | { readonly _tag: "Some"; readonly value: Value }
  | { readonly _tag: "None" };

type EffectYieldable<
  Value = unknown,
  Error = unknown,
  Requirements = never,
  Next = never,
> = unknown;

interface Effect<
  Value = unknown,
  Error = unknown,
  Requirements = never,
> {
  [Symbol.iterator](): Generator<EffectYieldable<Value, Error>, Value, any>;
}

interface Scope {
  readonly [key: string]: unknown;
}

interface Stream<
  Value = unknown,
  Error = never,
  Requirements = never,
> {
  readonly [key: string]: unknown;
}

interface ScriptExecutionError extends Error {
  readonly _tag: "ScriptExecutionError";
}

interface ScriptNotReadyError extends Error {
  readonly _tag: "ScriptNotReadyError";
}

interface ScriptStopSignal extends Error {
  readonly _tag: "ScriptStopSignal";
}

type Skill = number | string;

type LucentScriptInputValue = string | number | boolean;
type LucentScriptInputType = "string" | "number" | "boolean" | "select";

interface LucentScriptInputFieldBase<
  Type extends LucentScriptInputType,
  Value extends LucentScriptInputValue,
> {
  /** Stable key used by script.inputs.get(key). */
  readonly key: string;
  readonly type: Type;
  readonly label: string;
  readonly description?: string;
  readonly required?: boolean;
  readonly default?: Value;
}

interface LucentScriptStringInputField
  extends LucentScriptInputFieldBase<"string", string> {}

interface LucentScriptNumberInputField
  extends LucentScriptInputFieldBase<"number", number> {}

interface LucentScriptBooleanInputField
  extends LucentScriptInputFieldBase<"boolean", boolean> {}

interface LucentScriptSelectInputField
  extends LucentScriptInputFieldBase<"select", string> {
  readonly options: readonly string[];
}

type LucentScriptInputField =
  | LucentScriptStringInputField
  | LucentScriptNumberInputField
  | LucentScriptBooleanInputField
  | LucentScriptSelectInputField;

interface LucentScriptInputsDefinition {
  /** Stable id used to persist values for this script. */
  readonly id: string;
  readonly fields: readonly LucentScriptInputField[];
}

type LucentScriptInputValues = Readonly<Record<string, LucentScriptInputValue>>;

interface LucentScriptModuleExports extends ScriptMain {
  inputs?: LucentScriptInputsDefinition;
}

type ScriptInputValue = LucentScriptInputValue;
type ScriptInputType = LucentScriptInputType;
type ScriptInputField = LucentScriptInputField;
interface ScriptInputsDefinition extends LucentScriptInputsDefinition {}
type ScriptInputValues = LucentScriptInputValues;
type ScriptModuleExports = LucentScriptModuleExports;
`;

type CliOptions = {
  readonly repoRoot: string;
  readonly sourceFile: string;
  readonly outputFile: string;
};

type Declaration =
  | ts.InterfaceDeclaration
  | ts.TypeAliasDeclaration
  | ts.ClassDeclaration
  | ts.EnumDeclaration;

type RenderedInterface = {
  readonly name: string;
  readonly content: string;
};

class TypesgenError extends Error {
  override readonly name = "TypesgenError";
}

const fail = (message: string): never => {
  throw new TypesgenError(message);
};

const parseCliOptions = (
  args: ReadonlyArray<string>,
  repoRoot: string,
): CliOptions => {
  let source = DEFAULT_SOURCE_FILE;
  let out = DEFAULT_OUTPUT_FILE;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index] ?? fail(`Unable to read argument at ${index}`);
    if (arg === "--") {
      continue;
    }
    if (arg === "--source") {
      source = args[index + 1] ?? fail("--source requires a path");
      index += 1;
      continue;
    }
    if (arg.startsWith("--source=")) {
      source = arg.slice("--source=".length);
      continue;
    }
    if (arg === "--out") {
      out = args[index + 1] ?? fail("--out requires a path");
      index += 1;
      continue;
    }
    if (arg.startsWith("--out=")) {
      out = arg.slice("--out=".length);
      continue;
    }
    fail(`Unknown argument: ${arg}`);
  }

  return {
    repoRoot,
    sourceFile: isAbsolute(source) ? source : resolve(repoRoot, source),
    outputFile: isAbsolute(out) ? out : resolve(repoRoot, out),
  };
};

const createProgram = (repoRoot: string): ts.Program => {
  const configPath = resolve(repoRoot, APP_TSCONFIG);
  const readResult = ts.readConfigFile(configPath, ts.sys.readFile);
  if (readResult.error) {
    fail(ts.flattenDiagnosticMessageText(readResult.error.messageText, "\n"));
  }

  const parsed = ts.parseJsonConfigFileContent(
    readResult.config,
    ts.sys,
    dirname(configPath),
  );

  if (parsed.errors.length > 0) {
    fail(
      parsed.errors
        .map((error) =>
          ts.flattenDiagnosticMessageText(error.messageText, "\n"),
        )
        .join("\n"),
    );
  }

  return ts.createProgram({
    rootNames: parsed.fileNames,
    options: parsed.options,
  });
};

const typeParameterText = (
  sourceFile: ts.SourceFile,
  typeParameters: ts.NodeArray<ts.TypeParameterDeclaration> | undefined,
): string =>
  typeParameters === undefined || typeParameters.length === 0
    ? ""
    : `<${typeParameters.map((parameter) => parameter.getText(sourceFile)).join(", ")}>`;

const formatType = (
  checker: ts.TypeChecker,
  node: ts.TypeNode | undefined,
): string => {
  if (node === undefined) {
    return "unknown";
  }

  const text = checker.typeToString(
    checker.getTypeAtLocation(node),
    node,
    ts.TypeFormatFlags.NoTruncation |
      ts.TypeFormatFlags.UseSingleQuotesForStringLiteralType,
  );
  return normalizeTypeText(text);
};

const formatExpandedType = (
  checker: ts.TypeChecker,
  node: ts.TypeNode,
): string =>
  normalizeTypeText(
    checker.typeToString(
      checker.getTypeAtLocation(node),
      node,
      ts.TypeFormatFlags.NoTruncation |
        ts.TypeFormatFlags.UseSingleQuotesForStringLiteralType |
        ts.TypeFormatFlags.InTypeAlias,
    ),
  );

const typeNodeText = (node: ts.TypeNode, sourceFile: ts.SourceFile): string =>
  normalizeTypeText(node.getText(sourceFile));

const transformTypeText = (type: string): string => {
  let output = type;

  output = output.replace(/\bEffect\.Effect\s*</g, "Effect<");
  output = output.replace(/\bEffect\.Yieldable\s*</g, "EffectYieldable<");
  output = output.replace(/\bOption\.Option\s*</g, "Option<");
  output = output.replace(/\bScope\.Scope\b/g, "Scope");
  output = output.replace(/\bStream\.Stream\s*</g, "Stream<");
  output = output.replace(/\bDuration\.Input\b/g, "DurationInput");
  output = output.replace(/\bReadonlyArray\s*</g, "readonly ");
  output = output.replace(
    /\bBridgeTypes\.InventoryItemSelector\b/g,
    "ObjectSelector<InventoryItemSelectorShape>",
  );
  output = output.replace(
    /\bBridgeTypes\.MonsterSelector\b/g,
    "ObjectSelector<MonsterSelectorShape>",
  );
  output = output.replace(
    /\bBridgeTypes\.ShopItemSelector\b/g,
    "ObjectSelector<ShopItemSelectorShape>",
  );
  output = output.replace(/\bSchema\.Schema\.Type<[^>]+>/g, "unknown");
  output = output.replace(
    /\bData\.TaggedError\([^)]*\)<([^>]*)>/g,
    "Error & $1",
  );

  return output;
};

const normalizeTypeText = (type: string): string =>
  transformTypeText(type)
    .replace(/import\([^)]*\)\./g, "")
    .replace(/\s+/g, " ")
    .trim();

const unwrapEffectReturn = (
  checker: ts.TypeChecker,
  node: ts.TypeNode | undefined,
): string | null => {
  const sourceFile = node?.getSourceFile();
  const reference = parseTypeReference(node);
  if (reference && sourceFile) {
    const args = reference.args.map((arg) => typeNodeText(arg, sourceFile));
    switch (reference.unqualifiedName) {
      case "Effect":
        return `Effect<${args[0] ?? "unknown"}, ${args[1] ?? "never"}${
          args[2] === undefined || args[2] === "never" ? "" : `, ${args[2]}`
        }>`;
      case "BridgeEffect":
        return `Effect<${args[0] ?? "unknown"}, BridgeError>`;
      case "ArmyEffect":
        return `Effect<${args[0] ?? "unknown"}, ${args[1] ?? "never"} | ArmyError | BridgeError>`;
      case "ScriptRecipeEffect":
        return `Effect<${args[0] ?? "unknown"}, unknown>`;
    }
  }

  const formatted = formatType(checker, node);
  if (formatted.startsWith("Effect<")) {
    return formatted;
  }
  return null;
};

const returnTypeText = (
  checker: ts.TypeChecker,
  node: ts.TypeNode | undefined,
): string => unwrapEffectReturn(checker, node) ?? formatType(checker, node);

const parameterText = (
  checker: ts.TypeChecker,
  parameter: ts.ParameterDeclaration,
): string => {
  const sourceFile = parameter.getSourceFile();
  const name = parameter.name.getText(sourceFile);
  const rest = parameter.dotDotDotToken === undefined ? "" : "...";
  const optional =
    parameter.dotDotDotToken !== undefined ||
    (parameter.questionToken === undefined &&
      parameter.initializer === undefined)
      ? ""
      : "?";
  return `${rest}${name}${optional}: ${formatType(checker, parameter.type)}`;
};

const getJsDocComment = (node: ts.Node): string => {
  const docs = (node as ts.Node & { jsDoc?: ts.JSDoc[] }).jsDoc;
  const doc = docs?.[docs.length - 1];
  if (doc === undefined) {
    return "";
  }
  return `${doc
    .getText(node.getSourceFile())
    .trim()
    .split("\n")
    .map((line) => `  ${line.trimStart()}`)
    .join("\n")}\n`;
};

const isDeclaration = (node: ts.Node): node is Declaration =>
  ts.isInterfaceDeclaration(node) ||
  ts.isTypeAliasDeclaration(node) ||
  ts.isClassDeclaration(node) ||
  ts.isEnumDeclaration(node);

const isProjectDeclaration = (declaration: Declaration): boolean => {
  const fileName = declaration.getSourceFile().fileName.replaceAll("\\", "/");
  return (
    !fileName.includes("/node_modules/") &&
    !fileName.includes("/.repos/") &&
    !fileName.endsWith(".test.ts")
  );
};

const symbolDeclaration = (
  checker: ts.TypeChecker,
  symbol: ts.Symbol | undefined,
): { readonly declaration: Declaration; readonly symbol: ts.Symbol } | null => {
  if (symbol === undefined) {
    return null;
  }

  const target =
    (symbol.flags & ts.SymbolFlags.Alias) === 0
      ? symbol
      : checker.getAliasedSymbol(symbol);
  const declaration = target.declarations?.find(
    (candidate): candidate is Declaration =>
      isDeclaration(candidate) && isProjectDeclaration(candidate),
  );
  return declaration === undefined ? null : { declaration, symbol: target };
};

const buildDeclarationMap = (
  program: ts.Program,
  sourceFile: ts.SourceFile,
): ReadonlyMap<string, Declaration> => {
  const checker = program.getTypeChecker();
  const declarations = new Map<string, Declaration>();
  const symbols = new Map<string, ts.Symbol>();
  const pending: Declaration[] = [];
  const visited = new Set<Declaration>();

  const addDeclaration = (
    declaration: Declaration,
    symbol: ts.Symbol | undefined,
  ): void => {
    const name = declaration.name?.text;
    if (
      name === undefined ||
      BUILTIN_TYPE_NAMES.has(name) ||
      SUPPORT_TYPE_NAMES.has(name)
    ) {
      return;
    }

    const current = declarations.get(name);
    const currentSymbol = symbols.get(name);
    if (
      current !== undefined &&
      current !== declaration &&
      currentSymbol !== symbol
    ) {
      fail(
        `Public scripting types contain two declarations named ${name}: ${
          current.getSourceFile().fileName
        } and ${declaration.getSourceFile().fileName}`,
      );
    }
    if (current !== undefined) {
      return;
    }

    declarations.set(name, declaration);
    if (symbol !== undefined) {
      symbols.set(name, symbol);
    }
    pending.push(declaration);
  };

  const addSymbolAt = (node: ts.Node): void => {
    const resolved = symbolDeclaration(
      checker,
      checker.getSymbolAtLocation(node),
    );
    if (resolved !== null) {
      addDeclaration(resolved.declaration, resolved.symbol);
    }
  };

  const visitTypeSyntax = (node: ts.Node): void => {
    if (ts.isTypeReferenceNode(node)) {
      addSymbolAt(node.typeName);
    } else if (ts.isExpressionWithTypeArguments(node)) {
      addSymbolAt(node.expression);
    } else if (ts.isImportTypeNode(node) && node.qualifier !== undefined) {
      addSymbolAt(node.qualifier);
    }
    ts.forEachChild(node, visitTypeSyntax);
  };

  const isVisibleClassMember = (member: ts.ClassElement): boolean => {
    const modifiers = ts.canHaveModifiers(member)
      ? ts.getModifiers(member)
      : undefined;
    return !modifiers?.some(
      (modifier) =>
        modifier.kind === ts.SyntaxKind.PrivateKeyword ||
        modifier.kind === ts.SyntaxKind.ProtectedKeyword ||
        modifier.kind === ts.SyntaxKind.StaticKeyword,
    );
  };

  const visitDeclarationTypes = (declaration: Declaration): void => {
    if (
      ts.isInterfaceDeclaration(declaration) ||
      ts.isTypeAliasDeclaration(declaration)
    ) {
      ts.forEachChild(declaration, visitTypeSyntax);
      return;
    }

    if (!ts.isClassDeclaration(declaration)) {
      return;
    }

    for (const typeParameter of declaration.typeParameters ?? []) {
      visitTypeSyntax(typeParameter);
    }
    for (const clause of declaration.heritageClauses ?? []) {
      visitTypeSyntax(clause);
    }
    for (const member of declaration.members) {
      if (!isVisibleClassMember(member)) {
        continue;
      }
      if (
        ts.isPropertyDeclaration(member) ||
        ts.isGetAccessorDeclaration(member) ||
        ts.isSetAccessorDeclaration(member) ||
        ts.isMethodDeclaration(member)
      ) {
        if (member.type !== undefined) {
          visitTypeSyntax(member.type);
        }
      }
      if (
        ts.isMethodDeclaration(member) ||
        ts.isGetAccessorDeclaration(member) ||
        ts.isSetAccessorDeclaration(member)
      ) {
        for (const typeParameter of member.typeParameters ?? []) {
          visitTypeSyntax(typeParameter);
        }
        for (const parameter of member.parameters) {
          visitTypeSyntax(parameter);
        }
      }
    }
  };

  for (const rootName of ["ScriptContext", "ScriptLucentStd"]) {
    const declaration =
      sourceFile.statements.find(
        (statement): statement is ts.InterfaceDeclaration =>
          ts.isInterfaceDeclaration(statement) &&
          statement.name.text === rootName,
      ) ?? fail(`Unable to find interface ${rootName}`);
    addDeclaration(
      declaration,
      checker.getSymbolAtLocation(declaration.name),
    );
  }

  for (let index = 0; index < pending.length; index += 1) {
    const declaration = pending[index];
    if (declaration === undefined || visited.has(declaration)) {
      continue;
    }
    visited.add(declaration);
    visitDeclarationTypes(declaration);
  }

  return declarations;
};

const getInterface = (
  declarations: ReadonlyMap<string, Declaration>,
  name: string,
  seen = new Set<string>(),
): ts.InterfaceDeclaration => {
  if (seen.has(name)) {
    fail(`Unable to resolve circular interface alias ${name}`);
  }

  const declaration =
    declarations.get(name) ?? fail(`Unable to find interface ${name}`);

  if (ts.isInterfaceDeclaration(declaration)) {
    return declaration;
  }

  if (ts.isTypeAliasDeclaration(declaration)) {
    const reference = parseTypeReference(declaration.type);
    if (reference) {
      const nextSeen = new Set(seen);
      nextSeen.add(name);
      const omitted = resolveOmitInterfaceAlias(
        reference,
        (targetName) => getInterface(declarations, targetName, nextSeen),
        { referenceName: "unqualifiedName" },
      );
      if (omitted) {
        return omitted;
      }
      return getInterface(declarations, reference.unqualifiedName, nextSeen);
    }
  }

  return fail(`Unable to find interface ${name}`);
};

const getDeclaration = (
  declarations: ReadonlyMap<string, Declaration>,
  name: string,
): Declaration | null => declarations.get(name) ?? null;

const parseEffectValueShape = (
  node: ts.TypeNode | undefined,
): string | null => {
  const reference = parseTypeReference(node);
  if (
    !reference ||
    reference.unqualifiedName !== "EffectValue" ||
    reference.args.length !== 1
  ) {
    return null;
  }

  const target = parseTypeReference(reference.args[0]);
  return target?.unqualifiedName ?? null;
};

const interfaceNameForProperty = (propertyName: string): string => {
  const normalized = propertyName
    .replace(/(^|[-_\s]+)([a-zA-Z0-9])/g, (_match, _separator, char: string) =>
      char.toUpperCase(),
    )
    .replace(/[^A-Za-z0-9_$]/g, "");
  return `${normalized}Api`;
};

const nestedInterfaceName = (
  parentName: string,
  propertyName: string,
): string =>
  `${parentName.replace(/Api$/, "")}${interfaceNameForProperty(propertyName)}`;

const collectTypeNames = (text: string, output: Set<string>): void => {
  const typeText = text
    .replaceAll(/\/\*\*[\s\S]*?\*\//g, "")
    .replaceAll(/"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'/g, "");
  for (const match of typeText.matchAll(
    /\b[A-Za-z_$][A-Za-z0-9_$]*\b/g,
  )) {
    const token = match[0];
    if (!BUILTIN_TYPE_NAMES.has(token) && /^[A-Z]/.test(token)) {
      output.add(token);
    }
  }
};

const renderMethodSignature = (
  checker: ts.TypeChecker,
  node: ts.MethodSignature | ts.FunctionTypeNode,
  name: string,
): string => {
  const sourceFile = node.getSourceFile();
  const typeParameters = typeParameterText(sourceFile, node.typeParameters);
  const parameters = node.parameters
    .map((parameter) => parameterText(checker, parameter))
    .join(", ");
  return `${name}${typeParameters}(${parameters}): ${returnTypeText(checker, node.type)};`;
};

const renderCallSignature = (
  checker: ts.TypeChecker,
  node: ts.CallSignatureDeclaration,
): string => {
  const sourceFile = node.getSourceFile();
  const typeParameters = typeParameterText(sourceFile, node.typeParameters);
  const parameters = node.parameters
    .map((parameter) => parameterText(checker, parameter))
    .join(", ");
  return `${typeParameters}(${parameters}): ${returnTypeText(checker, node.type)};`;
};

type RenderState = {
  readonly checker: ts.TypeChecker;
  readonly declarations: ReadonlyMap<string, Declaration>;
  readonly rendered: Map<string, RenderedInterface>;
  readonly referencedTypes: Set<string>;
};

const renderInterfaceFromDeclaration = (
  state: RenderState,
  declaration: ts.InterfaceDeclaration,
  outputName: string,
): string => {
  const lines: string[] = [`interface ${outputName} {`];

  for (const member of declaration.members) {
    if (ts.isCallSignatureDeclaration(member)) {
      const signature = renderCallSignature(state.checker, member);
      collectTypeNames(signature, state.referencedTypes);
      lines.push(`${getJsDocComment(member)}    ${signature}`);
      continue;
    }

    if (ts.isMethodSignature(member)) {
      const name = getPropertyName(member.name);
      if (name === null) {
        continue;
      }
      const signature = renderMethodSignature(state.checker, member, name);
      collectTypeNames(signature, state.referencedTypes);
      lines.push(`${getJsDocComment(member)}    ${signature}`);
      continue;
    }

    if (!ts.isPropertySignature(member)) {
      continue;
    }

    const name = getPropertyName(member.name);
    if (name === null) {
      continue;
    }

    if (member.type && ts.isFunctionTypeNode(member.type)) {
      const signature = renderMethodSignature(state.checker, member.type, name);
      collectTypeNames(signature, state.referencedTypes);
      lines.push(`${getJsDocComment(member)}    ${signature}`);
      continue;
    }

    const shapeName = parseEffectValueShape(member.type);
    if (shapeName !== null) {
      const childOutputName =
        outputName === "ScriptApi" || outputName === "ScriptLucentStd"
          ? interfaceNameForProperty(name)
          : nestedInterfaceName(outputName, name);
      renderApiInterface(state, shapeName, childOutputName);
      lines.push(`    readonly ${name}: ${childOutputName};`);
      continue;
    }

    const reference = parseTypeReference(member.type);
    if (reference !== null && SUPPORT_TYPE_NAMES.has(reference.unqualifiedName)) {
      const readonly = member.modifiers?.some(
        (modifier) => modifier.kind === ts.SyntaxKind.ReadonlyKeyword,
      )
        ? "readonly "
        : "";
      const optional = member.questionToken === undefined ? "" : "?";
      lines.push(
        `${getJsDocComment(member)}    ${readonly}${name}${optional}: ${formatType(
          state.checker,
          member.type,
        )};`,
      );
      continue;
    }

    const childDeclaration =
      reference === null
        ? null
        : getDeclaration(state.declarations, reference.unqualifiedName);
    if (childDeclaration && ts.isInterfaceDeclaration(childDeclaration)) {
      const childOutputName = childDeclaration.name.text;
      renderApiInterface(state, childDeclaration.name.text, childOutputName);
      lines.push(`    readonly ${name}: ${childOutputName};`);
      continue;
    }

    const readonly = member.modifiers?.some(
      (modifier) => modifier.kind === ts.SyntaxKind.ReadonlyKeyword,
    )
      ? "readonly "
      : "";
    const optional = member.questionToken === undefined ? "" : "?";
    const type = formatType(state.checker, member.type);
    collectTypeNames(type, state.referencedTypes);
    lines.push(
      `${getJsDocComment(member)}    ${readonly}${name}${optional}: ${type};`,
    );
  }

  lines.push("}");
  return lines.join("\n");
};

const renderApiInterface = (
  state: RenderState,
  sourceName: string,
  outputName: string,
): void => {
  if (state.rendered.has(outputName)) {
    return;
  }

  const declaration = getInterface(state.declarations, sourceName);
  state.rendered.set(outputName, {
    name: outputName,
    content: renderInterfaceFromDeclaration(state, declaration, outputName),
  });
};

const stripDeclarationText = (text: string): string =>
  transformTypeText(text)
    .replace(/^export\s+/gm, "")
    .replace(/^declare\s+/gm, "")
    .replace(/\bprivate\s+/g, "")
    .replace(/\bprotected\s+/g, "")
    .replace(/#private;\n?/g, "")
    .replace(/import\([^)]*\)\./g, "")
    .replace(/Schema\.Literals<[^;]+;/g, "unknown;");

const isSimpleHeritageExpression = (expression: ts.Expression): boolean =>
  ts.isIdentifier(expression) ||
  (ts.isPropertyAccessExpression(expression) &&
    isSimpleHeritageExpression(expression.expression));

const renderClassAsInterface = (
  checker: ts.TypeChecker,
  declaration: ts.ClassDeclaration,
): string => {
  const name = declaration.name?.text ?? fail("Cannot render anonymous class");
  const sourceFile = declaration.getSourceFile();
  const typeParameters = typeParameterText(
    sourceFile,
    declaration.typeParameters,
  );
  const extendsClause = declaration.heritageClauses
    ?.flatMap((clause) =>
      clause.token === ts.SyntaxKind.ExtendsKeyword
        ? clause.types
            .filter((type) => isSimpleHeritageExpression(type.expression))
            .map((type) => type.getText(type.getSourceFile()))
        : [],
    )
    .at(0);
  const lines = [
    `interface ${name}${typeParameters}${extendsClause ? ` extends ${extendsClause}` : ""} {`,
  ];

  for (const member of declaration.members) {
    const modifiers = ts.canHaveModifiers(member)
      ? ts.getModifiers(member)
      : undefined;
    if (
      modifiers?.some(
        (modifier) =>
          modifier.kind === ts.SyntaxKind.PrivateKeyword ||
          modifier.kind === ts.SyntaxKind.ProtectedKeyword ||
          modifier.kind === ts.SyntaxKind.StaticKeyword,
      )
    ) {
      continue;
    }

    if (ts.isGetAccessorDeclaration(member)) {
      const propertyName = getPropertyName(member.name);
      if (propertyName === null) continue;
      lines.push(
        `  readonly ${propertyName}: ${returnTypeText(checker, member.type)};`,
      );
      continue;
    }

    if (ts.isPropertyDeclaration(member)) {
      const propertyName = getPropertyName(member.name);
      if (propertyName === null) continue;
      const optional = member.questionToken === undefined ? "" : "?";
      lines.push(
        `  ${propertyName}${optional}: ${formatType(checker, member.type)};`,
      );
      continue;
    }

    if (ts.isMethodDeclaration(member)) {
      const methodName = getPropertyName(member.name);
      if (methodName === null) continue;
      const sourceFile = member.getSourceFile();
      const typeParameters = typeParameterText(
        sourceFile,
        member.typeParameters,
      );
      const parameters = member.parameters
        .map((parameter) => parameterText(checker, parameter))
        .join(", ");
      lines.push(
        `  ${methodName}${typeParameters}(${parameters}): ${returnTypeText(checker, member.type)};`,
      );
    }
  }

  lines.push("}");
  return lines.join("\n");
};

const isSchemaTypeAlias = (declaration: ts.TypeAliasDeclaration): boolean => {
  const reference = parseTypeReference(declaration.type);
  return reference?.name === "Schema.Schema.Type";
};

const renderTypeAlias = (
  checker: ts.TypeChecker,
  declaration: ts.TypeAliasDeclaration,
): string => {
  const typeParameters = typeParameterText(
    declaration.getSourceFile(),
    declaration.typeParameters,
  );
  const raw = stripDeclarationText(
    declaration.getText(declaration.getSourceFile()),
  );
  if (!isSchemaTypeAlias(declaration) && !raw.includes("typeof ")) {
    return raw;
  }

  return `type ${declaration.name.text}${typeParameters} = ${formatExpandedType(
    checker,
    declaration.type,
  )};`;
};

const declarationText = (
  checker: ts.TypeChecker,
  declaration: Declaration,
): string | null => {
  const sourceFile = declaration.getSourceFile();
  const name = declaration.name?.text;
  if (
    name === "ScriptExecutionError" ||
    name === "ScriptNotReadyError" ||
    name === "ScriptStopSignal"
  ) {
    return null;
  }

  if (ts.isClassDeclaration(declaration)) {
    return renderClassAsInterface(checker, declaration);
  }

  if (ts.isTypeAliasDeclaration(declaration)) {
    return renderTypeAlias(checker, declaration);
  }

  if (ts.isEnumDeclaration(declaration)) {
    return stripDeclarationText(declaration.getText(sourceFile)).replace(
      /^enum\s+/,
      "declare enum ",
    );
  }

  return stripDeclarationText(declaration.getText(sourceFile));
};

const renderReferencedDeclarations = (
  state: RenderState,
  apiInterfaceNames: ReadonlySet<string>,
): readonly string[] => {
  const output: string[] = [];
  const seen = new Set([...apiInterfaceNames, ...SUPPORT_TYPE_NAMES]);
  for (const declaration of state.declarations.values()) {
    const visit = (node: ts.Node): void => {
      if (ts.isTypeParameterDeclaration(node)) {
        seen.add(node.name.text);
      }
      ts.forEachChild(node, visit);
    };
    visit(declaration);
  }
  const pending = Array.from(state.referencedTypes).sort();

  for (let index = 0; index < pending.length; index += 1) {
    const name = pending[index];
    if (!name || seen.has(name) || BUILTIN_TYPE_NAMES.has(name)) {
      continue;
    }
    seen.add(name);

    const declaration =
      state.declarations.get(name) ??
      fail(`Unable to resolve public scripting type ${name}`);

    const rendered = declarationText(state.checker, declaration);
    if (rendered === null) {
      continue;
    }
    const text = rendered;
    output.push(text);
    collectTypeNames(text, state.referencedTypes);
    for (const referenced of Array.from(state.referencedTypes)) {
      if (!seen.has(referenced) && !pending.includes(referenced)) {
        pending.push(referenced);
      }
    }
  }

  return output;
};

const renderScriptTypes = (
  program: ts.Program,
  declarations: ReadonlyMap<string, Declaration>,
): string => {
  const checker = program.getTypeChecker();
  const state: RenderState = {
    checker,
    declarations,
    rendered: new Map(),
    referencedTypes: new Set(),
  };

  renderApiInterface(state, "ScriptContext", "ScriptContext");
  renderApiInterface(state, "ScriptLucentStd", "ScriptLucentStd");

  const interfaceNames = new Set(state.rendered.keys());
  const referencedDeclarations = renderReferencedDeclarations(
    state,
    interfaceNames,
  );
  const interfaces = Array.from(state.rendered.values())
    .sort((left, right) => {
      if (left.name === "ScriptContext") return -1;
      if (right.name === "ScriptContext") return 1;
      if (left.name === "ScriptLucentStd") return -1;
      if (right.name === "ScriptLucentStd") return 1;
      if (left.name === "ScriptApi") return -1;
      if (right.name === "ScriptApi") return 1;
      if (left.name === "ScriptRuntimeApi") return -1;
      if (right.name === "ScriptRuntimeApi") return 1;
      return left.name.localeCompare(right.name);
    })
    .map((entry) => entry.content);

  const lines = [
    GENERATED_HEADER,
    "",
    "/* eslint-disable */",
    "",
    SUPPORT_DECLARATIONS.trimEnd(),
    "",
    "type ScriptMain = () => Generator<Effect<any, any, never>, unknown, any>;",
    "",
    ...interfaces,
    "",
    ...referencedDeclarations,
    "",
  ];

  return `${lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
};

const validateGeneratedTypes = (content: string): void => {
  const sourceFile = ts.createSourceFile(
    "script-api.d.ts",
    content,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  );
  const interfaces = new Map<string, ts.InterfaceDeclaration>();
  const typeAliases = new Map<string, ts.TypeAliasDeclaration>();

  for (const statement of sourceFile.statements) {
    if (ts.isInterfaceDeclaration(statement)) {
      interfaces.set(statement.name.text, statement);
    } else if (ts.isTypeAliasDeclaration(statement)) {
      typeAliases.set(statement.name.text, statement);
    }
  }

  for (const name of [
    "ScriptEventsOn",
    "ScriptPacketOn",
    "ScriptWaitForEvent",
    "ScriptWaitForPacket",
  ]) {
    const declaration = interfaces.get(name);
    if (
      declaration === undefined ||
      !declaration.members.some(ts.isCallSignatureDeclaration)
    ) {
      fail(`Generated ${name} must retain at least one call signature`);
    }
  }

  const packetForDirection = typeAliases.get("PacketForDirection");
  if (
    packetForDirection === undefined ||
    !packetForDirection.type
      .getText(sourceFile)
      .replace(/\s+/gu, " ")
      .includes("Extract< FlashPacket,")
  ) {
    fail("Generated PacketForDirection must extract from FlashPacket");
  }
  if (content.includes("Scope.Scope")) {
    fail("Generated scripting types must normalize Scope.Scope to Scope");
  }
  if (content.includes("Stream.Stream")) {
    fail("Generated scripting types must normalize Stream.Stream to Stream");
  }
  if (/\binterface\s+Extract\b/u.test(content)) {
    fail("Generated scripting types must use the built-in Extract type");
  }
  if (/^type Event\s*=/mu.test(content)) {
    fail("Generated scripting types must not shadow the DOM Event type");
  }
  const directSelfAlias =
    /^type ([A-Za-z_$][A-Za-z0-9_$]*)\s*=\s*\1\s*;$/mu.exec(content);
  if (directSelfAlias !== null) {
    fail(`Generated ${directSelfAlias[1]} type must not alias itself`);
  }
  for (const name of ["R", "Json", "State", "Session"]) {
    if (new RegExp(`^interface ${name}\\b`, "mu").test(content)) {
      fail(`Generated scripting types must not contain an opaque ${name}`);
    }
  }
};

const main = async (options: CliOptions): Promise<void> => {
  const program = createProgram(options.repoRoot);
  const sourceFile =
    program.getSourceFile(options.sourceFile) ??
    fail(`Unable to load ${relative(options.repoRoot, options.sourceFile)}`);

  const declarations = buildDeclarationMap(program, sourceFile);
  const content = renderScriptTypes(program, declarations);
  validateGeneratedTypes(content);

  await fs.mkdir(dirname(options.outputFile), { recursive: true });
  const current = await fs
    .readFile(options.outputFile, "utf8")
    .catch(() => null);
  if (current !== content) {
    await fs.writeFile(options.outputFile, content, "utf8");
  }

  console.info(
    `Generated scripting types at ${relative(options.repoRoot, options.outputFile)}`,
  );
};

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  main(parseCliOptions(process.argv.slice(2), DEFAULT_REPO_ROOT)).catch(
    (error) => {
      console.error(error instanceof Error ? error.message : String(error));
      process.exitCode = 1;
    },
  );
}
